// Differential oracle replay: parses tests/fixtures/autoremesher_diff.txt
// (generated by the C++ autoremesher_diff_dump tool), re-runs every case
// with the Rust port, and asserts the port matches the C++ implementation.
//
// Three tiers (the C++ engine is self-nondeterministic on marginal cases:
// ~1e-13 TBB cover noise amplified by extractor integer rounding flips
// topology run to run — demonstrated by three dump runs during
// development, listed in the dump tool's isEpxId/isEcxId):
// - CASE (strict): same ok flag, same remeshed verts/quads/uvs (values
//   within scale-aware 1e-6; indices positional-exact, with a QPX-class
//   remap+canonicalize fallback that accepts order-only differences and
//   notes them loudly), same island counts, same decimated/isotropic
//   outputs, same symmetry plane, same phase-report structure (names +
//   order + counts, timings stripped), and the same progress sequence —
//   exact (bitwise f32 + status) on single-island cases, robust facts
//   (serial prefix/suffix, monotonic middle, range) on multi-island
//   cases where thread interleaving varies run to run on both sides.
// - ECX (strict except the connection capture): real outputs stable
//   across C++ runs, but the raw extracted-connection capture flipped.
//   Everything strict except CONN counts/values and MOVED, which report.
// - EPX (robustness-only): non-manifold soup / degenerate meshes (not
//   downstream-plausible; ill-conditioned covers by construction) plus
//   listed real-output flippers. The port must match every deterministic
//   structural fact (ok, island length, decimated + isotropic outputs,
//   phase head/tail, progress prefix/suffix + robust facts) and solve
//   everything C++ solves; cover-derived quantities (remeshed
//   verts/quads/uvs, IUV/IOUV/SING values and singular counts,
//   connections) are reported, not asserted.
use retopo_core::auto_remesher::{AutoRemesher, AutoRemesherProgressHandler, ModelType};
use retopo_core::vector2::Vector2;
use retopo_core::vector3::Vector3;
use std::ffi::c_void;
use std::sync::{Arc, Mutex};

const FIXTURE: &str = include_str!("../../../tests/fixtures/autoremesher_diff.txt");
const TOL: f64 = 1e-6;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn int(&mut self) -> i64 {
        self.word().parse().expect("bad int")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn frac(&mut self) -> f32 {
        self.word().parse().expect("bad f32")
    }
    fn v3(&mut self) -> Vector3 {
        let x = self.num();
        let y = self.num();
        let z = self.num();
        Vector3::new(x, y, z)
    }
    fn v2(&mut self) -> Vector2 {
        let x = self.num();
        let y = self.num();
        Vector2::new(x, y)
    }
}

fn status_token(status: &str) -> String {
    if status.is_empty() {
        return ".".to_string();
    }
    status.replace(' ', "_")
}

fn record_event(tag: *mut c_void, progress: f32, status: &str) {
    let events = unsafe { &*(tag as *const Mutex<Vec<(f32, String)>>) };
    events
        .lock()
        .unwrap()
        .push((progress, status_token(status)));
}

struct EpxStats {
    cases: usize,
    both_ok: usize,
    value_agree: usize,
    max_diff: f64,
    max_diff_at: String,
}

#[derive(Clone, Copy, PartialEq)]
enum Mode {
    Strict,
    ConnOnly,
    Robust,
}

struct ValState<'a> {
    strict: bool,
    max_diff: &'a mut f64,
    max_diff_at: &'a mut String,
    mismatches: &'a mut Vec<String>,
    stats: &'a mut EpxStats,
    case_agrees: &'a mut bool,
}

impl ValState<'_> {
    fn check(&mut self, case: &str, label: &str, rust: f64, expect: f64) {
        if rust.is_nan() != expect.is_nan() {
            // NaN skew is a logic bug on both sides (no NaN inputs exist
            // in the corpus), so it mismatches in both sections.
            if self.strict {
                self.mismatches.push(format!(
                    "{case}: {label} NaN skew (rust={rust} cpp={expect})"
                ));
            } else {
                self.stats.max_diff = f64::INFINITY;
                self.stats.max_diff_at = format!("{case} {label}");
                *self.case_agrees = false;
            }
            return;
        }
        if rust.is_nan() {
            return;
        }
        let d = (rust - expect).abs();
        let rel = d / expect.abs().max(1.0);
        let tol = TOL * expect.abs().max(1.0);
        if self.strict {
            if rel > *self.max_diff {
                *self.max_diff = rel;
                *self.max_diff_at = format!("{case} {label} rust={rust:.6e} cpp={expect:.6e}");
            }
            if d > tol {
                self.mismatches.push(format!(
                    "{case}: {label} diverged (rust={rust} cpp={expect} diff={d:.3e} tol={tol:.3e})"
                ));
            }
        } else {
            if d > self.stats.max_diff {
                self.stats.max_diff = d;
                self.stats.max_diff_at = format!("{case} {label} rust={rust:.6e} cpp={expect:.6e}");
            }
            if d > tol {
                *self.case_agrees = false;
            }
        }
    }
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("ARDIFF1");
    let mut strict_cases = 0usize;
    let mut ecx_cases = 0usize;
    let mut ecx_conn_agree = 0usize;
    let mut order_only_notes = 0usize;
    let mut stats = EpxStats {
        cases: 0,
        both_ok: 0,
        value_agree: 0,
        max_diff: 0.0,
        max_diff_at: String::new(),
    };
    let mut max_diff = 0.0f64;
    let mut max_diff_at = String::new();
    let mut mismatches: Vec<String> = Vec::new();
    // Structural-fact coverage: every section below must fire at least
    // once, so a silently-skipped comparison fails the run.
    let mut saw_ok_true = false;
    let mut saw_ok_false = false;
    let mut saw_single_exact_prog = false;
    let mut saw_multi_robust_prog = false;
    let mut saw_quiet_no_leaf = false;
    let mut saw_noisy_leaf = false;
    let mut saw_decimated = false;
    let mut saw_sym_active = false;
    let mut saw_multi_island = false;
    loop {
        let tag = c.word();
        if tag == "CASES" {
            let total = c.uint();
            assert_eq!(
                total,
                strict_cases + ecx_cases + stats.cases,
                "CASES trailer disagrees with parsed count"
            );
            break;
        }
        let mode = match tag.as_str() {
            "CASE" => Mode::Strict,
            "ECX" => Mode::ConnOnly,
            "EPX" => Mode::Robust,
            other => panic!("unexpected fixture tag: {other}"),
        };
        // Real-output asserts hold on CASE + ECX; CONN asserts on CASE only.
        let strict = mode != Mode::Robust;
        let conn_strict = mode == Mode::Strict;
        let id = c.int();
        c.expect("KIND");
        let kind = c.word();
        c.expect("NV");
        let nv = c.uint();
        c.expect("NT");
        let nt = c.uint();
        c.expect("TARGET");
        let target = c.uint();
        c.expect("SCALING");
        let scaling = c.num();
        c.expect("ADAPT");
        let adapt = c.num();
        c.expect("HARD");
        let hard = c.num();
        c.expect("ANISO");
        let aniso = c.num();
        c.expect("SMOOTH");
        let smooth = c.num();
        c.expect("MODEL");
        let model = c.int();
        c.expect("SYM");
        let sym = c.int() != 0;
        c.expect("SYMAXIS");
        let symaxis = c.int();
        c.expect("GUIDES");
        let n_guides = c.uint();
        c.expect("SHARPS");
        let n_sharps = c.uint();
        c.expect("DENSITY");
        let density_mode = c.int();
        c.expect("UVS");
        let want_uvs = c.int() != 0;
        c.expect("QUIET");
        let quiet = c.int() != 0;
        let case = format!(
            "{} {id} ({kind})",
            match mode {
                Mode::Strict => "case",
                Mode::ConnOnly => "ecx",
                Mode::Robust => "epx",
            }
        );
        let _ = density_mode;

        let mut vertices = Vec::with_capacity(nv);
        for _ in 0..nv {
            c.expect("V");
            vertices.push(c.v3());
        }
        let mut triangles = Vec::with_capacity(nt);
        for _ in 0..nt {
            c.expect("T");
            let k = c.uint();
            let mut tri = Vec::with_capacity(k);
            for _ in 0..k {
                tri.push(c.uint());
            }
            triangles.push(tri);
        }
        let mut guides = Vec::with_capacity(n_guides);
        for _ in 0..n_guides {
            c.expect("GUIDE");
            let m = c.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(c.v3());
            }
            guides.push(line);
        }
        let mut sharps = Vec::with_capacity(n_sharps);
        for _ in 0..n_sharps {
            c.expect("SHARP");
            let m = c.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(c.v3());
            }
            sharps.push(line);
        }
        c.expect("RHO");
        let n_rho = c.uint();
        let mut rho = Vec::with_capacity(n_rho);
        for _ in 0..n_rho {
            rho.push(c.num());
        }

        // Drive the port exactly like the dump tool drives the C++ (same
        // setter order, same even-id feature-alias rule).
        let events: Arc<Mutex<Vec<(f32, String)>>> = Arc::new(Mutex::new(Vec::new()));
        let tag_ptr = Arc::into_raw(Arc::clone(&events)) as *mut c_void;
        let mut remesher = AutoRemesher::new(&vertices, &triangles);
        remesher.set_target_triangle_count(target);
        remesher.set_scaling(scaling);
        remesher.set_model_type(if model == 0 {
            ModelType::Organic
        } else {
            ModelType::HardSurface
        });
        remesher.set_gradient_adaptivity(adapt);
        remesher.set_anisotropy(aniso);
        remesher.set_sharp_edge_degrees(hard);
        remesher.set_smooth_normal_degrees(smooth);
        remesher.set_symmetry_enabled(sym);
        remesher.set_symmetry_plane(symaxis as i32);
        remesher.set_guide_polylines(guides);
        if id % 2 == 0 {
            remesher.set_feature_polylines(sharps);
        } else {
            remesher.set_sharp_polylines(sharps);
        }
        remesher.set_density_multipliers(&rho);
        remesher.set_compute_remeshed_uvs(want_uvs);
        remesher.set_quiet(quiet);
        let handler: AutoRemesherProgressHandler = record_event;
        remesher.set_progress_handler(Some(handler));
        remesher.set_tag(tag_ptr);
        let ok = remesher.remesh();
        let got_events = events.lock().unwrap().clone();
        unsafe {
            drop(Arc::from_raw(tag_ptr as *const Mutex<Vec<(f32, String)>>));
        }

        c.expect("PROG");
        let n_prog = c.uint();
        let mut exp_events = Vec::with_capacity(n_prog);
        for _ in 0..n_prog {
            let f = c.frac();
            let s = c.word();
            exp_events.push((f, s));
        }
        c.expect("RES");
        let exp_ok = c.int() != 0;
        match mode {
            Mode::Strict => strict_cases += 1,
            Mode::ConnOnly => ecx_cases += 1,
            Mode::Robust => stats.cases += 1,
        }
        if ok {
            saw_ok_true = true;
        } else {
            saw_ok_false = true;
        }
        if ok != exp_ok {
            mismatches.push(format!("{case}: ok flag skew (rust={ok} cpp={exp_ok})"));
        }
        if !exp_ok {
            // Rejected input: exactly one handler call at 1.0 naming the
            // reason, outputs untouched.
            if got_events.len() != 1 || exp_events.len() != 1 {
                mismatches.push(format!(
                    "{case}: reject event count skew (rust={} cpp={})",
                    got_events.len(),
                    exp_events.len()
                ));
            } else {
                let (rf, rs) = &got_events[0];
                let (ef, es) = &exp_events[0];
                if rf.to_bits() != ef.to_bits() || rs != es {
                    mismatches.push(format!(
                        "{case}: reject event skew (rust=({rf},{rs}) cpp=({ef},{es}))"
                    ));
                }
            }
            if !remesher.remeshed_vertices().is_empty()
                || !remesher.remeshed_quads().is_empty()
                || !remesher.remeshed_vertex_uvs().is_empty()
                || !remesher.phase_report().is_empty()
                || !remesher.island_output_quad_counts().is_empty()
            {
                mismatches.push(format!("{case}: reject case populated outputs"));
            }
            continue;
        }
        if !ok {
            // Already reported the ok skew; nothing further to compare.
            // Still consume the output sections to stay in sync.
            consume_outputs(&mut c);
            continue;
        }

        // Parse the expected outputs.
        c.expect("RV");
        let n_rv = c.uint();
        let mut exp_rv = Vec::with_capacity(n_rv);
        for _ in 0..n_rv {
            exp_rv.push(c.v3());
        }
        c.expect("RQ");
        let n_rq = c.uint();
        let mut exp_rq = Vec::with_capacity(n_rq);
        for _ in 0..n_rq {
            let k = c.uint();
            let mut row = Vec::with_capacity(k);
            for _ in 0..k {
                row.push(c.uint());
            }
            exp_rq.push(row);
        }
        c.expect("RUV");
        let n_ruv = c.uint();
        let mut exp_ruv = Vec::with_capacity(n_ruv);
        for _ in 0..n_ruv {
            exp_ruv.push(c.v2());
        }
        c.expect("ISL");
        let n_isl = c.uint();
        let mut exp_isl = Vec::with_capacity(n_isl);
        for _ in 0..n_isl {
            exp_isl.push(c.uint());
        }
        c.expect("DEC");
        let exp_dec = c.int() != 0;
        let n_dv = c.uint();
        let n_dt = c.uint();
        let mut exp_dv = Vec::with_capacity(n_dv);
        for _ in 0..n_dv {
            exp_dv.push(c.v3());
        }
        let mut exp_dt = Vec::with_capacity(n_dt);
        for _ in 0..n_dt {
            let tk = c.word();
            assert!(tk.starts_with('T'), "{case}: bad DEC tri tag {tk}");
            let k: usize = tk[1..].parse().expect("bad tri len");
            let mut row = Vec::with_capacity(k);
            for _ in 0..k {
                row.push(c.uint());
            }
            exp_dt.push(row);
        }
        c.expect("ISO");
        let n_iv = c.uint();
        let n_it = c.uint();
        let mut exp_iv = Vec::with_capacity(n_iv);
        for _ in 0..n_iv {
            exp_iv.push(c.v3());
        }
        let mut exp_it = Vec::with_capacity(n_it);
        for _ in 0..n_it {
            let tk = c.word();
            assert!(tk.starts_with('T'), "{case}: bad ISO tri tag {tk}");
            let k: usize = tk[1..].parse().expect("bad tri len");
            let mut row = Vec::with_capacity(k);
            for _ in 0..k {
                row.push(c.uint());
            }
            exp_it.push(row);
        }
        c.expect("IUV");
        let n_iuv = c.uint();
        let mut exp_iuv = Vec::with_capacity(n_iuv);
        for _ in 0..n_iuv {
            exp_iuv.push((c.v2(), c.v2(), c.v2()));
        }
        c.expect("IOUV");
        let n_iouv = c.uint();
        let mut exp_iouv = Vec::with_capacity(n_iouv);
        for _ in 0..n_iouv {
            exp_iouv.push((c.v2(), c.v2(), c.v2()));
        }
        c.expect("SING");
        let n_sing = c.uint();
        let mut exp_sing = Vec::with_capacity(n_sing);
        for _ in 0..n_sing {
            exp_sing.push(c.v3());
        }
        c.expect("CONN");
        let n_conn = c.uint();
        let n_moved = c.uint();
        let mut exp_conn = Vec::with_capacity(n_conn);
        for _ in 0..n_conn {
            exp_conn.push((c.v3(), c.v3()));
        }
        let mut exp_moved = Vec::with_capacity(n_moved);
        for _ in 0..n_moved {
            exp_moved.push(c.uint());
        }
        c.expect("SYM");
        let exp_symaxis = c.int();
        let exp_symoff = c.num();
        let exp_symscore = c.num();
        c.expect("PHASE");
        let n_phase = c.uint();
        let mut exp_phase = Vec::with_capacity(n_phase);
        for _ in 0..n_phase {
            let tok = c.word();
            assert!(
                tok.starts_with('[') && tok.ends_with(']'),
                "{case}: bad PHASE token {tok}"
            );
            exp_phase.push(tok[1..tok.len() - 1].to_string());
        }

        let mut case_agrees = true;
        // Progress: exact on single-island strict cases; robust facts
        // everywhere else (multi-island interleaving varies run to run on
        // both sides, and EPX branch choices can move downstream steps).
        let single = exp_isl.len() <= 1;
        if !single {
            saw_multi_island = true;
        }
        if strict && single {
            saw_single_exact_prog = true;
            if got_events.len() != exp_events.len() {
                mismatches.push(format!(
                    "{case}: progress count skew (rust={} cpp={})",
                    got_events.len(),
                    exp_events.len()
                ));
            } else {
                for (i, ((rf, rs), (ef, es))) in
                    got_events.iter().zip(exp_events.iter()).enumerate()
                {
                    if rf.to_bits() != ef.to_bits() || rs != es {
                        mismatches.push(format!(
                            "{case}: progress[{i}] skew (rust=({rf},{rs}) cpp=({ef},{es}))"
                        ));
                        break;
                    }
                }
            }
        } else {
            if !single {
                saw_multi_robust_prog = true;
            }
            check_progress_robust(&case, &got_events, &mut mismatches);
            // Prefix/suffix still pin exactly (serial, deterministic).
            if got_events.len() < 4 || exp_events.len() < 4 {
                mismatches.push(format!(
                    "{case}: progress too short for prefix check (rust={} cpp={})",
                    got_events.len(),
                    exp_events.len()
                ));
            } else {
                for (i, ((rf, rs), (ef, es))) in got_events[..4]
                    .iter()
                    .zip(exp_events[..4].iter())
                    .enumerate()
                {
                    if rf.to_bits() != ef.to_bits() || rs != es {
                        mismatches.push(format!(
                            "{case}: progress prefix[{i}] skew (rust=({rf},{rs}) cpp=({ef},{es}))"
                        ));
                        break;
                    }
                }
            }
            if exp_events.len() >= 2 && got_events.len() >= 2 {
                for (i, ((rf, rs), (ef, es))) in got_events[got_events.len() - 2..]
                    .iter()
                    .zip(exp_events[exp_events.len() - 2..].iter())
                    .enumerate()
                {
                    if rf.to_bits() != ef.to_bits() || rs != es {
                        mismatches.push(format!(
                            "{case}: progress suffix[{i}] skew (rust=({rf},{rs}) cpp=({ef},{es}))"
                        ));
                        break;
                    }
                }
            } else {
                mismatches.push(format!(
                    "{case}: progress too short for suffix check (rust={} cpp={})",
                    got_events.len(),
                    exp_events.len()
                ));
            }
        }

        let got_rv = remesher.remeshed_vertices();
        let got_rq = remesher.remeshed_quads();
        let got_ruv = remesher.remeshed_vertex_uvs();
        // Real-output structural facts: asserted on CASE + ECX, folded
        // into the agreement report on EPX (C++ moves these itself).
        if got_rv.len() != exp_rv.len() {
            if strict {
                mismatches.push(format!(
                    "{case}: RV count skew (rust={} cpp={})",
                    got_rv.len(),
                    exp_rv.len()
                ));
            } else {
                case_agrees = false;
            }
        }
        // Optional order-free fallback (QPX-class, quadextractor precedent:
        // compaction/discovery order legitimately differs where the C++
        // iterates hash maps). Filled only when positional RQ fails on a
        // strict case but the remapped face sets agree with all values
        // within tolerance; the RV/RUV value checks below then follow
        // the remap instead of positions.
        let mut remap: Option<(Vec<usize>, f64)> = None;
        if got_rq.len() != exp_rq.len() {
            if strict {
                mismatches.push(format!(
                    "{case}: RQ count skew (rust={} cpp={})",
                    got_rq.len(),
                    exp_rq.len()
                ));
            } else {
                case_agrees = false;
            }
        } else {
            let mut first_skew: Option<(usize, &Vec<usize>, &Vec<usize>)> = None;
            for (i, (got, exp)) in got_rq.iter().zip(exp_rq.iter()).enumerate() {
                if got != exp {
                    first_skew = Some((i, got, exp));
                    break;
                }
            }
            match first_skew {
                None => {}
                Some((i, got, exp)) if !strict => {
                    let _ = (i, got, exp);
                    case_agrees = false;
                }
                Some((i, got, exp)) => {
                    remap = try_remap_faces(got_rv, &exp_rv, got_rq, &exp_rq);
                    match &remap {
                        Some((_, max_pos)) => {
                            order_only_notes += 1;
                            eprintln!(
                                "{case}: NOTE order-only remap accepted (face sets equal, max vertex diff {max_pos:.2e})"
                            );
                        }
                        None => {
                            mismatches
                                .push(format!("{case}: RQ[{i}] skew (rust={got:?} cpp={exp:?})"));
                        }
                    }
                }
            }
        }
        if got_ruv.len() != exp_ruv.len() {
            if strict {
                mismatches.push(format!(
                    "{case}: RUV count skew (rust={} cpp={})",
                    got_ruv.len(),
                    exp_ruv.len()
                ));
            } else {
                case_agrees = false;
            }
        }
        // The --uvs contract: one UV per vertex when on, none when off.
        if want_uvs && got_ruv.len() != got_rv.len() {
            mismatches.push(format!(
                "{case}: RUV len {} != RV len {} with uvs on",
                got_ruv.len(),
                got_rv.len()
            ));
        }
        if !want_uvs && !got_ruv.is_empty() {
            mismatches.push(format!("{case}: RUV nonempty with uvs off"));
        }
        let got_isl = remesher.island_output_quad_counts();
        if got_isl.len() != exp_isl.len() {
            mismatches.push(format!(
                "{case}: ISL length skew (rust={} cpp={})",
                got_isl.len(),
                exp_isl.len()
            ));
        } else if got_isl != exp_isl.as_slice() {
            if strict {
                mismatches.push(format!(
                    "{case}: ISL skew (rust={got_isl:?} cpp={exp_isl:?})"
                ));
            } else {
                case_agrees = false;
            }
        }
        let isl_sum: usize = got_isl.iter().sum();
        if isl_sum != got_rq.len() {
            mismatches.push(format!(
                "{case}: ISL sum {isl_sum} != RQ len {}",
                got_rq.len()
            ));
        }
        for (i, row) in got_rq.iter().enumerate() {
            if row.iter().any(|&v| v >= got_rv.len()) {
                mismatches.push(format!("{case}: RQ[{i}] indexes past RV end"));
                break;
            }
        }
        if remesher.decimated() != exp_dec {
            mismatches.push(format!(
                "{case}: DEC flag skew (rust={} cpp={exp_dec})",
                remesher.decimated()
            ));
        }
        let got_dv = remesher.decimated_vertices();
        let got_dt = remesher.decimated_triangles();
        if got_dv.len() != exp_dv.len() || got_dt.len() != exp_dt.len() {
            mismatches.push(format!(
                "{case}: DEC count skew (rust={}/{} cpp={}/{})",
                got_dv.len(),
                got_dt.len(),
                exp_dv.len(),
                exp_dt.len()
            ));
        }
        if remesher.decimated() != !got_dv.is_empty() {
            mismatches.push(format!("{case}: DEC flag/count disagreement"));
        }
        if exp_dec {
            saw_decimated = true;
            // Decimated verts are input-vertex copies through the shared
            // FFI decimation: bitwise in both sections.
            for (i, (got, exp)) in got_dv.iter().zip(exp_dv.iter()).enumerate() {
                if got.x().to_bits() != exp.x().to_bits()
                    || got.y().to_bits() != exp.y().to_bits()
                    || got.z().to_bits() != exp.z().to_bits()
                {
                    mismatches.push(format!("{case}: DV[{i}] bitwise skew"));
                    break;
                }
            }
            if got_dt != exp_dt.as_slice() {
                mismatches.push(format!("{case}: DT skew"));
            }
        }
        let got_iv = remesher.isotropic_vertices();
        let got_it = remesher.isotropic_triangles();
        if got_iv.len() != exp_iv.len() || got_it.len() != exp_it.len() {
            mismatches.push(format!(
                "{case}: ISO count skew (rust={}/{} cpp={}/{})",
                got_iv.len(),
                got_it.len(),
                exp_iv.len(),
                exp_it.len()
            ));
        } else if got_it != exp_it.as_slice() {
            mismatches.push(format!("{case}: ISO triangle skew"));
        }
        let got_iuv = remesher.isotropic_triangle_uvs();
        let got_iouv = remesher.isotropic_original_triangle_uvs();
        if got_iuv.len() != exp_iuv.len() || got_iouv.len() != exp_iouv.len() {
            mismatches.push(format!(
                "{case}: IUV count skew (rust={}/{} cpp={}/{})",
                got_iuv.len(),
                got_iouv.len(),
                exp_iuv.len(),
                exp_iouv.len()
            ));
        }
        let got_sing = remesher.isotropic_singular_vertices();
        // Singular counts ride the noisy cover (case 281: C++ reports 1
        // vs 3 across its own runs), so EPX folds them into the
        // agreement report like the other cover-derived quantities.
        if got_sing.len() != exp_sing.len() {
            if strict {
                mismatches.push(format!(
                    "{case}: SING count skew (rust={} cpp={})",
                    got_sing.len(),
                    exp_sing.len()
                ));
            } else {
                case_agrees = false;
            }
        }
        let got_conn = remesher.isotropic_extracted_connections();
        let got_moved = remesher.isotropic_extracted_connection_moved();
        // Connection capture: strict on CASE only; ECX + EPX report (the
        // C++ flips these itself on the listed ids).
        let mut conn_agrees = true;
        if got_conn.len() != exp_conn.len() || got_moved.len() != exp_moved.len() {
            if conn_strict {
                mismatches.push(format!(
                    "{case}: CONN count skew (rust={}/{} cpp={}/{})",
                    got_conn.len(),
                    got_moved.len(),
                    exp_conn.len(),
                    exp_moved.len()
                ));
            } else {
                conn_agrees = false;
            }
        } else {
            for (i, (&got, &exp)) in got_moved.iter().zip(exp_moved.iter()).enumerate() {
                if got as usize != exp {
                    if conn_strict {
                        mismatches.push(format!("{case}: MOVED[{i}] skew"));
                    } else {
                        conn_agrees = false;
                    }
                    break;
                }
            }
        }
        if remesher.symmetry_plane_axis() as i64 != exp_symaxis {
            mismatches.push(format!(
                "{case}: SYM axis skew (rust={} cpp={exp_symaxis})",
                remesher.symmetry_plane_axis()
            ));
        }
        if remesher.symmetry_plane_axis() >= 0 {
            saw_sym_active = true;
        }
        // Phase structure: names + order + counts (timings stripped).
        let got_phase: Vec<String> = remesher
            .phase_report()
            .iter()
            .map(|l| phase_token(l))
            .collect();
        let has_leaf = got_phase.iter().any(|l| l.starts_with("____"));
        if quiet && has_leaf {
            mismatches.push(format!("{case}: quiet case has leaf-stage lines"));
        }
        if quiet {
            saw_quiet_no_leaf = true;
        } else {
            saw_noisy_leaf = has_leaf || saw_noisy_leaf;
        }
        if strict && single {
            // Stage order pins exactly where deterministic.
            if got_phase != exp_phase {
                mismatches.push(format!(
                    "{case}: PHASE skew\n  rust={got_phase:?}\n  cpp ={exp_phase:?}"
                ));
            }
        } else {
            // Fixed head (9) + tail (6) exact; stage lines as a multiset
            // (multi-island tied orders and EPX branch choices vary).
            let head = 9usize.min(got_phase.len()).min(exp_phase.len());
            if got_phase[..head] != exp_phase[..head] {
                mismatches.push(format!("{case}: phase head skew"));
            }
            let tail = 6usize.min(got_phase.len()).min(exp_phase.len());
            if got_phase[got_phase.len() - tail..] != exp_phase[exp_phase.len() - tail..] {
                mismatches.push(format!("{case}: phase tail skew"));
            }
            let mut got_mid = got_phase[head..got_phase.len() - tail].to_vec();
            let mut exp_mid = exp_phase[head..exp_phase.len() - tail].to_vec();
            got_mid.sort();
            exp_mid.sort();
            if got_mid != exp_mid {
                mismatches.push(format!("{case}: phase stage-set skew"));
            }
        }

        // Values.
        {
            let mut vals = ValState {
                strict,
                max_diff: &mut max_diff,
                max_diff_at: &mut max_diff_at,
                mismatches: &mut mismatches,
                stats: &mut stats,
                case_agrees: &mut case_agrees,
            };
            // With an accepted remap, values follow Rust->C++ vertex
            // indices instead of positions (same tolerance).
            if let Some((map, _)) = &remap {
                for (s, &t) in map.iter().enumerate() {
                    let (got, exp) = (&got_rv[s], &exp_rv[t]);
                    vals.check(&case, &format!("rv[{s}~{t}].x"), got.x(), exp.x());
                    vals.check(&case, &format!("rv[{s}~{t}].y"), got.y(), exp.y());
                    vals.check(&case, &format!("rv[{s}~{t}].z"), got.z(), exp.z());
                }
                if got_ruv.len() == got_rv.len() && exp_ruv.len() == exp_rv.len() {
                    for (s, &t) in map.iter().enumerate() {
                        let (got, exp) = (&got_ruv[s], &exp_ruv[t]);
                        vals.check(&case, &format!("ruv[{s}~{t}].x"), got.x(), exp.x());
                        vals.check(&case, &format!("ruv[{s}~{t}].y"), got.y(), exp.y());
                    }
                } else {
                    for (i, (got, exp)) in got_ruv.iter().zip(exp_ruv.iter()).enumerate() {
                        vals.check(&case, &format!("ruv[{i}].x"), got.x(), exp.x());
                        vals.check(&case, &format!("ruv[{i}].y"), got.y(), exp.y());
                    }
                }
            } else {
                for (i, (got, exp)) in got_rv.iter().zip(exp_rv.iter()).enumerate() {
                    vals.check(&case, &format!("rv[{i}].x"), got.x(), exp.x());
                    vals.check(&case, &format!("rv[{i}].y"), got.y(), exp.y());
                    vals.check(&case, &format!("rv[{i}].z"), got.z(), exp.z());
                }
                for (i, (got, exp)) in got_ruv.iter().zip(exp_ruv.iter()).enumerate() {
                    vals.check(&case, &format!("ruv[{i}].x"), got.x(), exp.x());
                    vals.check(&case, &format!("ruv[{i}].y"), got.y(), exp.y());
                }
            }
            for (i, (got, exp)) in got_iv.iter().zip(exp_iv.iter()).enumerate() {
                vals.check(&case, &format!("iso[{i}].x"), got.x(), exp.x());
                vals.check(&case, &format!("iso[{i}].y"), got.y(), exp.y());
                vals.check(&case, &format!("iso[{i}].z"), got.z(), exp.z());
            }
            for (i, row) in got_iuv.iter().zip(exp_iuv.iter()).enumerate() {
                if row.0.len() != 3 {
                    vals.mismatches
                        .push(format!("{case}: IUV[{i}] row len {} != 3", row.0.len()));
                    continue;
                }
                for (l, (g, e)) in row
                    .0
                    .iter()
                    .zip([row.1.0, row.1.1, row.1.2].iter())
                    .enumerate()
                {
                    vals.check(&case, &format!("iuv[{i}][{l}].x"), g.x(), e.x());
                    vals.check(&case, &format!("iuv[{i}][{l}].y"), g.y(), e.y());
                }
            }
            for (i, row) in got_iouv.iter().zip(exp_iouv.iter()).enumerate() {
                if row.0.len() != 3 {
                    vals.mismatches
                        .push(format!("{case}: IOUV[{i}] row len {} != 3", row.0.len()));
                    continue;
                }
                for (l, (g, e)) in row
                    .0
                    .iter()
                    .zip([row.1.0, row.1.1, row.1.2].iter())
                    .enumerate()
                {
                    vals.check(&case, &format!("iouv[{i}][{l}].x"), g.x(), e.x());
                    vals.check(&case, &format!("iouv[{i}][{l}].y"), g.y(), e.y());
                }
            }
            for (i, (got, exp)) in got_sing.iter().zip(exp_sing.iter()).enumerate() {
                vals.check(&case, &format!("sing[{i}].x"), got.x(), exp.x());
                vals.check(&case, &format!("sing[{i}].y"), got.y(), exp.y());
                vals.check(&case, &format!("sing[{i}].z"), got.z(), exp.z());
            }
            vals.check(
                &case,
                "symoff",
                remesher.symmetry_plane_offset(),
                exp_symoff,
            );
            vals.check(
                &case,
                "symscore",
                remesher.symmetry_plane_score(),
                exp_symscore,
            );
        }
        // Connection values under their own strictness (CASE only).
        {
            let mut conn_values_agree = true;
            {
                let mut cvals = ValState {
                    strict: conn_strict,
                    max_diff: &mut max_diff,
                    max_diff_at: &mut max_diff_at,
                    mismatches: &mut mismatches,
                    stats: &mut stats,
                    case_agrees: &mut conn_values_agree,
                };
                for (i, (got, exp)) in got_conn.iter().zip(exp_conn.iter()).enumerate() {
                    cvals.check(&case, &format!("conn[{i}].ax"), got.0.x(), exp.0.x());
                    cvals.check(&case, &format!("conn[{i}].ay"), got.0.y(), exp.0.y());
                    cvals.check(&case, &format!("conn[{i}].az"), got.0.z(), exp.0.z());
                    cvals.check(&case, &format!("conn[{i}].bx"), got.1.x(), exp.1.x());
                    cvals.check(&case, &format!("conn[{i}].by"), got.1.y(), exp.1.y());
                    cvals.check(&case, &format!("conn[{i}].bz"), got.1.z(), exp.1.z());
                }
            }
            conn_agrees &= conn_values_agree;
        }
        match mode {
            Mode::Robust => {
                stats.both_ok += 1;
                if case_agrees && conn_agrees {
                    stats.value_agree += 1;
                }
            }
            Mode::ConnOnly => {
                if conn_agrees {
                    ecx_conn_agree += 1;
                }
            }
            Mode::Strict => {}
        }
    }
    assert!(saw_ok_true, "no ok=true case ran");
    assert!(saw_ok_false, "no ok=false case ran");
    assert!(saw_single_exact_prog, "no single-island exact progress ran");
    assert!(saw_multi_robust_prog, "no multi-island robust progress ran");
    assert!(saw_quiet_no_leaf, "no quiet case ran");
    assert!(saw_noisy_leaf, "no leaf-stage lines observed");
    assert!(saw_decimated, "no decimation RAN case ran");
    assert!(saw_sym_active, "no symmetry-active case ran");
    assert!(saw_multi_island, "no multi-island case ran");
    eprintln!("strict cases: {strict_cases}, max rel diff: {max_diff:.3e} at {max_diff_at}");
    eprintln!("order-only remaps accepted: {order_only_notes}");
    eprintln!("ecx cases: {ecx_cases}, conn-agree: {ecx_conn_agree}");
    eprintln!(
        "epx cases: {}, both-ok: {}, value-agree: {}, max diff: {:.3e} at {}",
        stats.cases, stats.both_ok, stats.value_agree, stats.max_diff, stats.max_diff_at
    );
    assert!(
        mismatches.is_empty(),
        "{} structural/value mismatches:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Skips one case's output sections (ok-skew path: keeps the tokenizer in
/// sync without comparing).
fn consume_outputs(c: &mut Cur) {
    c.expect("RV");
    let n = c.uint();
    for _ in 0..n * 3 {
        c.num();
    }
    c.expect("RQ");
    let n = c.uint();
    for _ in 0..n {
        let k = c.uint();
        for _ in 0..k {
            c.uint();
        }
    }
    c.expect("RUV");
    let n = c.uint();
    for _ in 0..n * 2 {
        c.num();
    }
    c.expect("ISL");
    let n = c.uint();
    for _ in 0..n {
        c.uint();
    }
    c.expect("DEC");
    c.int();
    let nv = c.uint();
    let nt = c.uint();
    for _ in 0..nv * 3 {
        c.num();
    }
    for _ in 0..nt {
        let tk = c.word();
        let k: usize = tk[1..].parse().expect("bad tri len");
        for _ in 0..k {
            c.uint();
        }
    }
    c.expect("ISO");
    let nv = c.uint();
    let nt = c.uint();
    for _ in 0..nv * 3 {
        c.num();
    }
    for _ in 0..nt {
        let tk = c.word();
        let k: usize = tk[1..].parse().expect("bad tri len");
        for _ in 0..k {
            c.uint();
        }
    }
    c.expect("IUV");
    let n = c.uint();
    for _ in 0..n * 6 {
        c.num();
    }
    c.expect("IOUV");
    let n = c.uint();
    for _ in 0..n * 6 {
        c.num();
    }
    c.expect("SING");
    let n = c.uint();
    for _ in 0..n * 3 {
        c.num();
    }
    c.expect("CONN");
    let nc = c.uint();
    let nm = c.uint();
    for _ in 0..nc * 6 {
        c.num();
    }
    for _ in 0..nm {
        c.uint();
    }
    c.expect("SYM");
    c.int();
    c.num();
    c.num();
    c.expect("PHASE");
    let n = c.uint();
    for _ in 0..n {
        c.word();
    }
}

/// Order-free face comparison (QPX-class): builds a Rust->C++ vertex
/// bijection by position (same 1e-6 scale-aware tolerance as values),
/// remaps the Rust faces, canonicalizes winding (rotation + reversal),
/// and accepts when the face multisets agree. Returns the map and the
/// worst matched-vertex distance. Greedy matching can miss a valid
/// bijection on near-duplicate positions; then it returns `None` and
/// the positional mismatch stands (conservative either way).
fn try_remap_faces(
    got_rv: &[Vector3],
    exp_rv: &[Vector3],
    got_rq: &[Vec<usize>],
    exp_rq: &[Vec<usize>],
) -> Option<(Vec<usize>, f64)> {
    if got_rv.len() != exp_rv.len() || got_rv.is_empty() {
        return None;
    }
    let mut used = vec![false; exp_rv.len()];
    let mut map = vec![usize::MAX; got_rv.len()];
    let mut worst = 0.0f64;
    for (s, g) in got_rv.iter().enumerate() {
        let mut best: Option<(usize, f64)> = None;
        for (t, e) in exp_rv.iter().enumerate() {
            if used[t] {
                continue;
            }
            let scale = e.x().abs().max(e.y().abs()).max(e.z().abs()).max(1.0);
            let d = (g.x() - e.x())
                .abs()
                .max((g.y() - e.y()).abs())
                .max((g.z() - e.z()).abs());
            if d <= TOL * scale && best.is_none_or(|(_, bd)| d < bd) {
                best = Some((t, d));
            }
        }
        let (t, d) = best?;
        used[t] = true;
        map[s] = t;
        worst = worst.max(d);
    }
    fn canon(row: &[usize]) -> Vec<usize> {
        let n = row.len();
        let mut best: Option<Vec<usize>> = None;
        for rev in [false, true] {
            for start in 0..n {
                let cand: Vec<usize> = (0..n)
                    .map(|k| {
                        let k = (start + k) % n;
                        if rev { row[n - 1 - k] } else { row[k] }
                    })
                    .collect();
                if best.as_ref().is_none_or(|b| cand < *b) {
                    best = Some(cand);
                }
            }
        }
        best.unwrap_or_default()
    }
    let mut rmapped: Vec<Vec<usize>> = got_rq
        .iter()
        .map(|row| canon(&row.iter().map(|&v| map[v]).collect::<Vec<_>>()))
        .collect();
    let mut expected: Vec<Vec<usize>> = exp_rq.iter().map(|row| canon(row)).collect();
    rmapped.sort();
    expected.sort();
    if rmapped == expected {
        Some((map, worst))
    } else {
        None
    }
}

/// Robust progress facts for multi-island (and EPX) cases: the serial
/// prefix/suffix are pinned by the caller; here the middle must be
/// monotonic, in range, and named.
fn check_progress_robust(case: &str, events: &[(f32, String)], mismatches: &mut Vec<String>) {
    if events.len() < 6 {
        mismatches.push(format!(
            "{case}: progress too short ({}) for an ok case",
            events.len()
        ));
        return;
    }
    // Empty statuses are legitimate on multi-island runs (both sides emit
    // "" when the slowest island has not reported a step yet — C++
    // updateProgress passes `name ? name : ""`), so only the pinned
    // prefix/suffix/exact sequences constrain status text.
    let mut prev = 0.0f32;
    for (i, (f, _)) in events.iter().enumerate() {
        if *f < prev {
            mismatches.push(format!(
                "{case}: progress[{i}] went backwards ({prev} -> {f})"
            ));
            break;
        }
        prev = *f;
        if !(*f >= 0.0 && *f <= 1.0) {
            mismatches.push(format!("{case}: progress[{i}] out of range ({f})"));
            break;
        }
    }
    for (i, (f, _)) in events.iter().enumerate().skip(4).take(events.len() - 6) {
        if !(*f >= 0.03 && *f <= 0.95) {
            mismatches.push(format!("{case}: middle progress[{i}] out of range ({f})"));
            break;
        }
    }
}

/// Mirrors the dump tool's `phaseToken`: strip the timing suffix, map
/// spaces to '_'.
fn phase_token(line: &str) -> String {
    let mut work = line.to_string();
    if let Some(stripped) = work.strip_suffix(" ms") {
        let bytes = stripped.as_bytes();
        let mut begin = bytes.len();
        while begin > 0 && (bytes[begin - 1].is_ascii_digit() || bytes[begin - 1] == b'.') {
            begin -= 1;
        }
        work = format!("{}T", &stripped[..begin]);
    }
    const CORES: &str = "Cores kept busy across the parallel phase: ";
    if let Some(rest) = work.strip_prefix(CORES) {
        let mut end = 0;
        for b in rest.as_bytes() {
            if b.is_ascii_digit() || *b == b'.' {
                end += 1;
            } else {
                break;
            }
        }
        work = format!("{CORES}T{}", &rest[end..]);
    }
    work.replace(' ', "_")
}
