// Differential oracle replay for the density port: parses
// tests/fixtures/density_diff.txt (generated by the C++ density_diff_dump
// tool) and replays every case. Doubles compare BITWISE (%.17g round-trips
// exactly; the port uses the FMA-exact vector3 port, so every op must be
// bit-identical). NaNs compare by sign bit only: payloads are never
// consumed, but a dropped/toggled sign is a real bug.
use retopo_core::density::Density;
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/density_diff.txt");

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad usize")
    }
    fn v3(&mut self) -> Vector3 {
        Vector3::new(self.num(), self.num(), self.num())
    }
    fn vec_f64(&mut self, n: usize) -> Vec<f64> {
        (0..n).map(|_| self.num()).collect()
    }
}

fn check_bits(case: &str, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    let same = if got.is_nan() && expect.is_nan() {
        got.is_sign_negative() == expect.is_sign_negative()
    } else {
        got.to_bits() == expect.to_bits()
    };
    assert!(
        same,
        "{case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

fn check_vec(case: &str, what: &str, got: &[f64], c: &mut Cur, compared: &mut usize) {
    c.expect("r");
    let n = c.uint();
    assert_eq!(
        got.len(),
        n,
        "{case} {what}: len rust={} cpp={n}",
        got.len()
    );
    for (i, &v) in got.iter().enumerate() {
        check_bits(case, &format!("{what}[{i}]"), v, c, compared);
    }
}

#[test]
fn density_differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("DDIFF1");
    let mut compared = 0usize;
    let (mut nn, mut ne, mut nr, mut na) = (0, 0, 0, 0);
    loop {
        if c.pos >= c.toks.len() {
            break;
        }
        let tag = c.word();
        match tag.as_str() {
            "N" => {
                nn += 1;
                let case = format!("N case {nn}");
                let len = c.uint();
                let field = c.vec_f64(len);
                let got = Density::normalize_field(&field);
                check_vec(&case, "normalize", &got, &mut c, &mut compared);
            }
            "E" => {
                ne += 1;
                let case = format!("E case {ne}");
                let v = c.num();
                let got = Density::edge_scale_for(v);
                c.expect("r");
                check_bits(&case, "edge", got, &mut c, &mut compared);
            }
            "R" => {
                nr += 1;
                let case = format!("R case {nr}");
                let (nsrc, nfield, ndst) = (c.uint(), c.uint(), c.uint());
                let src: Vec<Vector3> = (0..nsrc).map(|_| c.v3()).collect();
                let field = c.vec_f64(nfield);
                let dst: Vec<Vector3> = (0..ndst).map(|_| c.v3()).collect();
                let got = Density::resample_nearest(&src, &field, &dst);
                check_vec(&case, "resample", &got, &mut c, &mut compared);
            }
            "A" => {
                na += 1;
                let case = format!("A case {na}");
                let (nv, nt, ndens, nscal) = (c.uint(), c.uint(), c.uint(), c.uint());
                let verts: Vec<Vector3> = (0..nv).map(|_| c.v3()).collect();
                let mut tris = Vec::with_capacity(nt);
                for _ in 0..nt {
                    c.expect("t");
                    let len = c.uint();
                    tris.push((0..len).map(|_| c.uint()).collect::<Vec<_>>());
                }
                let dens = c.vec_f64(ndens);
                let mut scal = c.vec_f64(nscal);
                Density::apply_to_scaling_field(&verts, &tris, &dens, &mut scal);
                check_vec(&case, "scaling", &scal, &mut c, &mut compared);
            }
            "T" => {
                // Timing lines are informational; the timing test compares
                // the sink. Format: `T dens ms=%.3f sink=%.17g`.
                assert_eq!(c.word(), "dens");
                c.word();
                c.word();
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    // 60+40+80+60 seeded plus the adversarial blocks in the dump tool.
    assert_eq!(nn, 67, "expected 67 N cases");
    assert_eq!(ne, 58, "expected 58 E cases");
    assert_eq!(nr, 94, "expected 94 R cases");
    assert_eq!(na, 74, "expected 74 A cases");
    eprintln!(
        "density replay: {nn} N + {ne} E + {nr} R + {na} A, {compared} doubles bitwise-equal"
    );
}
