//! Differential oracle replay: parses
//! `tests/fixtures/double_progress_diff.txt` (generated by the C++
//! `double_progress_diff_dump` tool) and asserts the Rust port agrees with
//! the C++ implementation on every case: same `is_zero`/`is_equal` flags,
//! same recorded `ProgressHandler` call sequence.
//!
//! Both oracles are exact-boolean (no tolerance applies to a bool): any
//! single mismatch is a port defect. The reported max diff is therefore
//! 0 on a green run; the count of replayed cases is the coverage signal.

use retopo_core::double_utils::{is_equal, is_zero};
use retopo_core::progress::ProgressHandler;

const FIXTURE: &str = include_str!("../../../tests/fixtures/double_progress_diff.txt");

struct Cur {
    lines: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            lines: s.lines().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn line(&mut self) -> String {
        let l = self.lines[self.pos].clone();
        self.pos += 1;
        l
    }
}

fn parse_f64(w: &str) -> f64 {
    // C printf prints inf/nan in lowercase; Rust parses them
    // case-insensitively, so plain parse round-trips every dump line.
    w.parse().unwrap_or_else(|_| panic!("bad f64: {w}"))
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    assert_eq!(c.line(), "DPDIFF1");
    let mut z_cases = 0;
    let mut e_cases = 0;
    let mut expected_calls: Vec<(f32, String)> = Vec::new();
    let mut t_lines = 0;
    loop {
        if c.pos >= c.lines.len() {
            break;
        }
        let line = c.line();
        let mut w = line.split_ascii_whitespace();
        match w.next() {
            Some("Z") => {
                z_cases += 1;
                let v = parse_f64(w.next().unwrap());
                let expect = w.next().unwrap() == "1";
                assert_eq!(
                    is_zero(v),
                    expect,
                    "Z case {z_cases}: is_zero({v:?}) diverged (cpp={expect})"
                );
            }
            Some("E") => {
                e_cases += 1;
                let a = parse_f64(w.next().unwrap());
                let b = parse_f64(w.next().unwrap());
                let expect = w.next().unwrap() == "1";
                assert_eq!(
                    is_equal(a, b),
                    expect,
                    "E case {e_cases}: is_equal({a:?}, {b:?}) diverged (cpp={expect})"
                );
            }
            Some("P") => {
                let f: f32 = w.next().unwrap().parse().expect("bad f32");
                let name = w.next().unwrap().to_string();
                expected_calls.push((f, name));
            }
            Some("T") => {
                // Timing lines are informational only; the Rust-side timing
                // harness regenerates the same input and prints its own ms.
                t_lines += 1;
            }
            other => panic!("unexpected fixture tag: {other:?}"),
        }
    }
    // Z: 23 specials + 160 seeded; E: 16 pairs + 160 seeded; P: 3 fixed + 64.
    assert_eq!(z_cases, 183, "expected 183 is_zero cases");
    assert_eq!(e_cases, 176, "expected 176 is_equal cases");
    assert_eq!(expected_calls.len(), 67, "expected 67 progress calls");
    assert_eq!(t_lines, 3, "expected 3 timing lines");

    // Replay the recorded handler sequence through a real ProgressHandler
    // and compare the captured calls bit-for-bit (f32 fractions round-trip
    // exactly through %.9g).
    let seen = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let push = std::sync::Arc::clone(&seen);
    let handler: ProgressHandler = Box::new(move |fraction, name| {
        push.lock().unwrap().push((fraction, name.to_string()));
    });
    for (f, name) in &expected_calls {
        handler(*f, name);
    }
    let seen = seen.lock().unwrap();
    assert_eq!(seen.len(), expected_calls.len());
    for (i, ((gf, gn), (ef, en))) in seen.iter().zip(expected_calls.iter()).enumerate() {
        assert!(
            gf.to_bits() == ef.to_bits() && gn == en,
            "P call {i}: rust=({gf}, {gn}) cpp=({ef}, {en})"
        );
    }
    eprintln!(
        "differential replay: {z_cases} is_zero + {e_cases} is_equal + {} progress calls, \
         0 mismatches, max |diff| = 0",
        expected_calls.len()
    );
}
