// Harness indexes parallel arrays/cursors in lockstep; index loops stay.
#![allow(clippy::needless_range_loop)]

// Differential oracle replay: parses tests/fixtures/framefield_diff.txt
// (generated by the C++ framefield_diff_dump tool), re-runs every case with
// the Rust port, and asserts the port matches the C++ implementation.
//
// Two sections, mirroring the solvers' CLS/CLSX split:
// - CASE (strict): same ok flag, same face count, field values within
//   scale-aware 1e-6, every output a unit vector (structural invariant).
// - FFX (robustness-only): near-degenerate curvature inputs where the
//   principal direction is backend-noise-defined (Eigen tridiagonal-QR vs
//   the port's Jacobi pick different noise axes). The port must match the
//   ok flag and the face count and solve everything C++ solves; value
//   agreement is reported, not asserted.
use retopo_core::frame_field::FrameField;
use retopo_core::surface_mesh::SurfaceMesh;
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/framefield_diff.txt");
const TOL: f64 = 1e-6;
// Must match kFfxMagnitude in tests/framefield_diff_dump.cpp: the replay
// asserts every tag is consistent with the printed magnitude, proving the
// CASE/FFX segregation is principled rather than cherry-picked.
const FFX_MAGNITUDE: f64 = 1e-6;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn int(&mut self) -> i64 {
        self.word().parse().expect("bad int")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn v3(&mut self) -> Vector3 {
        let x = self.num();
        let y = self.num();
        let z = self.num();
        Vector3::new(x, y, z)
    }
    fn lines(&mut self, tag: &str, n: usize) -> Vec<Vec<Vector3>> {
        let mut out = Vec::with_capacity(n);
        for _ in 0..n {
            self.expect(tag);
            let m = self.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(self.v3());
            }
            out.push(line);
        }
        out
    }
}

struct FfxStats {
    cases: usize,
    both_ok: usize,
    value_agree: usize,
    max_diff: f64,
    max_diff_at: String,
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("FFDIFF1");
    let mut strict_cases = 0usize;
    let mut strict_ok = 0usize;
    let mut stats = FfxStats {
        cases: 0,
        both_ok: 0,
        value_agree: 0,
        max_diff: 0.0,
        max_diff_at: String::new(),
    };
    let mut max_diff = 0.0f64;
    let mut max_diff_at = String::new();
    let mut mismatches: Vec<String> = Vec::new();
    let mut seen_56 = false;
    let mut seen_290 = false;
    loop {
        let tag = c.word();
        if tag == "CASES" {
            let total = c.uint();
            assert_eq!(
                total,
                strict_cases + stats.cases,
                "CASES trailer disagrees with parsed count"
            );
            break;
        }
        let strict = match tag.as_str() {
            "CASE" => true,
            "FFX" => false,
            other => panic!("unexpected fixture tag: {other}"),
        };
        let id = c.int();
        c.expect("KIND");
        let kind = c.word();
        c.expect("NV");
        let nv = c.uint();
        c.expect("NT");
        let nt = c.uint();
        c.expect("HARD");
        let hard = c.num();
        c.expect("GUIDES");
        let n_guides = c.uint();
        c.expect("SHARPS");
        let n_sharps = c.uint();
        let case = format!("{} {id} ({kind})", if strict { "case" } else { "ffx" });

        let mut vertices = Vec::with_capacity(nv);
        for _ in 0..nv {
            c.expect("V");
            vertices.push(c.v3());
        }
        let mut triangles = Vec::with_capacity(nt);
        for _ in 0..nt {
            c.expect("T");
            let k = c.uint();
            let mut tri = Vec::with_capacity(k);
            for _ in 0..k {
                tri.push(c.uint());
            }
            triangles.push(tri);
        }
        let guides = c.lines("GUIDE", n_guides);
        let sharps = c.lines("SHARP", n_sharps);
        c.expect("RES");
        let expected_ok = c.int() != 0;
        c.expect("MAG");
        let min_magnitude = c.num();
        // Tag rule (must match dumpCase): FFX iff a listed straggler with
        // matching identity, or the magnitude auto-rule fired. Asserted in
        // both directions, so a hand-edited fixture, a shifted ID, or a
        // drifted detector voids the oracle loudly instead of silently
        // weakening it.
        let listed_identity = match id {
            56 => {
                kind == "tetra"
                    && nv == 4
                    && nt == 4
                    && hard.to_bits() == 180.0f64.to_bits()
                    && n_guides == 0
                    && n_sharps == 0
            }
            290 => {
                kind == "tiny"
                    && nv == 4
                    && nt == 4
                    && hard.to_bits() == 90.0f64.to_bits()
                    && n_guides == 0
                    && n_sharps == 0
            }
            _ => false,
        };
        if (id == 56 || id == 290) && !listed_identity {
            mismatches.push(format!(
                "{case}: listed FFX identity drifted (kind={kind} nv={nv} nt={nt} hard={hard} ng={n_guides} ns={n_sharps})"
            ));
        }
        if id == 56 {
            seen_56 = true;
        }
        if id == 290 {
            seen_290 = true;
        }
        let expected_robust = listed_identity
            || (expected_ok && min_magnitude > 0.0 && min_magnitude < FFX_MAGNITUDE);
        if strict == expected_robust {
            mismatches.push(format!(
                "{case}: tag inconsistent (strict={strict} mag={min_magnitude:.3e} listed={listed_identity})"
            ));
        }

        let mesh = SurfaceMesh::new(&vertices, &triangles);
        let got = FrameField::create(&mesh, hard, &guides, &sharps);
        if strict {
            strict_cases += 1;
        } else {
            stats.cases += 1;
        }
        if got.is_some() != expected_ok {
            // Robustness rule (both sections): the port must solve
            // everything C++ solves; solving more is fine.
            if expected_ok || strict {
                mismatches.push(format!(
                    "{case}: ok flag diverged (rust={} cpp={expected_ok})",
                    got.is_some()
                ));
            }
            if expected_ok {
                consume_outputs(&mut c);
            }
            continue;
        }
        if !expected_ok {
            continue;
        }
        if strict {
            strict_ok += 1;
        } else {
            stats.both_ok += 1;
        }
        let field = got.unwrap();
        let mut case_agrees = true;

        c.expect("NF");
        let n_faces = c.uint();
        if field.len() != n_faces {
            mismatches.push(format!(
                "{case}: face count diverged (rust={} cpp={n_faces})",
                field.len()
            ));
            consume_outputs(&mut c);
            continue;
        }
        c.expect("FIELD");
        for f in 0..n_faces {
            let expect = c.v3();
            let got_v = field[f];
            // Structural invariant (both sections): outputs are unit
            // tangents, so a non-unit output is a logic bug, not noise.
            let len = got_v.length();
            if (len - 1.0).abs() > 1e-9 {
                mismatches.push(format!("{case}: field[{f}] not unit (len={len})"));
            }
            for (coord, (g, e)) in [
                (got_v.x(), expect.x()),
                (got_v.y(), expect.y()),
                (got_v.z(), expect.z()),
            ]
            .into_iter()
            .enumerate()
            {
                let d = (g - e).abs();
                let tol = TOL * e.abs().max(1.0);
                if strict {
                    if d > max_diff {
                        max_diff = d;
                        max_diff_at = format!("{case} field[{f}][{coord}] g={g:.6e} e={e:.6e}");
                    }
                    if d > tol {
                        mismatches.push(format!(
                            "{case}: field[{f}][{coord}] diverged (rust={g} cpp={e} diff={d:.3e} tol={tol:.3e})"
                        ));
                    }
                } else {
                    if d > stats.max_diff {
                        stats.max_diff = d;
                        stats.max_diff_at =
                            format!("{case} field[{f}][{coord}] g={g:.6e} e={e:.6e}");
                    }
                    if d > tol {
                        case_agrees = false;
                    }
                }
            }
        }
        if !strict && case_agrees {
            stats.value_agree += 1;
        }
    }
    // Timing lines are informational only; the timing harness regenerates
    // the same mesh and prints its own ms.
    let mut t_lines = 0;
    let mut t_faces = 0usize;
    let mut t_checksum = 0.0f64;
    while c.pos < c.toks.len() {
        c.expect("T");
        let kind = c.word();
        assert_eq!(kind, "ff", "bad T line");
        let ok_tok = c.word();
        assert_eq!(ok_tok, "ok=1", "timing case must solve on the C++ side");
        c.word(); // ms=...
        let faces_tok = c.word();
        t_faces = faces_tok
            .strip_prefix("faces=")
            .expect("bad faces token")
            .parse()
            .expect("bad faces");
        let checksum_tok = c.word();
        t_checksum = checksum_tok
            .strip_prefix("checksum=")
            .expect("bad checksum token")
            .parse()
            .expect("bad checksum");
        t_lines += 1;
    }
    eprintln!(
        "differential replay: {strict_cases} strict ({strict_ok} ok), max |field diff| = {max_diff:.3e} at {max_diff_at}"
    );
    eprintln!(
        "FFX (robustness-only): {} cases, {} both-ok, {} value-agree, max |diff| = {:.3e} at {}",
        stats.cases, stats.both_ok, stats.value_agree, stats.max_diff, stats.max_diff_at
    );
    eprintln!("timing mesh: {t_faces} faces, C++ checksum {t_checksum:.17e}");
    for m in mismatches.iter().take(20) {
        eprintln!("MISMATCH: {m}");
    }
    assert!(strict_cases >= 200, "expected 200+ strict cases");
    assert!(
        seen_56 && seen_290,
        "listed FFX cases missing from fixture (56: {seen_56}, 290: {seen_290})"
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        max_diff <= TOL,
        "strict max field diff {max_diff:.3e} exceeds {TOL}"
    );
    assert!(
        mismatches.is_empty(),
        "{} mismatches (first above)",
        mismatches.len()
    );
}

/// Skip expected outputs after an ok-flag divergence to keep the cursor in
/// sync (scans to the next case tag; all output payloads are numeric).
fn consume_outputs(c: &mut Cur) {
    let from = c.pos;
    while c.pos < c.toks.len()
        && c.toks[c.pos] != "CASE"
        && c.toks[c.pos] != "FFX"
        && c.toks[c.pos] != "CASES"
    {
        c.pos += 1;
    }
    eprintln!(
        "ok diverged, skipping {} tokens to stay in sync",
        c.pos - from
    );
}
