//! Differential oracle replay: parses `tests/fixtures/glb_diff.txt`
//! (generated by the C++ `glb_diff_dump` tool), replays every case through
//! the Rust port, and asserts the port matches the C++ implementation:
//! same ok flags, same positions (f32 bits on exact cases, 1e-5
//! scale-aware on INEXACT-transform cases where C++ -O3 fuses
//! multiply-adds), same triangles, same warn/err strings (temp paths
//! normalized to `@F@`), same extension predicates, and byte-identical
//! writer output. Writer cases additionally round-trip: the C++ bytes load
//! through the Rust reader into the expected fan-triangulated mesh.

use retopo_core::glb::{
    has_glb_extension, is_supported_input_extension, load_glb_positions_and_triangles, save_glb,
    save_glb_with_uvs,
};
use retopo_core::vector2::Vector2;
use retopo_core::vector3::Vector3;
use std::sync::atomic::{AtomicUsize, Ordering};

const FIXTURE: &str = include_str!("../../../tests/fixtures/glb_diff.txt");

static TEMP_COUNTER: AtomicUsize = AtomicUsize::new(0);

fn unescape(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] != b'\\' {
            out.push(b[i]);
            i += 1;
            continue;
        }
        i += 1;
        match b[i] {
            b'\\' => out.push(b'\\'),
            b'r' => out.push(b'\r'),
            b'n' => out.push(b'\n'),
            b'0' => out.push(0),
            b'x' => {
                let hex = std::str::from_utf8(&b[i + 1..i + 3]).expect("bad hex");
                out.push(u8::from_str_radix(hex, 16).expect("bad hex"));
                i += 2;
            }
            e => panic!("bad escape: \\{}", e as char),
        }
        i += 1;
    }
    out
}

fn hex_decode(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd hex length");
    let mut out = Vec::with_capacity(s.len() / 2);
    for i in (0..s.len()).step_by(2) {
        out.push(u8::from_str_radix(&s[i..i + 2], 16).expect("bad hex"));
    }
    out
}

struct Cur<'a> {
    lines: Vec<&'a str>,
    pos: usize,
}

impl<'a> Cur<'a> {
    fn new(s: &'a str) -> Self {
        Self {
            lines: s.split('\n').collect(),
            pos: 0,
        }
    }
    fn line(&mut self) -> &'a str {
        let l = self.lines[self.pos];
        self.pos += 1;
        l
    }
    fn done(&self) -> bool {
        // Trailing newline yields one phantom empty line.
        self.pos >= self.lines.len()
            || (self.pos + 1 == self.lines.len() && self.lines[self.pos].is_empty())
    }
}

fn fields(line: &str) -> Vec<&str> {
    line.split_ascii_whitespace().collect()
}

fn kv<'a>(f: &[&'a str], key: &str) -> &'a str {
    let prefix = format!("{key}=");
    for tok in f {
        if let Some(v) = tok.strip_prefix(&prefix) {
            return v;
        }
    }
    panic!("missing {key} in {f:?}");
}

fn parse_pos(line: &str, tag: &str) -> Vec<u32> {
    let f = fields(line);
    assert_eq!(f[0], tag, "expected {tag} line, got {line:?}");
    f[1..]
        .iter()
        .map(|w| u32::from_str_radix(w, 16).expect("bad hex word"))
        .collect()
}

fn parse_tris(c: &mut Cur<'_>, n: usize, tag: &str) -> Vec<Vec<usize>> {
    let mut out = Vec::with_capacity(n);
    for _ in 0..n {
        let f = fields(c.line());
        assert_eq!(f[0], tag);
        let k: usize = f[1].parse().expect("bad k");
        assert_eq!(f.len(), 2 + k, "TRI arity");
        out.push(f[2..].iter().map(|w| w.parse().expect("bad idx")).collect());
    }
    out
}

fn sentinel_positions() -> Vec<f32> {
    vec![1.5, -2.5]
}

fn sentinel_triangles() -> Vec<Vec<usize>> {
    vec![vec![99], vec![7, 8]]
}

fn write_temp(bytes: &[u8], suffix: &str) -> std::path::PathBuf {
    let path = std::env::temp_dir().join(format!(
        "retopo_rs_glbdiff_{}_{}{}",
        std::process::id(),
        TEMP_COUNTER.fetch_add(1, Ordering::SeqCst),
        suffix
    ));
    std::fs::write(&path, bytes).expect("write temp glb");
    path
}

/// Check one loaded result against the fixture `R`/`POS`/`TRI`/`W`/`E`
/// block. `path_for_subst` is the filename the loader saw (its text is
/// normalized to `@F@` on both sides); when the normalized message mentions
/// `@F@`, the raw message must embed the real path.
#[allow(clippy::too_many_arguments)]
fn check_load(
    name: &str,
    c: &mut Cur<'_>,
    ok: bool,
    positions: &[f32],
    triangles: &[Vec<usize>],
    warn: &str,
    err: &str,
    path_for_subst: &str,
    inexact: bool,
    max_diff: &mut f32,
) {
    let fr = fields(c.line());
    assert_eq!(fr[0], "R");
    let e_ok = kv(&fr, "ok") == "1";
    let e_npos: usize = kv(&fr, "npos").parse().expect("bad npos");
    let e_ntri: usize = kv(&fr, "ntri").parse().expect("bad ntri");
    assert_eq!(ok, e_ok, "{name}: ok flag diverged");
    assert_eq!(positions.len(), e_npos, "{name}: npos diverged");
    assert_eq!(triangles.len(), e_ntri, "{name}: ntri diverged");
    let e_pos = parse_pos(c.line(), "POS");
    assert_eq!(e_pos.len(), e_npos, "{name}: POS arity");
    for (i, w) in e_pos.iter().enumerate() {
        let expected = f32::from_bits(*w);
        if inexact {
            let d = (positions[i] - expected).abs();
            assert!(
                d <= 1e-5 * (1.0f32.max(expected.abs())),
                "{name}: pos[{i}] approx diverged: got {} expected {expected} (d={d})",
                positions[i],
            );
            if !d.is_nan() {
                *max_diff = max_diff.max(d / 1.0f32.max(expected.abs()));
            }
        } else {
            assert_eq!(
                positions[i].to_bits(),
                *w,
                "{name}: pos[{i}] bits diverged (got {} expected {expected})",
                positions[i],
            );
        }
    }
    let e_tri = parse_tris(c, e_ntri, "TRI");
    assert_eq!(triangles, e_tri, "{name}: triangles diverged");
    let wline = c.line();
    let e_warn = unescape(wline.strip_prefix("W ").unwrap_or(""));
    let norm_warn = warn.replace(path_for_subst, "@F@");
    assert_eq!(
        norm_warn.as_bytes(),
        e_warn.as_slice(),
        "{name}: warn diverged"
    );
    if norm_warn.contains("@F@") {
        assert!(
            warn.contains(path_for_subst),
            "{name}: warn does not embed the path"
        );
    }
    let eline = c.line();
    let e_err = unescape(eline.strip_prefix("E ").unwrap_or(""));
    let norm_err = err.replace(path_for_subst, "@F@");
    assert_eq!(
        norm_err.as_bytes(),
        e_err.as_slice(),
        "{name}: err diverged"
    );
    if norm_err.contains("@F@") {
        assert!(
            err.contains(path_for_subst),
            "{name}: err does not embed the path"
        );
    }
}

fn fan_tris(faces: &[Vec<usize>]) -> Vec<Vec<usize>> {
    let mut tris = Vec::new();
    for face in faces {
        if face.len() < 3 {
            continue;
        }
        for i in 1..face.len() - 1 {
            tris.push(vec![face[0], face[i], face[i + 1]]);
        }
    }
    tris
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    assert_eq!(c.line(), "GLBDIFF1");
    let mut read_cases = 0usize;
    let mut inexact_cases = 0usize;
    let mut file_cases = 0usize;
    let mut ext_cases = 0usize;
    let mut write_cases = 0usize;
    let mut t_lines = 0usize;
    let mut max_rel_diff = 0.0f32;

    while !c.done() {
        let header = c.line();
        let f = fields(header);
        if f[0] == "READCASE" {
            read_cases += 1;
            let id: usize = f[1].parse().expect("bad id");
            let inexact = kv(&f, "INEXACT") == "1";
            if inexact {
                inexact_cases += 1;
            }
            let suffix = if kv(&f, "SUFFIX") == "GLB" {
                ".GLB"
            } else {
                ".glb"
            };
            let hexlen: usize = kv(&f, "HEXLEN").parse().expect("bad HEXLEN");
            let hexline = c.line();
            let hextext = hexline.strip_prefix("HEX").expect("bad HEX").trim();
            let bytes = hex_decode(hextext);
            assert_eq!(bytes.len(), hexlen, "READCASE {id}: HEXLEN");
            // R54 (missing file) carries no bytes and reuses the fixed
            // nonexistent path; everything else goes through a temp file.
            let (path, path_string) = if hexlen == 0 {
                let p = "/nonexistent-dir-rs-glb-9f3/missing.glb".to_string();
                (std::path::PathBuf::from(&p), p)
            } else {
                let p = write_temp(&bytes, suffix);
                let s = p.to_string_lossy().into_owned();
                (p, s)
            };
            let mut positions = sentinel_positions();
            let mut triangles = sentinel_triangles();
            let mut warn = String::from("W");
            let mut err = String::from("E");
            let ok = load_glb_positions_and_triangles(
                &path,
                &mut positions,
                &mut triangles,
                Some(&mut warn),
                Some(&mut err),
            );
            if hexlen != 0 {
                let _ = std::fs::remove_file(&path);
            }
            check_load(
                &format!("READCASE {id}"),
                &mut c,
                ok,
                &positions,
                &triangles,
                &warn,
                &err,
                &path_string,
                inexact,
                &mut max_rel_diff,
            );
        } else if f[0] == "FILE" {
            file_cases += 1;
            let name = f[1];
            assert_eq!(name, "tetra.glb");
            let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/tetra.glb");
            let path_string = path.to_string_lossy().into_owned();
            let mut positions = sentinel_positions();
            let mut triangles = sentinel_triangles();
            let mut warn = String::from("W");
            let mut err = String::from("E");
            let ok = load_glb_positions_and_triangles(
                &path,
                &mut positions,
                &mut triangles,
                Some(&mut warn),
                Some(&mut err),
            );
            check_load(
                "FILE tetra.glb",
                &mut c,
                ok,
                &positions,
                &triangles,
                &warn,
                &err,
                &path_string,
                false,
                &mut max_rel_diff,
            );
        } else if f[0] == "EXTCASE" {
            ext_cases += 1;
            let id: usize = f[1].parse().expect("bad id");
            let pline = c.line();
            let raw = unescape(pline.strip_prefix("P ").unwrap_or(""));
            let path = String::from_utf8(raw).expect("ext path utf8");
            let fr = fields(c.line());
            assert_eq!(fr[0], "R");
            let e_glb = kv(&fr, "glb") == "1";
            let e_sup = kv(&fr, "sup") == "1";
            assert_eq!(has_glb_extension(&path), e_glb, "EXTCASE {id}: glb");
            assert_eq!(
                is_supported_input_extension(&path),
                e_sup,
                "EXTCASE {id}: sup"
            );
        } else if f[0] == "WRITECASE" {
            write_cases += 1;
            let id: usize = f[1].parse().expect("bad id");
            let name = format!("WRITECASE {id} {}", kv(&f, "name"));
            let with_uvs = kv(&f, "uvs") == "1";
            let nverts: usize = kv(&f, "nverts").parse().expect("bad nverts");
            let nfaces: usize = kv(&f, "nfaces").parse().expect("bad nfaces");
            let badpath = kv(&f, "badpath") == "1";
            let genline = c.line();
            let gen_raw = unescape(genline.strip_prefix("GEN ").unwrap_or(""));
            let generator = String::from_utf8(gen_raw).expect("generator utf8");
            let mut verts = Vec::with_capacity(nverts);
            for _ in 0..nverts {
                let fv = fields(c.line());
                assert_eq!(fv[0], "VERT");
                let x = f64::from_bits(u64::from_str_radix(fv[1], 16).expect("bad vert"));
                let y = f64::from_bits(u64::from_str_radix(fv[2], 16).expect("bad vert"));
                let z = f64::from_bits(u64::from_str_radix(fv[3], 16).expect("bad vert"));
                verts.push(Vector3::new(x, y, z));
            }
            let mut faces: Vec<Vec<usize>> = Vec::with_capacity(nfaces);
            for _ in 0..nfaces {
                let ff = fields(c.line());
                assert_eq!(ff[0], "FACE");
                let k: usize = ff[1].parse().expect("bad k");
                assert_eq!(ff.len(), 2 + k, "FACE arity");
                faces.push(
                    ff[2..]
                        .iter()
                        .map(|w| w.parse().expect("bad idx"))
                        .collect(),
                );
            }
            let mut uvs = Vec::new();
            if with_uvs {
                // UV count is the writer's input length (may mismatch).
                // The dump prints one UV line per input uv; nverts lines
                // when matching, else the mismatched input length, which we
                // recover by peeking: UV lines precede ROUT.
                loop {
                    let peek = c.lines[c.pos];
                    if !peek.starts_with("UV ") {
                        break;
                    }
                    let fu = fields(c.line());
                    let x = f64::from_bits(u64::from_str_radix(fu[1], 16).expect("bad uv"));
                    let y = f64::from_bits(u64::from_str_radix(fu[2], 16).expect("bad uv"));
                    uvs.push(Vector2::new(x, y));
                }
            }
            let fr = fields(c.line());
            assert_eq!(fr[0], "ROUT");
            let e_ok = kv(&fr, "ok") == "1";
            let e_nbytes: usize = kv(&fr, "nbytes").parse().expect("bad nbytes");
            let byline = c.line();
            let e_bytes = hex_decode(byline.strip_prefix("BYTES").expect("bad BYTES").trim());
            assert_eq!(e_bytes.len(), e_nbytes, "{name}: nbytes");

            let (path, _cleanup) = if badpath {
                (
                    std::path::PathBuf::from("/nonexistent-dir-rs-glb-9f3/nope.glb"),
                    None,
                )
            } else {
                let p = std::env::temp_dir().join(format!(
                    "retopo_rs_glbwrite_{}_{}.glb",
                    std::process::id(),
                    TEMP_COUNTER.fetch_add(1, Ordering::SeqCst)
                ));
                (p.clone(), Some(p))
            };
            let ok = if with_uvs {
                save_glb_with_uvs(&path, &generator, &verts, &faces, &uvs)
            } else {
                save_glb(&path, &generator, &verts, &faces)
            };
            assert_eq!(ok, e_ok, "{name}: ok flag diverged");
            if e_ok {
                let got = std::fs::read(&path).expect("read back written glb");
                assert_eq!(got.len(), e_bytes.len(), "{name}: byte length diverged");
                let mut first_diff = None;
                for (i, (a, b)) in got.iter().zip(e_bytes.iter()).enumerate() {
                    if a != b && first_diff.is_none() {
                        first_diff = Some(i);
                    }
                }
                assert_eq!(got, e_bytes, "{name}: bytes diverged at {first_diff:?}");
                // Round-trip: the C++ bytes load through the Rust reader
                // into the fan-triangulated mesh.
                let rpath = write_temp(&e_bytes, ".glb");
                let mut positions = Vec::new();
                let mut triangles = Vec::new();
                let mut warn = String::new();
                let mut err = String::new();
                let rok = load_glb_positions_and_triangles(
                    &rpath,
                    &mut positions,
                    &mut triangles,
                    Some(&mut warn),
                    Some(&mut err),
                );
                let _ = std::fs::remove_file(&rpath);
                assert!(rok, "{name}: round-trip load failed: {err}");
                // Expected positions: verts as f32 pushed through the
                // identity transform (which NaN-poisons inf/nan corners
                // via 0*inf terms on both sides alike: R78 pins that
                // C++ and Rust agree there bitwise).
                let flat: Vec<f32> = verts
                    .iter()
                    .flat_map(|v| [v.x() as f32, v.y() as f32, v.z() as f32])
                    .collect();
                let mut expected_pos = Vec::with_capacity(flat.len());
                for v in flat.chunks_exact(3) {
                    let (x, y, z) = (v[0], v[1], v[2]);
                    expected_pos.push(1.0 * x + 0.0 * y + 0.0 * z + 0.0);
                    expected_pos.push(0.0 * x + 1.0 * y + 0.0 * z + 0.0);
                    expected_pos.push(0.0 * x + 0.0 * y + 1.0 * z + 0.0);
                }
                assert_eq!(
                    positions.len(),
                    expected_pos.len(),
                    "{name}: round-trip npos"
                );
                for (i, (a, b)) in positions.iter().zip(expected_pos.iter()).enumerate() {
                    if b.is_nan() {
                        assert!(a.is_nan(), "{name}: round-trip pos[{i}] not NaN: {a}");
                    } else {
                        assert_eq!(a.to_bits(), b.to_bits(), "{name}: round-trip pos[{i}]");
                    }
                }
                assert_eq!(triangles, fan_tris(&faces), "{name}: round-trip tris");
            }
            if let Some(p) = _cleanup {
                let _ = std::fs::remove_file(&p);
            }
        } else if f[0] == "T" {
            // Timing lines are informational only; the Rust-side timing
            // harness regenerates the same mesh and prints its own ms.
            t_lines += 1;
            assert_eq!(kv(&f, "ok"), "1");
            if f[1] == "save_glb_grid" {
                eprintln!(
                    "C++ save: nbytes={} save_ms={} hash={}",
                    kv(&f, "nbytes"),
                    kv(&f, "save_ms"),
                    kv(&f, "hash"),
                );
            } else {
                eprintln!(
                    "C++ load: npos={} ntri={} load_ms={} hash={}",
                    kv(&f, "npos"),
                    kv(&f, "ntri"),
                    kv(&f, "load_ms"),
                    kv(&f, "hash"),
                );
            }
        } else {
            panic!("unexpected fixture tag: {header:?}");
        }
    }

    assert_eq!(read_cases, 235, "expected 235 READCASE cases");
    assert_eq!(inexact_cases, 14, "expected 14 INEXACT cases");
    assert_eq!(file_cases, 1, "expected 1 FILE case");
    assert_eq!(ext_cases, 21, "expected 21 EXTCASE cases");
    assert_eq!(write_cases, 20, "expected 20 WRITECASE cases");
    assert_eq!(t_lines, 6, "expected 6 T lines");
    eprintln!(
        "differential replay: {read_cases} READ + {file_cases} FILE + {ext_cases} EXT + \
         {write_cases} WRITE, 0 mismatches, max inexact rel diff = {max_rel_diff:.3e}"
    );
}
