//! Timing mirror: regenerates the byte-identical grid mesh the C++
//! `glb_diff_dump` tool times (same loops, verified by FNV-1a hash of the
//! written bytes) and prints Rust-side save/load ms for the runtime ratio.
//! Run release: `cargo test --release --offline --test glb_timing -- --nocapture`
use retopo_core::glb::{load_glb_positions_and_triangles, save_glb};
use retopo_core::vector3::Vector3;
use std::time::Instant;

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &c in bytes {
        h ^= c as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

// GxG grid, 2 tris per cell. Mirror of the C++ timingGrid (same loop
// order, same winding).
fn timing_grid(g: usize) -> (Vec<Vector3>, Vec<Vec<usize>>) {
    let mut verts = Vec::new();
    for y in 0..g {
        for x in 0..g {
            verts.push(Vector3::new(x as f64, y as f64, 0.0));
        }
    }
    let mut faces = Vec::new();
    for y in 0..g - 1 {
        for x in 0..g - 1 {
            let a = y * g + x;
            let b = a + 1;
            let c = a + g;
            let d = c + 1;
            faces.push(vec![a, c, b]);
            faces.push(vec![b, c, d]);
        }
    }
    (verts, faces)
}

#[test]
fn timing_grid_save_and_load() {
    // Hash pinned to the C++ T lines in tests/fixtures/glb_diff.txt.
    const EXPECT_HASH: u64 = 0x564370c437130669;
    let (verts, faces) = timing_grid(200);
    let path = std::env::temp_dir().join(format!("retopo_rs_glbtime_{}.glb", std::process::id(),));
    for i in 0..3 {
        let t0 = Instant::now();
        let ok = save_glb(&path, "glb_diff_dump", &verts, &faces);
        let t1 = Instant::now();
        assert!(ok);
        let bytes = std::fs::read(&path).expect("read back timing glb");
        assert_eq!(fnv1a(&bytes), EXPECT_HASH, "regenerated bytes differ");
        assert_eq!(bytes.len(), 1431020, "nbytes");
        let ms = (t1 - t0).as_secs_f64() * 1000.0;
        eprintln!(
            "T rust save_glb_grid i={i} ok=1 nbytes={} save_ms={ms:.3} hash={EXPECT_HASH:016x}",
            bytes.len()
        );
    }
    for i in 0..3 {
        let mut positions = Vec::new();
        let mut triangles = Vec::new();
        let mut warn = String::new();
        let mut err = String::new();
        let t0 = Instant::now();
        let ok = load_glb_positions_and_triangles(
            &path,
            &mut positions,
            &mut triangles,
            Some(&mut warn),
            Some(&mut err),
        );
        let t1 = Instant::now();
        assert!(ok);
        assert_eq!(positions.len(), 120000, "npos");
        assert_eq!(triangles.len(), 79202, "ntri");
        let ms = (t1 - t0).as_secs_f64() * 1000.0;
        eprintln!(
            "T rust load_glb_grid i={i} ok=1 npos={} ntri={} load_ms={ms:.3} hash={EXPECT_HASH:016x}",
            positions.len(),
            triangles.len(),
        );
    }
    let _ = std::fs::remove_file(&path);
}
