// Differential oracle replay: parses tests/fixtures/guides_diff.txt
// (generated by the C++ guides_diff_dump tool), rebuilds every mesh and
// guide query with the Rust port, and asserts the port matches the C++
// implementation bitwise: influence radius plus all three tangent
// components. All float work goes through the FMA-exact Vector3 methods
// plus unfused +,-,*,/ (proven by the FMA audit), so every double must
// be bit-identical; NaNs (only from the NaN-robustness edge cases)
// compare by sign bit only, like the surface_mesh oracle.
use retopo_core::guides::Guides;
use retopo_core::surface_mesh::SurfaceMesh;
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/guides_diff.txt");
const EDGE_CASES: usize = 39;
const RANDOM_CASES: usize = 220;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
}

fn check_bits(case: usize, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    let same = if got.is_nan() && expect.is_nan() {
        got.is_sign_negative() == expect.is_sign_negative()
    } else {
        got.to_bits() == expect.to_bits()
    };
    assert!(
        same,
        "case {case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("GUIDES1");
    let mut cases = 0usize;
    let mut t_lines = 0usize;
    let mut compared = 0usize;
    let mut nonzero = 0usize;
    let mut zero = 0usize;
    while c.pos < c.toks.len() {
        let tag = c.word();
        match tag.as_str() {
            "CASE" => {
                cases += 1;
                let nv = c.uint();
                let nt = c.uint();
                let ng = c.uint();
                let mut positions = Vec::with_capacity(nv);
                for _ in 0..nv {
                    c.expect("v");
                    positions.push(Vector3::new(c.num(), c.num(), c.num()));
                }
                let mut triangles = Vec::with_capacity(nt);
                for _ in 0..nt {
                    c.expect("t");
                    let k = c.uint();
                    let mut face = Vec::with_capacity(k);
                    for _ in 0..k {
                        face.push(c.uint());
                    }
                    triangles.push(face);
                }
                let mut guides = Vec::with_capacity(ng);
                for _ in 0..ng {
                    c.expect("g");
                    let np = c.uint();
                    let mut polyline = Vec::with_capacity(np);
                    for _ in 0..np {
                        polyline.push(Vector3::new(c.num(), c.num(), c.num()));
                    }
                    guides.push(polyline);
                }
                c.expect("q");
                let point = Vector3::new(c.num(), c.num(), c.num());
                let normal = Vector3::new(c.num(), c.num(), c.num());
                let radius = c.num();
                let mesh = SurfaceMesh::new(&positions, &triangles);
                c.expect("R");
                check_bits(
                    cases,
                    "influence_radius",
                    Guides::influence_radius(&mesh),
                    &mut c,
                    &mut compared,
                );
                c.expect("TAN");
                let t = Guides::tangent_near(&guides, &point, &normal, radius);
                if t.x() == 0.0 && t.y() == 0.0 && t.z() == 0.0 {
                    zero += 1;
                } else {
                    nonzero += 1;
                }
                check_bits(cases, "tangent.x", t.x(), &mut c, &mut compared);
                check_bits(cases, "tangent.y", t.y(), &mut c, &mut compared);
                check_bits(cases, "tangent.z", t.z(), &mut c, &mut compared);
            }
            "T" => {
                // `T guides queries=.. influence=.. checksum=.. ms=..`:
                // informational only; the Rust timing test rebuilds the
                // same batch and must reproduce influence/checksum bitwise.
                t_lines += 1;
                for _ in 0..5 {
                    c.word();
                }
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(
        cases,
        EDGE_CASES + RANDOM_CASES,
        "expected {} cases",
        EDGE_CASES + RANDOM_CASES
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        nonzero > 50 && zero > 50,
        "unbalanced oracle: {nonzero} nonzero, {zero} zero tangents"
    );
    eprintln!(
        "guides differential replay: {cases} cases ({nonzero} nonzero, {zero} zero), {compared} doubles bitwise, 0 mismatches"
    );
}
