//! Replica goldens for the isotropic_remesher port. No C++ unit tests exist
//! for this module, so these pin verified oracle values instead: each
//! expectation below is transcribed from `tests/fixtures/isoremesh_diff.txt`
//! (generated by the C++ `isoremesh_diff_dump` tool) and proven bit-identical
//! by `isotropic_remesher_diff.rs`. Any divergence is a port defect.
//!
//! Covered: default remesh of tetra/single-triangle/cube/grid (counts,
//! first/last vertex bits, first triangle), kernel triangle-count target,
//! progress callback records, double-remesh append behavior, the dead
//! constraint-vertices setter, per-vertex lengths, and `debug_export_obj`.

use retopo_core::iso_remesh_kernel::IsoRemeshKernel;
use retopo_core::isotropic_remesher::IsotropicRemesher;
use retopo_core::vector3::Vector3;
use std::collections::HashSet;
use std::sync::{Arc, Mutex};

fn tetra_verts() -> Vec<Vector3> {
    vec![
        Vector3::new(0.0, 0.0, 0.0),
        Vector3::new(1.0, 0.0, 0.0),
        Vector3::new(0.0, 1.0, 0.0),
        Vector3::new(0.0, 0.0, 1.0),
    ]
}

fn tetra_tris() -> Vec<Vec<usize>> {
    vec![vec![0, 2, 1], vec![0, 1, 3], vec![0, 3, 2], vec![1, 2, 3]]
}

fn cube_verts() -> Vec<Vector3> {
    vec![
        Vector3::new(0.0, 0.0, 0.0),
        Vector3::new(1.0, 0.0, 0.0),
        Vector3::new(1.0, 1.0, 0.0),
        Vector3::new(0.0, 1.0, 0.0),
        Vector3::new(0.0, 0.0, 1.0),
        Vector3::new(1.0, 0.0, 1.0),
        Vector3::new(1.0, 1.0, 1.0),
        Vector3::new(0.0, 1.0, 1.0),
    ]
}

fn cube_tris() -> Vec<Vec<usize>> {
    vec![
        vec![0, 2, 1],
        vec![0, 3, 2],
        vec![4, 5, 6],
        vec![4, 6, 7],
        vec![0, 1, 5],
        vec![0, 5, 4],
        vec![2, 3, 7],
        vec![2, 7, 6],
        vec![0, 4, 7],
        vec![0, 7, 3],
        vec![1, 2, 6],
        vec![1, 6, 5],
    ]
}

fn grid_verts(w: usize, h: usize) -> Vec<Vector3> {
    let mut verts = Vec::new();
    for y in 0..=h {
        for x in 0..=w {
            verts.push(Vector3::new(x as f64, y as f64, 0.0));
        }
    }
    verts
}

fn grid_tris(w: usize, h: usize) -> Vec<Vec<usize>> {
    let mut tris = Vec::new();
    let id = |x: usize, y: usize| y * (w + 1) + x;
    for y in 0..h {
        for x in 0..w {
            let a = id(x, y);
            let b = id(x + 1, y);
            let c = id(x + 1, y + 1);
            let d = id(x, y + 1);
            tris.push(vec![a, b, c]);
            tris.push(vec![a, c, d]);
        }
    }
    tris
}

fn bits(v: &Vector3) -> (u64, u64, u64) {
    (v[0].to_bits(), v[1].to_bits(), v[2].to_bits())
}

#[test]
fn tetra_default_remesh() {
    // Fixture case 0.
    let mut remesher = IsotropicRemesher::new(&tetra_verts(), &tetra_tris());
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 4);
    assert_eq!(remesher.remeshed_triangles().len(), 4);
    assert_eq!(
        bits(&remesher.remeshed_vertices()[0]),
        (0x3fc521b8b31f4518, 0x3fabbe0cdaf95780, 0xbfb5021b28de9270)
    );
    assert_eq!(
        bits(remesher.remeshed_vertices().last().expect("nonempty")),
        (0x3fd4c9a1936fd390, 0x3fd37d7eb53ea602, 0x3fec0a8eb98723b6)
    );
    assert_eq!(remesher.remeshed_triangles()[0], vec![1, 0, 2]);
}

#[test]
fn single_triangle_all_boundary() {
    // Fixture case 1: one triangle is all boundary, so nothing moves.
    let verts = vec![
        Vector3::new(0.0, 0.0, 0.0),
        Vector3::new(1.0, 0.0, 0.0),
        Vector3::new(0.0, 1.0, 0.0),
    ];
    let tris = vec![vec![0, 1, 2]];
    let mut remesher = IsotropicRemesher::new(&verts, &tris);
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 3);
    assert_eq!(remesher.remeshed_triangles().len(), 1);
    assert_eq!(
        bits(&remesher.remeshed_vertices()[0]),
        (0x0000000000000000, 0x0000000000000000, 0x0000000000000000)
    );
    assert_eq!(
        bits(remesher.remeshed_vertices().last().expect("nonempty")),
        (0x0000000000000000, 0x3ff0000000000000, 0x0000000000000000)
    );
    assert_eq!(remesher.remeshed_triangles()[0], vec![2, 0, 1]);
}

#[test]
fn cube_sharp_edges() {
    // Fixture case 4: sharp 90-degree edges stay featured.
    let mut remesher = IsotropicRemesher::new(&cube_verts(), &cube_tris());
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 8);
    assert_eq!(remesher.remeshed_triangles().len(), 12);
    assert_eq!(
        bits(&remesher.remeshed_vertices()[0]),
        (0xbfb1c8f67b98ff70, 0xbfb40fca1676a350, 0x3fd2c86a1c05ab68)
    );
    assert_eq!(
        bits(remesher.remeshed_vertices().last().expect("nonempty")),
        (0xbfb21ee1072a1548, 0x3ff09d3e98d4d9ec, 0x3fe893b9e22e3c93)
    );
    assert_eq!(remesher.remeshed_triangles()[0], vec![0, 3, 1]);
}

#[test]
fn open_grid_boundary() {
    // Fixture case 7: open 4x4 grid keeps its boundary verts fixed.
    let mut remesher = IsotropicRemesher::new(&grid_verts(4, 4), &grid_tris(4, 4));
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 25);
    assert_eq!(remesher.remeshed_triangles().len(), 32);
    assert_eq!(
        bits(&remesher.remeshed_vertices()[0]),
        (0x0000000000000000, 0x0000000000000000, 0x0000000000000000)
    );
    assert_eq!(
        bits(remesher.remeshed_vertices().last().expect("nonempty")),
        (0x4010000000000000, 0x4010000000000000, 0x0000000000000000)
    );
    assert_eq!(remesher.remeshed_triangles()[0], vec![6, 0, 1]);
}

#[test]
fn progress_records() {
    // Fixture case 0 progress: 2 setup reports + 3x5 passes + final 1.0.
    let expected: Vec<(u32, &str)> = vec![
        (0x00000000, "Building bounding volume tree"),
        (0x3e19999a, "Splitting long edges"),
        (0x3e800000, "Splitting long edges"),
        (0x3e99999a, "Collapsing short edges"),
        (0x3eb33333, "Flipping edges"),
        (0x3ecccccd, "Shifting vertices"),
        (0x3ee66666, "Projecting vertices"),
        (0x3f000000, "Splitting long edges"),
        (0x3f0ccccd, "Collapsing short edges"),
        (0x3f19999a, "Flipping edges"),
        (0x3f266666, "Shifting vertices"),
        (0x3f333333, "Projecting vertices"),
        (0x3f400000, "Splitting long edges"),
        (0x3f4ccccd, "Collapsing short edges"),
        (0x3f59999a, "Flipping edges"),
        (0x3f666666, "Shifting vertices"),
        (0x3f733333, "Projecting vertices"),
        (0x3f800000, ""),
    ];
    let prog: Arc<Mutex<Vec<(u32, String)>>> = Arc::new(Mutex::new(Vec::new()));
    let prog_clone = Arc::clone(&prog);
    let mut remesher = IsotropicRemesher::new(&tetra_verts(), &tetra_tris());
    remesher.set_progress_handler(Box::new(move |fraction, name| {
        prog_clone
            .lock()
            .expect("prog lock")
            .push((fraction.to_bits(), name.to_string()));
    }));
    assert!(remesher.remesh());
    let got = prog.lock().expect("prog lock").clone();
    assert_eq!(got.len(), expected.len());
    for (i, (got_rec, exp_rec)) in got.iter().zip(expected.iter()).enumerate() {
        assert_eq!(got_rec.0, exp_rec.0, "progress[{i}] fraction bits");
        assert_eq!(got_rec.1, exp_rec.1, "progress[{i}] name");
    }
}

#[test]
fn remesh_appends_and_keeps_handler() {
    // The C++ pushes into the output vectors without clearing, and keeps
    // its (copied) progress handler: a second remesh() doubles the output
    // and reports progress again.
    let prog: Arc<Mutex<Vec<(u32, String)>>> = Arc::new(Mutex::new(Vec::new()));
    let prog_clone = Arc::clone(&prog);
    let mut remesher = IsotropicRemesher::new(&tetra_verts(), &tetra_tris());
    remesher.set_progress_handler(Box::new(move |fraction, name| {
        prog_clone
            .lock()
            .expect("prog lock")
            .push((fraction.to_bits(), name.to_string()));
    }));
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 4);
    assert_eq!(remesher.remeshed_triangles().len(), 4);
    assert_eq!(prog.lock().expect("prog lock").len(), 18);
    assert!(remesher.remesh());
    assert_eq!(remesher.remeshed_vertices().len(), 8);
    assert_eq!(remesher.remeshed_triangles().len(), 8);
    assert_eq!(prog.lock().expect("prog lock").len(), 36);
    // The appended half repeats the first half exactly.
    assert_eq!(
        remesher.remeshed_triangles()[4],
        remesher.remeshed_triangles()[0]
    );
}

#[test]
fn constraint_vertices_are_ignored() {
    // The C++ setter stores a set that remesh() never reads; outputs must
    // be identical with and without it.
    let mut plain = IsotropicRemesher::new(&tetra_verts(), &tetra_tris());
    assert!(plain.remesh());
    let set: HashSet<usize> = [0, 1, 2, 3].into_iter().collect();
    let mut constrained = IsotropicRemesher::new(&tetra_verts(), &tetra_tris());
    constrained.set_constraint_vertices(&set);
    assert!(constrained.remesh());
    assert_eq!(plain.remeshed_triangles(), constrained.remeshed_triangles());
    assert_eq!(
        plain
            .remeshed_vertices()
            .iter()
            .map(bits)
            .collect::<Vec<_>>(),
        constrained
            .remeshed_vertices()
            .iter()
            .map(bits)
            .collect::<Vec<_>>()
    );
}

#[test]
fn kernel_triangle_count_target() {
    // Wrapper has no triangle-count setter; the kernel honors it directly:
    // 50 triangles on the tetra refines the mesh (fixture K cases cover
    // more of this surface).
    let verts = tetra_verts();
    let tris = tetra_tris();
    let mut remesher = IsoRemeshKernel::new(&verts, &tris);
    assert_eq!(
        remesher.initial_average_edge_length().to_bits(),
        0x3ff3504f333f9de7
    );
    remesher.set_target_triangle_count(50);
    remesher.set_sharp_edge_included_angle(180.0 - 60.0);
    remesher.remesh(3);
    let mesh = remesher.remeshed_halfedge_mesh();
    let mut nv = 0;
    let mut v = mesh.move_to_next_vertex(None);
    while let Some(current) = v {
        nv += 1;
        v = mesh.move_to_next_vertex(Some(current));
    }
    let mut nt = 0;
    let mut f = mesh.move_to_next_face(None);
    while let Some(current) = f {
        nt += 1;
        f = mesh.move_to_next_face(Some(current));
    }
    assert_eq!((nv, nt), (49, 94));
}

#[test]
fn debug_export_obj_format() {
    // `%f` vertices plus 1-based faces, byte-exact.
    let mut remesher = IsotropicRemesher::new(
        &[
            Vector3::new(0.0, 0.0, 0.0),
            Vector3::new(1.0, 0.0, 0.0),
            Vector3::new(0.0, 1.0, 0.0),
        ],
        &[vec![0, 1, 2]],
    );
    assert!(remesher.remesh());
    let path = std::env::temp_dir().join(format!(
        "retopo_rs_isoremesh_test_{}.obj",
        std::process::id()
    ));
    remesher.debug_export_obj(path.to_str().expect("utf8 path"));
    let text = std::fs::read_to_string(&path).expect("read exported obj");
    let _ = std::fs::remove_file(&path);
    let mut lines = text.lines();
    assert_eq!(lines.next(), Some("v 0.000000 0.000000 0.000000"));
    assert_eq!(lines.next(), Some("v 1.000000 0.000000 0.000000"));
    assert_eq!(lines.next(), Some("v 0.000000 1.000000 0.000000"));
    assert_eq!(lines.next(), Some("f 3 1 2"));
    assert_eq!(lines.next(), None);
}
