//! Differential oracle replay: parses `tests/fixtures/isoremesh_diff.txt`
//! (generated by the C++ `isoremesh_diff_dump` tool), replays every case
//! through the Rust port, and asserts the port matches the C++ implementation
//! bit-for-bit: same ok flags, same remeshed vertex positions (f64 bits),
//! same triangles, same progress records (f32 bits + names), same kernel
//! average edge lengths. Zero mismatches allowed.

use retopo_core::iso_remesh_kernel::IsoRemeshKernel;
use retopo_core::isotropic_remesher::IsotropicRemesher;
use retopo_core::vector3::Vector3;
use std::sync::{Arc, Mutex};

const FIXTURE: &str = include_str!("../../../tests/fixtures/isoremesh_diff.txt");

const WRAPPER_CASES: usize = 212;
const KERNEL_CASES: usize = 36;

fn bits(hex: &str) -> u64 {
    u64::from_str_radix(hex, 16).expect("bad hex word")
}

fn v3(words: &[&str]) -> Vector3 {
    assert_eq!(words.len(), 3, "V arity");
    Vector3::new(
        f64::from_bits(bits(words[0])),
        f64::from_bits(bits(words[1])),
        f64::from_bits(bits(words[2])),
    )
}

fn fields(line: &str) -> Vec<&str> {
    line.split_ascii_whitespace().collect()
}

fn kv<'a>(f: &[&'a str], key: &str) -> &'a str {
    let prefix = format!("{key}=");
    for tok in f {
        if let Some(v) = tok.strip_prefix(&prefix) {
            return v;
        }
    }
    panic!("missing {key} in {f:?}");
}

struct Cur<'a> {
    lines: Vec<&'a str>,
    pos: usize,
}

impl<'a> Cur<'a> {
    fn new(s: &'a str) -> Self {
        Self {
            lines: s.split('\n').collect(),
            pos: 0,
        }
    }
    fn line(&mut self) -> &'a str {
        let l = self.lines[self.pos];
        self.pos += 1;
        l
    }
    fn done(&self) -> bool {
        self.pos >= self.lines.len()
            || (self.pos + 1 == self.lines.len() && self.lines[self.pos].is_empty())
    }
}

fn parse_tri(line: &str, tag: &str) -> Vec<usize> {
    let f = fields(line);
    assert_eq!(f[0], tag, "expected {tag} line, got {line:?}");
    assert_eq!(f.len(), 4, "{tag} arity");
    f[1..].iter().map(|w| w.parse().expect("bad idx")).collect()
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    assert_eq!(c.line(), "ISOREMESH1");
    let mut wrapper_cases = 0usize;
    let mut kernel_cases = 0usize;
    let mut t_lines = 0usize;
    let mut max_abs_diff = 0.0f64;
    let mut max_ulp_diff = 0u64;
    let mut mismatches: Vec<String> = Vec::new();
    let mut first_detail = String::new();

    while !c.done() {
        let header = c.line();
        let f = fields(header);
        if f[0] == "CASE" {
            let id: usize = f[1].parse().expect("bad id");
            let kernel = kv(&f, "MODE") == "K";
            if kernel {
                kernel_cases += 1;
            } else {
                wrapper_cases += 1;
            }
            let nv: usize = kv(&f, "NV").parse().expect("bad NV");
            let nt: usize = kv(&f, "NT").parse().expect("bad NT");
            let tel: f64 = kv(&f, "TEL").parse().expect("bad TEL");
            let sharp: f64 = kv(&f, "SHARP").parse().expect("bad SHARP");
            let smooth: f64 = kv(&f, "SMOOTH").parse().expect("bad SMOOTH");
            let vtel = kv(&f, "VTEL") == "1";
            let ttc: usize = kv(&f, "TTC").parse().expect("bad TTC");
            let iters: usize = kv(&f, "ITERS").parse().expect("bad ITERS");

            let mut vertices = Vec::with_capacity(nv);
            for _ in 0..nv {
                let g = fields(c.line());
                assert_eq!(g[0], "V");
                vertices.push(v3(&g[1..]));
            }
            let mut triangles = Vec::with_capacity(nt);
            for _ in 0..nt {
                triangles.push(parse_tri(c.line(), "T"));
            }
            let lengths: Option<Vec<f64>> = if vtel {
                let g = fields(c.line());
                assert_eq!(g[0], "VLEN");
                assert_eq!(g.len(), 1 + nv, "VLEN arity");
                Some(g[1..].iter().map(|w| f64::from_bits(bits(w))).collect())
            } else {
                None
            };

            let fr = fields(c.line());
            assert_eq!(fr[0], "R");
            let e_ok = kv(&fr, "ok") == "1";
            let e_nv: usize = kv(&fr, "nv").parse().expect("bad nv");
            let e_nt: usize = kv(&fr, "nt").parse().expect("bad nt");
            let e_np: usize = kv(&fr, "np").parse().expect("bad np");
            let e_avg = if kernel {
                Some(f64::from_bits(bits(kv(&fr, "avg"))))
            } else {
                None
            };
            let mut e_verts = Vec::with_capacity(e_nv);
            for _ in 0..e_nv {
                let g = fields(c.line());
                assert_eq!(g[0], "OV");
                e_verts.push(v3(&g[1..]));
            }
            let mut e_tris = Vec::with_capacity(e_nt);
            for _ in 0..e_nt {
                e_tris.push(parse_tri(c.line(), "OT"));
            }
            let mut e_prog: Vec<(u32, String)> = Vec::with_capacity(e_np);
            for _ in 0..e_np {
                let line = c.line();
                assert!(line.starts_with("P "), "expected P line, got {line:?}");
                let (w, name) = line[2..].split_once(' ').unwrap_or((&line[2..], ""));
                e_prog.push((
                    u32::from_str_radix(w, 16).expect("bad prog bits"),
                    name.to_string(),
                ));
            }

            // Replay through the Rust port.
            let prog: Arc<Mutex<Vec<(u32, String)>>> = Arc::new(Mutex::new(Vec::new()));
            let prog_clone = Arc::clone(&prog);
            let handler: Box<dyn Fn(f32, &str) + Send + Sync> = Box::new(move |fraction, name| {
                prog_clone
                    .lock()
                    .expect("prog lock")
                    .push((fraction.to_bits(), name.to_string()));
            });
            let (ok, got_verts, got_tris, got_avg) = if kernel {
                let mut remesher = IsoRemeshKernel::new(&vertices, &triangles);
                let avg = remesher.initial_average_edge_length();
                if tel > 0.0 {
                    remesher.set_target_edge_length(tel);
                }
                if ttc > 0 {
                    remesher.set_target_triangle_count(ttc);
                }
                if let Some(lengths) = &lengths {
                    remesher.set_vertex_target_edge_lengths(lengths);
                }
                remesher.set_sharp_edge_included_angle(180.0 - sharp);
                remesher.set_smooth_normal_degrees(smooth);
                remesher.set_progress_handler(handler);
                remesher.remesh(iters);
                let mesh = remesher.remeshed_halfedge_mesh();
                // Same output-index assignment + face loop as the C++ dump.
                let mut output_index = 0;
                let mut out_verts = Vec::new();
                let mut v = mesh.move_to_next_vertex(None);
                while let Some(current) = v {
                    v = mesh.move_to_next_vertex(Some(current));
                    mesh.vertex_mut(current).output_index = output_index;
                    output_index += 1;
                    out_verts.push(mesh.vertex(current).position);
                }
                let mut out_tris = Vec::new();
                let mut ff = mesh.move_to_next_face(None);
                while let Some(current) = ff {
                    ff = mesh.move_to_next_face(Some(current));
                    let start = mesh.face(current).halfedge;
                    let previous = mesh.halfedge(start).previous_halfedge;
                    let next = mesh.halfedge(start).next_halfedge;
                    out_tris.push(vec![
                        mesh.vertex(mesh.halfedge(previous).start_vertex)
                            .output_index,
                        mesh.vertex(mesh.halfedge(start).start_vertex).output_index,
                        mesh.vertex(mesh.halfedge(next).start_vertex).output_index,
                    ]);
                }
                (true, out_verts, out_tris, Some(avg))
            } else {
                let mut remesher = IsotropicRemesher::new(&vertices, &triangles);
                if tel > 0.0 {
                    remesher.set_target_edge_length(tel);
                }
                if let Some(lengths) = &lengths {
                    remesher.set_vertex_target_edge_lengths(lengths);
                }
                remesher.set_sharp_edge_degrees(sharp);
                remesher.set_smooth_normal_degrees(smooth);
                remesher.set_progress_handler(handler);
                let ok = remesher.remesh();
                (
                    ok,
                    remeshed_vec(remesher.remeshed_vertices()),
                    remesher.remeshed_triangles().to_vec(),
                    None,
                )
            };
            let got_prog = prog.lock().expect("prog lock").clone();

            let name = format!("case {id} (MODE={})", if kernel { "K" } else { "W" });
            if ok != e_ok {
                record(
                    &mut mismatches,
                    &mut first_detail,
                    &name,
                    "ok",
                    format!("{name}: ok diverged (rust={ok} cpp={e_ok})"),
                );
            }
            if let (Some(got_avg), Some(e_avg)) = (got_avg, e_avg) {
                if got_avg.to_bits() != e_avg.to_bits() {
                    record(
                        &mut mismatches,
                        &mut first_detail,
                        &name,
                        "avg",
                        format!(
                            "{name}: avg diverged (rust={:016x} cpp={:016x})",
                            got_avg.to_bits(),
                            e_avg.to_bits()
                        ),
                    );
                }
                max_abs_diff = max_abs_diff.max((got_avg - e_avg).abs());
            }
            if got_verts.len() != e_verts.len() || got_tris.len() != e_tris.len() {
                record(
                    &mut mismatches,
                    &mut first_detail,
                    &name,
                    "counts",
                    format!(
                        "{name}: counts diverged (rust nv={} nt={} cpp nv={} nt={})",
                        got_verts.len(),
                        got_tris.len(),
                        e_verts.len(),
                        e_tris.len()
                    ),
                );
            } else {
                let mut pos_failed = false;
                for (i, (got, exp)) in got_verts.iter().zip(e_verts.iter()).enumerate() {
                    if pos_failed {
                        break;
                    }
                    for k in 0..3 {
                        let (gb, eb) = (got[k].to_bits(), exp[k].to_bits());
                        if gb != eb {
                            let ulp = gb.abs_diff(eb);
                            max_ulp_diff = max_ulp_diff.max(ulp);
                            max_abs_diff = max_abs_diff.max((got[k] - exp[k]).abs());
                            record(
                                &mut mismatches,
                                &mut first_detail,
                                &name,
                                "pos",
                                format!(
                                    "{name}: vert[{i}][{k}] bits diverged\n rust={:016x} ({}) cpp={:016x} ({})",
                                    gb, got[k], eb, exp[k]
                                ),
                            );
                            pos_failed = true;
                            break;
                        }
                    }
                }
                if got_tris != e_tris {
                    record(
                        &mut mismatches,
                        &mut first_detail,
                        &name,
                        "tris",
                        format!("{name}: triangles diverged:\n rust={got_tris:?}\n cpp={e_tris:?}"),
                    );
                }
            }
            if got_prog != e_prog {
                record(
                    &mut mismatches,
                    &mut first_detail,
                    &name,
                    "prog",
                    format!("{name}: progress diverged:\n rust={got_prog:?}\n cpp={e_prog:?}"),
                );
            }
        } else if f[0] == "T" {
            t_lines += 1;
            eprintln!(
                "C++ {}: nv={} nt={} outv={} outt={} ok={} ms={}",
                f[1],
                kv(&f, "nv"),
                kv(&f, "nt"),
                kv(&f, "outv"),
                kv(&f, "outt"),
                kv(&f, "ok"),
                kv(&f, "ms"),
            );
        } else {
            panic!("unexpected fixture tag: {header:?}");
        }
    }

    assert_eq!(
        wrapper_cases, WRAPPER_CASES,
        "expected {WRAPPER_CASES} W cases"
    );
    assert_eq!(
        kernel_cases, KERNEL_CASES,
        "expected {KERNEL_CASES} K cases"
    );
    assert_eq!(t_lines, 3, "expected 3 T lines");
    eprintln!(
        "differential replay: {wrapper_cases} W + {kernel_cases} K, {} mismatches, max |diff| = {max_abs_diff:.3e}, max ulp = {max_ulp_diff}",
        mismatches.len()
    );
    assert!(
        mismatches.is_empty(),
        "oracle mismatches: {mismatches:?}\n{first_detail}"
    );
}

fn remeshed_vec(v: &[Vector3]) -> Vec<Vector3> {
    v.to_vec()
}

fn record(
    mismatches: &mut Vec<String>,
    first_detail: &mut String,
    name: &str,
    what: &str,
    detail: String,
) {
    mismatches.push(format!("{name}: {what}"));
    if first_detail.is_empty() {
        *first_detail = detail;
    }
}
