// Differential oracle replay: parses tests/fixtures/meshsep_diff.txt
// (generated by the C++ meshsep_diff_dump tool), re-splits every mesh with
// the Rust port, and asserts the port matches the C++ implementation
// exactly: same directed-edge map entries, same island count, same faces in
// the same order in every island. Integer data, so equality is exact.
use retopo_core::mesh_separator::MeshSeparator;
use std::collections::BTreeMap;

const FIXTURE: &str = include_str!("../../../tests/fixtures/meshsep_diff.txt");
const EDGE_CASES: usize = 16;
const RANDOM_CASES: usize = 220;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn face(&mut self) -> Vec<usize> {
        self.expect("f");
        let k = self.uint();
        (0..k).map(|_| self.uint()).collect()
    }
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("MESHSEP1");
    let mut cases = 0usize;
    let mut t_lines = 0usize;
    let mut fallback_cases = 0usize;
    let mut mismatches: Vec<String> = Vec::new();
    let mut first_detail = String::new();
    while c.pos < c.toks.len() {
        let tag = c.word();
        match tag.as_str() {
            "CASE" => {
                cases += 1;
                let nfaces = c.uint();
                let mut faces = Vec::with_capacity(nfaces);
                for _ in 0..nfaces {
                    faces.push(c.face());
                }
                if faces.iter().flatten().any(|&v| v > 0xffff_ffff) {
                    fallback_cases += 1;
                }
                c.expect("MAP");
                let nmap = c.uint();
                let mut expected_map = Vec::with_capacity(nmap);
                for _ in 0..nmap {
                    c.expect("m");
                    let from = c.uint();
                    let to = c.uint();
                    let idx = c.uint();
                    expected_map.push(((from, to), idx));
                }
                c.expect("ISLANDS");
                let nislands = c.uint();
                let mut expected: Vec<Vec<Vec<usize>>> = Vec::with_capacity(nislands);
                for _ in 0..nislands {
                    c.expect("ISL");
                    let m = c.uint();
                    let mut island = Vec::with_capacity(m);
                    for _ in 0..m {
                        island.push(c.face());
                    }
                    expected.push(island);
                }
                // Replay the directed-edge map (BTreeMap iterates in the
                // same ascending order as the C++ std::map dump).
                let mut got_map = BTreeMap::new();
                MeshSeparator::build_edge_to_face_map(&faces, &mut got_map);
                let got_entries: Vec<((usize, usize), usize)> = got_map.into_iter().collect();
                if got_entries != expected_map {
                    mismatches.push(format!("case {cases}: edge map"));
                    if first_detail.is_empty() {
                        first_detail = format!(
                            "case {cases}: edge map diverged:\n faces={faces:?}\n rust={got_entries:?}\n cpp={expected_map:?}"
                        );
                    }
                }
                // Replay the island split.
                let mut got = Vec::new();
                MeshSeparator::split_to_islands(&faces, &mut got);
                if got != expected {
                    mismatches.push(format!("case {cases}: islands"));
                    if first_detail.is_empty() {
                        first_detail = format!(
                            "case {cases}: islands diverged:\n faces={faces:?}\n rust={got:?}\n cpp={expected:?}"
                        );
                    }
                }
            }
            "T" => {
                // `T meshsep faces=N islands=M ms=X`: informational only;
                // the Rust timing test regenerates the same grid.
                t_lines += 1;
                for _ in 0..4 {
                    c.word();
                }
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(
        cases,
        EDGE_CASES + RANDOM_CASES,
        "expected {} cases",
        EDGE_CASES + RANDOM_CASES
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        fallback_cases > 0,
        "no >u32 case replayed: packed-table fallback unproven"
    );
    eprintln!(
        "meshsep differential replay: {cases} cases ({} fallback), {} mismatches",
        fallback_cases,
        mismatches.len()
    );
    assert!(
        mismatches.is_empty(),
        "oracle mismatches: {mismatches:?}\n{first_detail}"
    );
}
