//! Timing mirror: regenerates the byte-identical large inputs the C++
//! `objreader_diff_dump` tool times (same loops, verified by FNV-1a hash) and
//! prints Rust-side load/weld ms for the calibration runtime ratio. Run release:
//! `cargo test --release --offline --test obj_reader_timing -- --nocapture`
use retopo_core::obj_reader::{load_obj_positions_and_triangles, weld_positions_and_triangles};
use std::time::Instant;

fn fnv1a(s: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &c in s {
        h ^= c as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

// GxG grid, indexed: G*G vertices + 2*(G-1)^2 triangles. Mirror of the C++
// timingIndexed (same loop order, same format strings).
fn timing_indexed(g: usize) -> Vec<u8> {
    let mut obj = String::new();
    for y in 0..g {
        for x in 0..g {
            obj.push_str(&format!("v {x} {y} 0\n"));
        }
    }
    for y in 0..g - 1 {
        for x in 0..g - 1 {
            let a = y * g + x + 1;
            let b = a + 1;
            let c = a + g;
            let d = c + 1;
            obj.push_str(&format!("f {a} {c} {b}\n"));
            obj.push_str(&format!("f {b} {c} {d}\n"));
        }
    }
    obj.into_bytes()
}

// Same triangles as non-indexed soup (weld stress). Mirror of C++ timingSoup.
fn timing_soup(g: usize) -> Vec<u8> {
    let mut obj = String::new();
    let mut vi = 0usize;
    for y in 0..g - 1 {
        for x in 0..g - 1 {
            let xs = [x, x, x + 1, x + 1, x, x + 1];
            let ys = [y, y + 1, y, y, y + 1, y + 1];
            for k in 0..6 {
                obj.push_str(&format!("v {} {} 0\n", xs[k], ys[k]));
            }
            obj.push_str(&format!("f {} {} {}\n", vi + 1, vi + 2, vi + 3));
            obj.push_str(&format!("f {} {} {}\n", vi + 4, vi + 5, vi + 6));
            vi += 6;
        }
    }
    obj.into_bytes()
}

fn time_input(name: &str, obj: &[u8], expect_hash: u64) {
    assert_eq!(fnv1a(obj), expect_hash, "{name}: regenerated bytes differ");
    let path = std::env::temp_dir().join(format!(
        "retopo_rs_objtime_{}_{}.obj",
        std::process::id(),
        name
    ));
    std::fs::write(&path, obj).expect("write timing obj");
    for _ in 0..3 {
        let mut positions = Vec::new();
        let mut triangles = Vec::new();
        let mut warn = String::new();
        let mut err = String::new();
        let t0 = Instant::now();
        let ok = load_obj_positions_and_triangles(
            &path,
            &mut positions,
            &mut triangles,
            Some(&mut warn),
            Some(&mut err),
        );
        let t1 = Instant::now();
        weld_positions_and_triangles(&mut positions, &mut triangles, None);
        let t2 = Instant::now();
        assert!(ok);
        // Indexed input is already welded (identity); soup welds back to the
        // same 40k-vertex / 79202-triangle mesh. Same numbers as the C++ T lines.
        assert_eq!(positions.len(), 120000, "{name}: npos");
        assert_eq!(triangles.len(), 79202, "{name}: ntri");
        let load_ms = (t1 - t0).as_secs_f64() * 1000.0;
        let weld_ms = (t2 - t1).as_secs_f64() * 1000.0;
        eprintln!(
            "T rust obj_{name} ok={ok} npos={} ntri={} load_ms={load_ms:.3} weld_ms={weld_ms:.3} hash={expect_hash:016x}",
            positions.len(),
            triangles.len(),
        );
    }
    let _ = std::fs::remove_file(&path);
}

#[test]
fn timing_large_inputs() {
    // Hashes pinned to the C++ T lines in tests/fixtures/objreader_diff.txt.
    time_input("indexed", &timing_indexed(200), 0xea327fa03d8acfee);
    time_input("soup", &timing_soup(200), 0x3858067516885998);
}
