//! Differential oracle replay: parses `tests/fixtures/objreader_diff.txt`
//! (generated by the C++ `objreader_diff_dump` tool), replays every case
//! through the Rust port, and asserts the port matches the C++ implementation
//! bit-for-bit: same ok flags, same positions (f32 bits), same triangles, same
//! warn/err strings, same weld outputs and stats. Zero mismatches allowed.

use retopo_core::obj_reader::{
    WeldStats, load_obj_positions_and_triangles, weld_positions_and_triangles,
};
use std::sync::atomic::{AtomicUsize, Ordering};

const FIXTURE: &str = include_str!("../../../tests/fixtures/objreader_diff.txt");

static TEMP_COUNTER: AtomicUsize = AtomicUsize::new(0);

fn unescape(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] != b'\\' {
            out.push(b[i]);
            i += 1;
            continue;
        }
        i += 1;
        match b[i] {
            b'\\' => out.push(b'\\'),
            b'r' => out.push(b'\r'),
            b'n' => out.push(b'\n'),
            b'0' => out.push(0),
            b'x' => {
                let hex = std::str::from_utf8(&b[i + 1..i + 3]).expect("bad hex");
                out.push(u8::from_str_radix(hex, 16).expect("bad hex"));
                i += 2;
            }
            e => panic!("bad escape: \\{}", e as char),
        }
        i += 1;
    }
    out
}

struct Cur<'a> {
    lines: Vec<&'a str>,
    pos: usize,
}

impl<'a> Cur<'a> {
    fn new(s: &'a str) -> Self {
        Self {
            lines: s.split('\n').collect(),
            pos: 0,
        }
    }
    fn line(&mut self) -> &'a str {
        let l = self.lines[self.pos];
        self.pos += 1;
        l
    }
    fn done(&self) -> bool {
        // Trailing newline yields one phantom empty line.
        self.pos >= self.lines.len()
            || (self.pos + 1 == self.lines.len() && self.lines[self.pos].is_empty())
    }
}

fn fields(line: &str) -> Vec<&str> {
    line.split_ascii_whitespace().collect()
}

fn kv<'a>(f: &[&'a str], key: &str) -> &'a str {
    let prefix = format!("{key}=");
    for tok in f {
        if let Some(v) = tok.strip_prefix(&prefix) {
            return v;
        }
    }
    panic!("missing {key} in {f:?}");
}

fn parse_pos(line: &str, tag: &str) -> Vec<u32> {
    let f = fields(line);
    assert_eq!(f[0], tag, "expected {tag} line, got {line:?}");
    f[1..]
        .iter()
        .map(|w| u32::from_str_radix(w, 16).expect("bad hex word"))
        .collect()
}

fn parse_tris(c: &mut Cur<'_>, n: usize, tag: &str) -> Vec<Vec<usize>> {
    let mut out = Vec::with_capacity(n);
    for _ in 0..n {
        let f = fields(c.line());
        assert_eq!(f[0], tag);
        let k: usize = f[1].parse().expect("bad k");
        assert_eq!(f.len(), 2 + k, "TRI arity");
        out.push(f[2..].iter().map(|w| w.parse().expect("bad idx")).collect());
    }
    out
}

fn sentinel_positions() -> Vec<f32> {
    vec![1.5, -2.5]
}

fn sentinel_triangles() -> Vec<Vec<usize>> {
    vec![vec![99], vec![7, 8]]
}

fn write_temp(bytes: &[u8]) -> std::path::PathBuf {
    let path = std::env::temp_dir().join(format!(
        "retopo_rs_objdiff_{}_{}.obj",
        std::process::id(),
        TEMP_COUNTER.fetch_add(1, Ordering::SeqCst)
    ));
    std::fs::write(&path, bytes).expect("write temp obj");
    path
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    assert_eq!(c.line(), "OBJDIFF1");
    let mut gen_cases = 0usize;
    let mut fixed_cases = 0usize;
    let mut file_cases = 0usize;
    let mut weld_cases = 0usize;
    let mut t_lines = 0usize;
    let mut max_diff = 0.0f32;
    let mut nan_payload_cases = 0usize;

    while !c.done() {
        let header = c.line();
        let f = fields(header);
        if f[0] == "CASE" || f[0] == "FIXED" || f[0] == "FILE" {
            let (id, name) = if f[0] == "FILE" {
                file_cases += 1;
                (file_cases, format!("FILE {}", f[1]))
            } else {
                if f[0] == "CASE" {
                    gen_cases += 1;
                } else {
                    fixed_cases += 1;
                }
                let id: usize = f[1].parse().expect("bad id");
                (id, format!("{} {id}", f[0]))
            };
            let _ = id;
            assert_eq!(f[f.len() - 2], "LINES");
            let nlines: usize = f[f.len() - 1].parse().expect("bad LINES");
            let mut bytes: Vec<u8> = Vec::new();
            for i in 0..nlines {
                if i > 0 {
                    bytes.push(b'\n');
                }
                bytes.extend_from_slice(&unescape(c.line()));
            }
            // Load through the real file API (temp file, like production).
            let path = write_temp(&bytes);
            let mut positions = sentinel_positions();
            let mut triangles = sentinel_triangles();
            let mut warn = String::new();
            let mut err = String::new();
            let ok = load_obj_positions_and_triangles(
                &path,
                &mut positions,
                &mut triangles,
                Some(&mut warn),
                Some(&mut err),
            );
            let _ = std::fs::remove_file(&path);

            let fr = fields(c.line());
            assert_eq!(fr[0], "R");
            let e_ok = kv(&fr, "ok") == "1";
            let e_npos: usize = kv(&fr, "npos").parse().expect("bad npos");
            let e_ntri: usize = kv(&fr, "ntri").parse().expect("bad ntri");
            assert_eq!(ok, e_ok, "{name}: ok flag diverged");
            assert_eq!(positions.len(), e_npos, "{name}: npos diverged");
            assert_eq!(triangles.len(), e_ntri, "{name}: ntri diverged");
            let e_pos = parse_pos(c.line(), "POS");
            assert_eq!(e_pos.len(), e_npos, "{name}: POS arity");
            for (i, w) in e_pos.iter().enumerate() {
                let got = positions[i].to_bits();
                assert_eq!(got, *w, "{name}: pos[{i}] bits diverged");
                let d = (positions[i] - f32::from_bits(*w)).abs();
                if d.is_nan() {
                    nan_payload_cases += 1;
                } else {
                    max_diff = max_diff.max(d);
                }
            }
            let e_tri = parse_tris(&mut c, e_ntri, "TRI");
            assert_eq!(triangles, e_tri, "{name}: triangles diverged");
            let wline = c.line();
            let e_warn = unescape(wline.strip_prefix("W ").expect("bad W"));
            assert_eq!(warn.as_bytes(), e_warn.as_slice(), "{name}: warn diverged");
            let eline = c.line();
            let e_err = unescape(eline.strip_prefix("E ").expect("bad E"));
            assert_eq!(err.as_bytes(), e_err.as_slice(), "{name}: err diverged");

            if e_ok {
                let fw = fields(c.line());
                assert_eq!(fw[0], "WELD");
                let e_wpos: usize = kv(&fw, "npos").parse().expect("bad WELD npos");
                let e_wtri: usize = kv(&fw, "ntri").parse().expect("bad WELD ntri");
                let e_deg: usize = kv(&fw, "deg").parse().expect("bad deg");
                let e_nonfin: usize = kv(&fw, "nonfin").parse().expect("bad nonfin");
                let mut wpos = positions.clone();
                let mut wtri = triangles.clone();
                let mut stats = WeldStats::default();
                weld_positions_and_triangles(&mut wpos, &mut wtri, Some(&mut stats));
                assert_eq!(wpos.len(), e_wpos, "{name}: weld npos diverged");
                assert_eq!(wtri.len(), e_wtri, "{name}: weld ntri diverged");
                assert_eq!(stats.degenerate_dropped, e_deg, "{name}: weld deg diverged");
                assert_eq!(
                    stats.non_finite_dropped, e_nonfin,
                    "{name}: weld nonfin diverged"
                );
                let e_wpos_bits = parse_pos(c.line(), "POS");
                for (i, w) in e_wpos_bits.iter().enumerate() {
                    assert_eq!(wpos[i].to_bits(), *w, "{name}: weld pos[{i}] diverged");
                }
                let e_wtri = parse_tris(&mut c, e_wtri, "TRI");
                assert_eq!(wtri, e_wtri, "{name}: weld tris diverged");
            }
        } else if f[0] == "WELDCASE" {
            weld_cases += 1;
            let name = format!("WELDCASE {}", f[1]);
            let e_npos: usize = kv(&f, "npos").parse().expect("bad npos");
            let e_ntri: usize = kv(&f, "ntri").parse().expect("bad ntri");
            let in_bits = parse_pos(c.line(), "INPOS");
            assert_eq!(in_bits.len(), e_npos, "{name}: INPOS arity");
            let mut positions: Vec<f32> = in_bits.iter().map(|w| f32::from_bits(*w)).collect();
            let mut triangles = parse_tris(&mut c, e_ntri, "INTRI");
            let fw = fields(c.line());
            assert_eq!(fw[0], "WELDOUT");
            let e_wpos: usize = kv(&fw, "npos").parse().expect("bad npos");
            let e_wtri: usize = kv(&fw, "ntri").parse().expect("bad ntri");
            let e_deg: usize = kv(&fw, "deg").parse().expect("bad deg");
            let e_nonfin: usize = kv(&fw, "nonfin").parse().expect("bad nonfin");
            let mut stats = WeldStats::default();
            weld_positions_and_triangles(&mut positions, &mut triangles, Some(&mut stats));
            assert_eq!(positions.len(), e_wpos, "{name}: npos diverged");
            assert_eq!(triangles.len(), e_wtri, "{name}: ntri diverged");
            assert_eq!(stats.degenerate_dropped, e_deg, "{name}: deg diverged");
            assert_eq!(
                stats.non_finite_dropped, e_nonfin,
                "{name}: nonfin diverged"
            );
            let e_pos = parse_pos(c.line(), "POS");
            for (i, w) in e_pos.iter().enumerate() {
                assert_eq!(positions[i].to_bits(), *w, "{name}: pos[{i}] diverged");
            }
            let e_tri = parse_tris(&mut c, e_wtri, "WTRI");
            assert_eq!(triangles, e_tri, "{name}: tris diverged");
        } else if f[0] == "T" {
            // Timing lines are informational only; the Rust-side timing
            // harness regenerates the same inputs and prints its own ms.
            t_lines += 1;
            assert_eq!(kv(&f, "ok"), "1");
            eprintln!(
                "C++ {}: npos={} ntri={} load_ms={} weld_ms={} hash={}",
                f[1],
                kv(&f, "npos"),
                kv(&f, "ntri"),
                kv(&f, "load_ms"),
                kv(&f, "weld_ms"),
                kv(&f, "hash"),
            );
        } else {
            panic!("unexpected fixture tag: {header:?}");
        }
    }

    assert_eq!(gen_cases, 220, "expected 220 GEN cases");
    assert_eq!(fixed_cases, 250, "expected 250 FIXED cases");
    assert_eq!(file_cases, 11, "expected 11 FILE cases");
    assert_eq!(weld_cases, 80, "expected 80 WELDCASE cases");
    assert_eq!(t_lines, 6, "expected 6 T lines");
    eprintln!(
        "differential replay: {gen_cases} GEN + {fixed_cases} FIXED + {file_cases} FILE + {weld_cases} WELD, \
         0 mismatches, max |diff| = {max_diff:.3e} ({nan_payload_cases} NaN-bit compares)"
    );
    assert_eq!(max_diff, 0.0, "max diff must be zero (bitwise oracle)");
}
