// Harness indexes parallel arrays/cursors in lockstep; index loops stay.
#![allow(clippy::needless_range_loop)]

// Differential oracle replay: parses tests/fixtures/parameterizer_diff.txt
// (generated by the C++ parameterizer_diff_dump tool), re-runs every case
// with the Rust port, and asserts the port matches the C++ implementation.
//
// Two sections, mirroring the quad lane's CASE/QPX split:
// - CASE (strict): same ok flag, same progress-event sequence (alias +
//   bitwise f32 fraction, which pins the branch choices and the MILS
//   rounding iteration count), same singular vertices, UV values within
//   scale-aware 1e-6, plus structural invariants (original UVs agree with
//   taken UVs, singular positions derive from indices, second take is None).
// - PPX (robustness-only): non-manifold random soup (not
//   downstream-plausible; ill-conditioned covers by construction) plus
//   listed manifold stragglers with a demonstrated backend-noise
//   mechanism each (none so far). The port must match every structural
//   fact and solve everything C++ solves; value agreement is reported,
//   not asserted.
use retopo_core::parameterizer::Parameterizer;
use retopo_core::progress::ProgressHandler;
use retopo_core::symmetry::SymmetryPlane;
use retopo_core::vector3::Vector3;
use std::sync::{Arc, Mutex};

const FIXTURE: &str = include_str!("../../../tests/fixtures/parameterizer_diff.txt");
const TOL: f64 = 1e-6;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn int(&mut self) -> i64 {
        self.word().parse().expect("bad int")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn frac(&mut self) -> f32 {
        self.word().parse().expect("bad f32")
    }
    fn v3(&mut self) -> Vector3 {
        let x = self.num();
        let y = self.num();
        let z = self.num();
        Vector3::new(x, y, z)
    }
}

fn prog_alias(name: &str) -> &'static str {
    match name {
        "Computing vertex normals" => "VNORM",
        "Computing scaling field" => "VSCALE",
        "Building surface topology" => "TOPO",
        "Solving frame field" => "FIELD",
        "Symmetrizing frame field" => "SYMM",
        "Simplifying singularities" => "SIMP",
        "Computing anisotropy field" => "ANISO",
        "Collecting singularities" => "SING",
        "" => "DONE",
        "Initializing cover field" => "INIT",
        "Smoothing cross field" => "SMOOTH",
        "Computing corner rotations" => "ROTC",
        "Correcting field curl" => "CURL",
        "Building cover system" => "BUILD",
        "Eliminating cover constraints" => "ELIM",
        "Rounding cover to integers" => "ROUND",
        "Building cover uvs" => "UVS",
        _ => "UNKNOWN",
    }
}

struct PpxStats {
    cases: usize,
    both_ok: usize,
    value_agree: usize,
    max_diff: f64,
    max_diff_at: String,
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("PPDIFF1");
    let mut strict_cases = 0usize;
    let mut strict_ok = 0usize;
    let mut stats = PpxStats {
        cases: 0,
        both_ok: 0,
        value_agree: 0,
        max_diff: 0.0,
        max_diff_at: String::new(),
    };
    let mut max_diff = 0.0f64;
    let mut max_diff_at = String::new();
    let mut mismatches: Vec<String> = Vec::new();
    let mut seen_180 = false;
    let mut seen_183 = false;
    let mut seen_325 = false;
    // Corner-mark cage fix (docs/corner-marks.md): strict cases demoted
    // to PPX because alignment-only explicit marks intentionally change
    // their UV values (all carry sharps; ok/progress/rot/sing still pin).
    const CAGE_DEMOTED: &[i64] = &[
        2, 4, 21, 25, 43, 44, 45, 46, 61, 63, 66, 69, 76, 81, 90, 96, 123, 127, 129, 130, 136, 139,
        143, 144, 167, 172, 173, 177, 187, 188, 192, 193,
    ];
    let mut seen_cage: Vec<i64> = Vec::new();
    loop {
        let tag = c.word();
        if tag == "CASES" {
            let total = c.uint();
            assert_eq!(
                total,
                strict_cases + stats.cases,
                "CASES trailer disagrees with parsed count"
            );
            break;
        }
        let strict = match tag.as_str() {
            "CASE" => true,
            "PPX" => false,
            other => panic!("unexpected fixture tag: {other}"),
        };
        let id = c.int();
        c.expect("KIND");
        let kind = c.word();
        c.expect("NV");
        let nv = c.uint();
        c.expect("NT");
        let nt = c.uint();
        c.expect("SCALING");
        let scaling = c.num();
        c.expect("HARD");
        let hard = c.num();
        c.expect("ADAPT");
        let adapt = c.num();
        c.expect("ANISO");
        let aniso = c.num();
        c.expect("SIMP");
        let simp = c.int() != 0;
        c.expect("MAXPD");
        let maxpd = c.uint();
        c.expect("SYMAXIS");
        let symaxis = c.int();
        c.expect("SYMOFF");
        let symoff = c.num();
        c.expect("GUIDES");
        let n_guides = c.uint();
        c.expect("SHARPS");
        let n_sharps = c.uint();
        c.expect("DENSITY");
        let density_mode = c.int();
        c.expect("FIELDVEC");
        let field_mode = c.int();
        let case = format!("{} {id} ({kind})", if strict { "case" } else { "ppx" });

        let mut vertices = Vec::with_capacity(nv);
        for _ in 0..nv {
            c.expect("V");
            vertices.push(c.v3());
        }
        let mut triangles = Vec::with_capacity(nt);
        for _ in 0..nt {
            c.expect("T");
            let k = c.uint();
            let mut tri = Vec::with_capacity(k);
            for _ in 0..k {
                tri.push(c.uint());
            }
            triangles.push(tri);
        }
        let mut guides = Vec::with_capacity(n_guides);
        for _ in 0..n_guides {
            c.expect("GUIDE");
            let m = c.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(c.v3());
            }
            guides.push(line);
        }
        let mut sharps = Vec::with_capacity(n_sharps);
        for _ in 0..n_sharps {
            c.expect("SHARP");
            let m = c.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(c.v3());
            }
            sharps.push(line);
        }
        c.expect("RHO");
        let n_rho = c.uint();
        let mut rho = Vec::with_capacity(n_rho);
        for _ in 0..n_rho {
            rho.push(c.num());
        }
        let mut field_vecs = Vec::new();
        if field_mode != 0 {
            // Length is implicit (quad precedent: recompute, don't trust):
            // mode 2 = nt+1 (1 when nt == 0), else nt.
            let flen = if field_mode == 2 {
                if nt > 0 { nt + 1 } else { 1 }
            } else {
                nt
            };
            for _ in 0..flen {
                c.expect("F");
                field_vecs.push(c.v3());
            }
        }
        c.expect("PROG");
        let n_prog = c.uint();
        let mut expected_prog: Vec<(f32, String)> = Vec::with_capacity(n_prog);
        for _ in 0..n_prog {
            let f = c.frac();
            let a = c.word();
            expected_prog.push((f, a));
        }
        c.expect("RES");
        let expected_ok = c.int() != 0;

        // Tag rule (must match dumpCase): PPX iff soup-family input or
        // a listed straggler with matching identity. Asserted in both
        // directions, so a hand-edited fixture, a shifted ID, or a
        // drifted detector voids the oracle loudly instead of silently
        // weakening it (frame-lane FFX precedent).
        let listed_identity = match id {
            180 => {
                kind == "strip"
                    && nv == 16
                    && nt == 7
                    && scaling.to_bits() == 1.0f64.to_bits()
                    && hard.to_bits() == 90.0f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.0f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 0
                    && symoff.to_bits() == 0.72_f64.to_bits()
                    && n_guides == 1
                    && n_sharps == 3
                    && density_mode == 0
                    && field_mode == 0
            }
            183 => {
                kind == "saddle"
                    && nv == 25
                    && nt == 32
                    && scaling.to_bits() == 1.0f64.to_bits()
                    && hard.to_bits() == 135.0f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.0f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 4
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            325 => {
                kind == "tiny"
                    && nv == 4
                    && nt == 4
                    && scaling.to_bits() == 1.0f64.to_bits()
                    && hard.to_bits() == 90.0f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.0f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 0
                    && n_sharps == 0
                    && density_mode == 0
                    && field_mode == 0
            }
            // Corner-mark cage fix (docs/corner-marks.md): explicit-sharp
            // marks are alignment-only now, so these sharp-carrying cases
            // no longer match C++ UV values. PPX keeps the robustness pins
            // (ok/progress/rot/sing); values are report-only.
            2 => {
                kind == "sphere"
                    && nv == 12
                    && nt == 20
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 135f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 0.5f64.to_bits()
                    && simp
                    && maxpd == 8
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 1
                    && density_mode == 2
                    && field_mode == 0
            }
            4 => {
                kind == "sphere"
                    && nv == 20
                    && nt == 36
                    && scaling.to_bits() == 0.5f64.to_bits()
                    && hard.to_bits() == 75f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && !simp
                    && maxpd == 4
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 2
                    && field_mode == 0
            }
            21 => {
                kind == "fan"
                    && nv == 6
                    && nt == 5
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && simp
                    && maxpd == 10
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 3
                    && density_mode == 2
                    && field_mode == 3
            }
            25 => {
                kind == "grid"
                    && nv == 25
                    && nt == 32
                    && scaling.to_bits() == 0.75f64.to_bits()
                    && hard.to_bits() == 75f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && !simp
                    && maxpd == 8
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 2
                    && field_mode == 0
            }
            43 => {
                kind == "saddle"
                    && nv == 30
                    && nt == 40
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 45f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 8
                    && symaxis == -1
                    && n_guides == 4
                    && n_sharps == 3
                    && density_mode == 0
                    && field_mode == 0
            }
            44 => {
                kind == "sphere"
                    && nv == 38
                    && nt == 72
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 60f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 0.5f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 0
                    && symoff.to_bits() == 0.019f64.to_bits()
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 4
                    && field_mode == 0
            }
            45 => {
                kind == "sphere"
                    && nv == 22
                    && nt == 40
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.25f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 0
                    && symoff.to_bits() == 0.090_817_816_000_670_13_f64.to_bits()
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            46 => {
                kind == "grid"
                    && nv == 25
                    && nt == 32
                    && scaling.to_bits() == 0.5f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 2f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 3
                    && density_mode == 0
                    && field_mode == 0
            }
            61 => {
                kind == "grid"
                    && nv == 25
                    && nt == 32
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 135f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            63 => {
                kind == "saddle"
                    && nv == 12
                    && nt == 12
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 60f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 0f64.to_bits()
                    && simp
                    && maxpd == 1
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 2
                    && density_mode == 4
                    && field_mode == 0
            }
            66 => {
                kind == "grid"
                    && nv == 30
                    && nt == 40
                    && scaling.to_bits() == 0.75f64.to_bits()
                    && hard.to_bits() == 60f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            69 => {
                kind == "grid"
                    && nv == 24
                    && nt == 30
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 0f64.to_bits()
                    && simp
                    && maxpd == 8
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 2
                    && field_mode == 0
            }
            76 => {
                kind == "grid"
                    && nv == 10
                    && nt == 8
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 15f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 0f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 4
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            81 => {
                kind == "grid"
                    && nv == 25
                    && nt == 32
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && !simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            90 => {
                kind == "quad"
                    && nv == 4
                    && nt == 2
                    && scaling.to_bits() == 0.75f64.to_bits()
                    && hard.to_bits() == 180f64.to_bits()
                    && adapt.to_bits() == 0.75f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && !simp
                    && maxpd == 0
                    && symaxis == 2
                    && symoff.to_bits() == 0f64.to_bits()
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 3
            }
            96 => {
                kind == "sphere"
                    && nv == 14
                    && nt == 24
                    && scaling.to_bits() == 1.5f64.to_bits()
                    && hard.to_bits() == 135f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 0.5f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            123 => {
                kind == "saddle"
                    && nv == 20
                    && nt == 24
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 10f64.to_bits()
                    && adapt.to_bits() == 0.75f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 0
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 1
            }
            127 => {
                kind == "quad"
                    && nv == 4
                    && nt == 2
                    && scaling.to_bits() == 0.75f64.to_bits()
                    && hard.to_bits() == 135f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 12
                    && symaxis == -1
                    && n_guides == 0
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 3
            }
            129 => {
                kind == "grid"
                    && nv == 15
                    && nt == 16
                    && scaling.to_bits() == 1.5f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 0f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 0
                    && symoff.to_bits() == 0.777_f64.to_bits()
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            130 => {
                kind == "grid"
                    && nv == 12
                    && nt == 12
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 15f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            136 => {
                kind == "grid"
                    && nv == 12
                    && nt == 12
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 30f64.to_bits()
                    && adapt.to_bits() == 0.75f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            139 => {
                kind == "quad"
                    && nv == 4
                    && nt == 2
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 180f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 0f64.to_bits()
                    && !simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 3
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 3
            }
            143 => {
                kind == "sphere"
                    && nv == 47
                    && nt == 90
                    && scaling.to_bits() == 1f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            144 => {
                kind == "saddle"
                    && nv == 9
                    && nt == 8
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 0
                    && n_sharps == 4
                    && density_mode == 0
                    && field_mode == 0
            }
            167 => {
                kind == "grid"
                    && nv == 6
                    && nt == 4
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 10f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 1
                    && symoff.to_bits() == (-0.974_f64).to_bits()
                    && n_guides == 2
                    && n_sharps == 4
                    && density_mode == 4
                    && field_mode == 0
            }
            172 => {
                kind == "sphere"
                    && nv == 37
                    && nt == 70
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 60f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 2f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == 1
                    && symoff.to_bits() == 0f64.to_bits()
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 4
                    && field_mode == 0
            }
            173 => {
                kind == "sphere"
                    && nv == 37
                    && nt == 70
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 90f64.to_bits()
                    && adapt.to_bits() == 0.75f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 0
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            177 => {
                kind == "sphere"
                    && nv == 26
                    && nt == 48
                    && scaling.to_bits() == 0.5f64.to_bits()
                    && hard.to_bits() == 135f64.to_bits()
                    && adapt.to_bits() == 0f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && !simp
                    && maxpd == 1
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 0
                    && field_mode == 0
            }
            187 => {
                kind == "grid"
                    && nv == 12
                    && nt == 10
                    && scaling.to_bits() == 2f64.to_bits()
                    && hard.to_bits() == 75f64.to_bits()
                    && adapt.to_bits() == 1f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && !simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 3
                    && density_mode == 0
                    && field_mode == 0
            }
            188 => {
                kind == "fan"
                    && nv == 7
                    && nt == 6
                    && scaling.to_bits() == 0.75f64.to_bits()
                    && hard.to_bits() == 45f64.to_bits()
                    && adapt.to_bits() == 0.75f64.to_bits()
                    && aniso.to_bits() == 0.5f64.to_bits()
                    && !simp
                    && maxpd == 3
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 4
                    && density_mode == 2
                    && field_mode == 1
            }
            192 => {
                kind == "grid"
                    && nv == 12
                    && nt == 10
                    && scaling.to_bits() == 0.33_f64.to_bits()
                    && hard.to_bits() == 180f64.to_bits()
                    && adapt.to_bits() == 0.5f64.to_bits()
                    && aniso.to_bits() == 1f64.to_bits()
                    && simp
                    && maxpd == 6
                    && symaxis == -1
                    && n_guides == 1
                    && n_sharps == 1
                    && density_mode == 4
                    && field_mode == 3
            }
            193 => {
                kind == "saddle"
                    && nv == 12
                    && nt == 12
                    && scaling.to_bits() == 0.25f64.to_bits()
                    && hard.to_bits() == 60f64.to_bits()
                    && adapt.to_bits() == 0.25f64.to_bits()
                    && aniso.to_bits() == 1.5f64.to_bits()
                    && !simp
                    && maxpd == 0
                    && symaxis == -1
                    && n_guides == 2
                    && n_sharps == 2
                    && density_mode == 0
                    && field_mode == 0
            }
            _ => false,
        };
        if (id == 180 || id == 183 || id == 325 || CAGE_DEMOTED.contains(&id)) && !listed_identity {
            mismatches.push(format!("{case}: listed PPX identity drifted"));
        }
        if id == 180 {
            seen_180 = true;
        }
        if id == 183 {
            seen_183 = true;
        }
        if id == 325 {
            seen_325 = true;
        }
        if CAGE_DEMOTED.contains(&id) {
            seen_cage.push(id);
        }
        let expected_robust = kind == "soup" || listed_identity;
        if strict == expected_robust {
            mismatches.push(format!(
                "{case}: tag inconsistent (strict={strict} kind={kind} listed={listed_identity})"
            ));
        }

        // Replay with a recording progress handler (Arc: the Box<dyn Fn>
        // alias is 'static, so the closure cannot borrow locals).
        let events: Arc<Mutex<Vec<(f32, String)>>> = Arc::new(Mutex::new(Vec::new()));
        let handler: ProgressHandler = Box::new({
            let events = events.clone();
            move |fraction: f32, name: &str| {
                events
                    .lock()
                    .unwrap()
                    .push((fraction, prog_alias(name).to_string()));
            }
        });
        let mut parameterizer = Parameterizer::new(
            &vertices,
            &triangles,
            if field_mode == 0 {
                None
            } else {
                Some(&field_vecs)
            },
        );
        parameterizer.set_scaling(scaling);
        parameterizer.set_gradient_adaptivity(adapt);
        parameterizer.set_sharp_edge_degrees(hard);
        parameterizer.set_anisotropy(aniso);
        parameterizer.set_singularity_simplification(simp);
        parameterizer.set_maximum_singularity_pair_distance(maxpd);
        if symaxis >= 0 {
            parameterizer.set_symmetry_plane(SymmetryPlane {
                axis: symaxis as i32,
                offset: symoff,
                score: 0.0,
            });
        }
        // Mirror the dump's setter/nullptr rules exactly (id parity picks
        // the sharp alias, exercising both Rust setters).
        let sharps_arg: Option<&[Vec<Vector3>]> = if sharps.is_empty() && id % 3 != 0 {
            None
        } else {
            Some(&sharps)
        };
        if id % 2 == 0 {
            parameterizer.set_feature_polylines(sharps_arg);
        } else {
            parameterizer.set_sharp_polylines(sharps_arg);
        }
        if !guides.is_empty() || id % 3 == 0 {
            parameterizer.set_guide_polylines(Some(&guides));
        }
        if density_mode != 0 {
            parameterizer.set_density_field(rho.clone());
        }
        parameterizer.set_progress_handler(handler);
        let got_ok = parameterizer.parameterize();
        if strict {
            strict_cases += 1;
        } else {
            stats.cases += 1;
        }
        if got_ok != expected_ok {
            // Robustness rule (both sections): the port must solve
            // everything C++ solves; solving more is fine.
            if expected_ok || strict {
                mismatches.push(format!(
                    "{case}: ok flag diverged (rust={got_ok} cpp={expected_ok})"
                ));
            }
            if expected_ok {
                consume_outputs(&mut c);
            }
            continue;
        }
        // Progress sequence: alias-exact, fractions bitwise (pins the
        // taken branches and the MILS rounding iteration count, and
        // proves the f32 FMA mirrors). Asserted in both sections:
        // backend noise never moved it in the quad lane.
        let got_prog = events.lock().unwrap().clone();
        if got_prog.len() != expected_prog.len() {
            mismatches.push(format!(
                "{case}: progress count diverged (rust={} cpp={})",
                got_prog.len(),
                expected_prog.len()
            ));
        } else {
            for (i, ((gf, ga), (ef, ea))) in got_prog.iter().zip(expected_prog.iter()).enumerate() {
                if ga != ea {
                    mismatches.push(format!(
                        "{case}: progress[{i}] alias diverged (rust={ga} cpp={ea})"
                    ));
                    break;
                }
                if gf.to_bits() != ef.to_bits() {
                    mismatches.push(format!(
                        "{case}: progress[{i}] fraction diverged (rust={gf} cpp={ef})"
                    ));
                    break;
                }
            }
        }
        if !expected_ok {
            continue;
        }
        if strict {
            strict_ok += 1;
        } else {
            stats.both_ok += 1;
        }
        let mut case_agrees = true;

        // Structural invariants (both sections): the kept originals agree
        // with the taken UVs, singular positions derive from indices, and
        // a second take returns None.
        let original_len = parameterizer.original_triangle_uvs().len();
        if original_len != nt {
            mismatches.push(format!(
                "{case}: original face count diverged (rust={original_len} cpp={nt})"
            ));
        }
        let taken = parameterizer.take_triangle_uvs().unwrap();
        if taken.len() != nt {
            mismatches.push(format!(
                "{case}: taken face count diverged (rust={} cpp={nt})",
                taken.len()
            ));
        }
        if parameterizer.original_triangle_uvs().len() != taken.len() {
            mismatches.push(format!("{case}: original/taken length skew"));
        } else {
            for (f, (o_tri, t_tri)) in parameterizer
                .original_triangle_uvs()
                .iter()
                .zip(taken.iter())
                .enumerate()
            {
                if o_tri.len() != t_tri.len() {
                    mismatches.push(format!("{case}: face[{f}] corner count skew"));
                    break;
                }
                for (l, (o, t)) in o_tri.iter().zip(t_tri.iter()).enumerate() {
                    if o.x().to_bits() != t.x().to_bits() || o.y().to_bits() != t.y().to_bits() {
                        mismatches.push(format!("{case}: original[{f}][{l}] != taken (bitwise)"));
                        break;
                    }
                }
            }
        }
        if parameterizer.take_triangle_uvs().is_some() {
            mismatches.push(format!("{case}: second take returned Some"));
        }
        let sing_idx = parameterizer.singular_vertex_indices().to_vec();
        let sing_pos = parameterizer.singular_vertex_positions().to_vec();
        if sing_idx.len() != sing_pos.len() {
            mismatches.push(format!("{case}: singular index/position length skew"));
        } else {
            for (i, &v) in sing_idx.iter().enumerate() {
                if v >= vertices.len() || sing_pos[i] != vertices[v] {
                    mismatches.push(format!("{case}: singular position[{i}] not vertices[{v}]"));
                    break;
                }
            }
        }

        c.expect("UV");
        if taken.len() != nt {
            // Already reported above; still consume to stay in sync.
            for _ in 0..nt * 3 * 2 {
                c.num();
            }
        } else {
            for f in 0..nt {
                for l in 0..3 {
                    for coord in 0..2 {
                        let expect = c.num();
                        let v = if coord == 0 {
                            taken[f][l].x()
                        } else {
                            taken[f][l].y()
                        };
                        let d = (v - expect).abs();
                        // NaN is never OK: both sides solve the same
                        // finite system, so a NaN is a logic bug, not
                        // noise (asserted in both sections via the
                        // structural path below).
                        if v.is_nan() != expect.is_nan() {
                            mismatches.push(format!(
                                "{case}: uv[{f}][{l}][{coord}] NaN skew (rust={v} cpp={expect})"
                            ));
                            continue;
                        }
                        if v.is_nan() {
                            continue;
                        }
                        let tol = TOL * expect.abs().max(1.0);
                        if strict {
                            // Scale-aware max: UVs reach 1e14 on extreme
                            // scalings, so the summary tracks
                            // d/max(1,|e|) like the assert.
                            let rel = d / expect.abs().max(1.0);
                            if rel > max_diff {
                                max_diff = rel;
                                max_diff_at = format!(
                                    "{case} uv[{f}][{l}][{coord}] v={v:.6e} e={expect:.6e}"
                                );
                            }
                            if d > tol {
                                mismatches.push(format!(
                                    "{case}: uv[{f}][{l}][{coord}] diverged (rust={v} cpp={expect} diff={d:.3e} tol={tol:.3e})"
                                ));
                            }
                        } else {
                            if d > stats.max_diff {
                                stats.max_diff = d;
                                stats.max_diff_at = format!(
                                    "{case} uv[{f}][{l}][{coord}] v={v:.6e} e={expect:.6e}"
                                );
                            }
                            if d > tol {
                                case_agrees = false;
                            }
                        }
                    }
                }
            }
        }
        if !strict && case_agrees {
            stats.value_agree += 1;
        }
        c.expect("SING");
        let n_sing = c.uint();
        let mut expected_sing = Vec::with_capacity(n_sing);
        for _ in 0..n_sing {
            expected_sing.push(c.uint());
        }
        if sing_idx != expected_sing {
            mismatches.push(format!(
                "{case}: singular vertices diverged (rust={sing_idx:?} cpp={expected_sing:?})"
            ));
        }
    }
    // Timing lines are informational only; the timing harness regenerates
    // the same mesh and prints its own ms.
    let mut t_lines = 0;
    let mut t_faces = 0usize;
    let mut t_checksum = 0.0f64;
    while c.pos < c.toks.len() {
        c.expect("T");
        let kind = c.word();
        assert_eq!(kind, "pp", "bad T line");
        let ok_tok = c.word();
        assert_eq!(ok_tok, "ok=1", "timing case must solve on the C++ side");
        c.word(); // ms=...
        let faces_tok = c.word();
        t_faces = faces_tok
            .strip_prefix("faces=")
            .expect("bad faces token")
            .parse()
            .expect("bad faces");
        c.word(); // sing=...
        let checksum_tok = c.word();
        t_checksum = checksum_tok
            .strip_prefix("checksum=")
            .expect("bad checksum token")
            .parse()
            .expect("bad checksum");
        t_lines += 1;
    }
    eprintln!(
        "differential replay: {strict_cases} strict ({strict_ok} ok), max uv rel-diff = {max_diff:.3e} at {max_diff_at}"
    );
    eprintln!(
        "PPX (robustness-only): {} cases, {} both-ok, {} value-agree, max |diff| = {:.3e} at {}",
        stats.cases, stats.both_ok, stats.value_agree, stats.max_diff, stats.max_diff_at
    );
    eprintln!("timing mesh: {t_faces} faces, C++ checksum {t_checksum:.17e}");
    for m in mismatches.iter().take(20) {
        eprintln!("MISMATCH: {m}");
    }
    assert!(strict_cases >= 200, "expected 200+ strict cases");
    assert!(
        seen_180 && seen_183 && seen_325,
        "listed PPX cases missing from fixture (180: {seen_180}, 183: {seen_183}, 325: {seen_325})"
    );
    seen_cage.sort_unstable();
    seen_cage.dedup();
    assert_eq!(
        seen_cage, CAGE_DEMOTED,
        "cage-demoted PPX cases missing or shifted in fixture"
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        max_diff <= TOL,
        "strict max rel-diff {max_diff:.3e} exceeds {TOL}"
    );
    assert!(
        mismatches.is_empty(),
        "{} mismatches (first above)",
        mismatches.len()
    );
}

/// Skip expected outputs after an ok-flag divergence to keep the cursor in
/// sync (scans to the next case tag; all output payloads are numeric).
fn consume_outputs(c: &mut Cur) {
    let from = c.pos;
    while c.pos < c.toks.len()
        && c.toks[c.pos] != "CASE"
        && c.toks[c.pos] != "PPX"
        && c.toks[c.pos] != "CASES"
    {
        c.pos += 1;
    }
    eprintln!(
        "ok diverged, skipping {} tokens to stay in sync",
        c.pos - from
    );
}
