// Differential oracle replay for the positionkey port: parses
// tests/fixtures/positionkey_diff.txt (generated by the C++
// positionkey_diff_dump tool) and replays every case. Positions compare
// BITWISE (%.17g round-trips exactly, incl. the -0.0 sign bit) and the
// full pairwise ==/</> matrix must match exactly — the port is one IEEE
// multiply plus a truncation per axis, so every op is deterministic.
// The replay also pins the Rust-only `Ord` impl to agree with `<`/`==`
// on every pair (downstream uses this as an ordered-map key).
use retopo_core::position_key::PositionKey;
use retopo_core::vector3::Vector3;
use std::cmp::Ordering;

const FIXTURE: &str = include_str!("../../../tests/fixtures/positionkey_diff.txt");

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn flag(&mut self) -> bool {
        match self.word().as_str() {
            "1" => true,
            "0" => false,
            other => panic!("bad flag token: {other}"),
        }
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn v3(&mut self) -> Vector3 {
        Vector3::new(self.num(), self.num(), self.num())
    }
}

fn check_bits(case: &str, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    assert!(
        got.to_bits() == expect.to_bits(),
        "{case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

fn check_flag(case: &str, what: &str, got: bool, c: &mut Cur) {
    let expect = c.flag();
    assert_eq!(got, expect, "{case} {what}: rust={got} cpp={expect}");
}

#[test]
fn position_key_differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("PKDIFF1");
    let mut compared = 0usize;
    let (mut kn, mut an) = (0, 0);
    loop {
        if c.pos >= c.toks.len() {
            break;
        }
        let tag = c.word();
        match tag.as_str() {
            "K" | "A" => {
                if tag == "K" {
                    kn += 1;
                } else {
                    an += 1;
                }
                let case = format!("{tag} case {}", if tag == "K" { kn } else { an });
                let pts = [c.v3(), c.v3(), c.v3(), c.v3()];
                let keys = [
                    PositionKey::new(pts[0].x(), pts[0].y(), pts[0].z()),
                    PositionKey::new(pts[1].x(), pts[1].y(), pts[1].z()),
                    PositionKey::new(pts[2].x(), pts[2].y(), pts[2].z()),
                    PositionKey::new(pts[3].x(), pts[3].y(), pts[3].z()),
                ];
                // from_vector must build the identical key (C++ ctor
                // delegation); checked against the same expectations.
                let via_vec = [
                    PositionKey::from_vector(&pts[0]),
                    PositionKey::from_vector(&pts[1]),
                    PositionKey::from_vector(&pts[2]),
                    PositionKey::from_vector(&pts[3]),
                ];
                c.expect("r");
                for (i, k) in keys.iter().enumerate() {
                    let p = k.position();
                    check_bits(&case, &format!("pos[{i}].x"), p.x(), &mut c, &mut compared);
                    check_bits(&case, &format!("pos[{i}].y"), p.y(), &mut c, &mut compared);
                    check_bits(&case, &format!("pos[{i}].z"), p.z(), &mut c, &mut compared);
                    assert_eq!(
                        via_vec[i], *k,
                        "{case} from_vector/new mismatch at point {i}"
                    );
                    let q = via_vec[i].position();
                    assert!(
                        q.x().to_bits() == p.x().to_bits()
                            && q.y().to_bits() == p.y().to_bits()
                            && q.z().to_bits() == p.z().to_bits(),
                        "{case} from_vector position mismatch at point {i}"
                    );
                }
                for i in 0..4 {
                    for j in (i + 1)..4 {
                        let pair = format!("pair[{i},{j}]");
                        check_flag(&case, &format!("{pair} eq"), keys[i] == keys[j], &mut c);
                        check_flag(&case, &format!("{pair} lt"), keys[i] < keys[j], &mut c);
                        check_flag(&case, &format!("{pair} gt"), keys[j] < keys[i], &mut c);
                        // Rust-only Ord must agree with ==/</> on every pair.
                        let ord = keys[i].cmp(&keys[j]);
                        let expect_ord = if keys[i] == keys[j] {
                            Ordering::Equal
                        } else if keys[i] < keys[j] {
                            Ordering::Less
                        } else {
                            assert!(keys[j] < keys[i], "{case} {pair}: trichotomy violated");
                            Ordering::Greater
                        };
                        assert_eq!(ord, expect_ord, "{case} {pair}: Ord disagrees");
                        assert_eq!(
                            keys[i].partial_cmp(&keys[j]),
                            Some(expect_ord),
                            "{case} {pair}: PartialOrd disagrees"
                        );
                    }
                }
            }
            "T" => {
                // Timing lines are informational; the timing test compares
                // the sink. Format: `T pk ms=%.3f sink=%.17g`.
                assert_eq!(c.word(), "pk");
                c.word();
                c.word();
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(kn, 200, "expected 200 K cases");
    assert_eq!(an, 51, "expected 51 adversarial cases");
    eprintln!(
        "positionkey replay: {kn} K + {an} adversarial, {compared} doubles bitwise-equal, 0 mismatches"
    );
}
