// Differential oracle replay: parses tests/fixtures/quadparam_diff.txt
// (generated by the C++ quadparam_diff_dump tool), re-runs every case with
// the Rust port, and asserts the port matches the C++ implementation.
//
// Two sections, mirroring the solvers' CLS/CLSX split:
// - CASE (strict): same ok flag, same progress-event sequence (alias +
//   bitwise f32 fraction, which pins the MILS rounding iteration count),
//   same corner rotations, same singular vertices, UV/field values within
//   scale-aware 1e-6.
// - QPX (robustness-only): non-manifold random soup (not
//   downstream-plausible; ill-conditioned covers by construction) plus
//   three manifold stragglers with a demonstrated backend-noise mechanism
//   (see the dump tool). The port must match every structural fact and
//   solve everything C++ solves; value agreement is reported, not
//   asserted: backend (Eigen-vs-faer) noise in the curl correction feeds
//   the cover and exceeds 1e-6 there, or flips an integer rounding cliff.
use retopo_core::progress::ProgressHandler;
use retopo_core::quad_parameterizer::{DipoleConfig, QuadParameterizer};
use retopo_core::vector3::Vector3;
use std::sync::{Arc, Mutex};

const FIXTURE: &str = include_str!("../../../tests/fixtures/quadparam_diff.txt");
const TOL: f64 = 1e-6;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn int(&mut self) -> i64 {
        self.word().parse().expect("bad int")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn frac(&mut self) -> f32 {
        self.word().parse().expect("bad f32")
    }
    fn v3(&mut self) -> Vector3 {
        let x = self.num();
        let y = self.num();
        let z = self.num();
        Vector3::new(x, y, z)
    }
}

fn prog_alias(name: &str) -> &'static str {
    match name {
        "Initializing cover field" => "INIT",
        "Smoothing cross field" => "SMOOTH",
        "Computing corner rotations" => "ROTC",
        "Correcting field curl" => "CURL",
        "Building cover system" => "BUILD",
        "Eliminating cover constraints" => "ELIM",
        "Rounding cover to integers" => "ROUND",
        "Building cover uvs" => "UVS",
        _ => "UNKNOWN",
    }
}

struct QpxStats {
    cases: usize,
    both_ok: usize,
    value_agree: usize,
    max_diff: f64,
    max_diff_at: String,
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("QPDIFF1");
    let mut strict_cases = 0usize;
    let mut strict_ok = 0usize;
    let mut stats = QpxStats {
        cases: 0,
        both_ok: 0,
        value_agree: 0,
        max_diff: 0.0,
        max_diff_at: String::new(),
    };
    let mut max_diff = 0.0f64;
    let mut max_diff_at = String::new();
    let mut max_field = 0.0f64;
    let mut max_field_at = String::new();
    let mut mismatches: Vec<String> = Vec::new();
    loop {
        let tag = c.word();
        if tag == "CASES" {
            let total = c.uint();
            assert_eq!(
                total,
                strict_cases + stats.cases,
                "CASES trailer disagrees with parsed count"
            );
            break;
        }
        let strict = match tag.as_str() {
            "CASE" => true,
            "QPX" => false,
            other => panic!("unexpected fixture tag: {other}"),
        };
        let id = c.int();
        c.expect("KIND");
        let kind = c.word();
        c.expect("NV");
        let nv = c.uint();
        c.expect("NT");
        let nt = c.uint();
        c.expect("SCALING");
        let scaling = c.num();
        c.expect("HARD");
        let hard = c.num();
        c.expect("GUIDANCE");
        let guidance_mode = c.int();
        c.expect("FS");
        let fs_mode = c.int();
        c.expect("FSDIR");
        let fs_dir = c.int();
        c.expect("SHARPS");
        let n_sharps = c.uint();
        let case = format!("{} {id} ({kind})", if strict { "case" } else { "qpx" });

        let mut vertices = Vec::with_capacity(nv);
        for _ in 0..nv {
            c.expect("V");
            vertices.push(c.v3());
        }
        let mut triangles = Vec::with_capacity(nt);
        for _ in 0..nt {
            c.expect("T");
            let k = c.uint();
            let mut tri = Vec::with_capacity(k);
            for _ in 0..k {
                tri.push(c.uint());
            }
            triangles.push(tri);
        }
        let mut guidance = Vec::new();
        if guidance_mode != 0 {
            // Guidance length is implicit: nt, except the wrong-size modes
            // (4 = nt+1, 5 = 1). Recompute instead of trusting the dump.
            let glen = if guidance_mode == 4 {
                nt + 1
            } else if guidance_mode == 5 {
                1
            } else {
                nt
            };
            for _ in 0..glen {
                c.expect("G");
                guidance.push(c.v3());
            }
        }
        let mut face_scaling = Vec::new();
        if fs_mode != 0 {
            c.expect("FS");
            let n = c.uint();
            for _ in 0..n {
                face_scaling.push(c.num());
            }
        }
        let mut face_scaling_u = Vec::new();
        let mut face_scaling_v = Vec::new();
        if fs_dir == 1 || fs_dir == 2 || fs_dir == 3 || fs_dir == 4 {
            c.expect("FSU");
            let n = c.uint();
            for _ in 0..n {
                face_scaling_u.push(c.num());
            }
        }
        if fs_dir == 1 || fs_dir == 3 || fs_dir == 4 {
            c.expect("FSV");
            let n = c.uint();
            for _ in 0..n {
                face_scaling_v.push(c.num());
            }
        }
        let mut sharps: Vec<Vec<Vector3>> = Vec::with_capacity(n_sharps);
        for _ in 0..n_sharps {
            c.expect("SHARP");
            let m = c.uint();
            let mut line = Vec::with_capacity(m);
            for _ in 0..m {
                line.push(c.v3());
            }
            sharps.push(line);
        }
        c.expect("PROG");
        let n_prog = c.uint();
        let mut expected_prog: Vec<(f32, String)> = Vec::with_capacity(n_prog);
        for _ in 0..n_prog {
            let f = c.frac();
            let a = c.word();
            expected_prog.push((f, a));
        }
        c.expect("RES");
        let expected_ok = c.int() != 0;

        // Replay with a recording progress handler (Arc: the Box<dyn Fn>
        // alias is 'static, so the closure cannot borrow locals).
        let events: Arc<Mutex<Vec<(f32, String)>>> = Arc::new(Mutex::new(Vec::new()));
        let handler: ProgressHandler = Box::new({
            let events = events.clone();
            move |fraction: f32, name: &str| {
                events
                    .lock()
                    .unwrap()
                    .push((fraction, prog_alias(name).to_string()));
            }
        });
        let guidance_arg: &[Vector3] = if guidance_mode == 0 { &[] } else { &guidance };
        let fs_arg: &[f64] = if fs_mode == 0 { &[] } else { &face_scaling };
        let fsu_arg: &[f64] = if fs_dir == 1 || fs_dir == 2 || fs_dir == 3 || fs_dir == 4 {
            &face_scaling_u
        } else {
            &[]
        };
        let fsv_arg: &[f64] = if fs_dir == 1 || fs_dir == 3 || fs_dir == 4 {
            &face_scaling_v
        } else {
            &[]
        };
        let sharps_arg: Option<&[Vec<Vector3>]> = if sharps.is_empty() {
            None
        } else {
            Some(&sharps)
        };
        let got = QuadParameterizer::parameterize(
            &vertices,
            &triangles,
            guidance_arg,
            scaling,
            hard,
            fs_arg,
            fsu_arg,
            fsv_arg,
            Some(&handler),
            sharps_arg,
            &[],
            // Parity tier: the C++ has no dipoles, so the differential
            // oracle pins the no-dipole path explicitly.
            DipoleConfig::off(),
        );
        if strict {
            strict_cases += 1;
        } else {
            stats.cases += 1;
        }
        if got.is_some() != expected_ok {
            // Robustness rule (both sections): the port must solve
            // everything C++ solves; solving more is fine.
            if expected_ok || strict {
                mismatches.push(format!(
                    "{case}: ok flag diverged (rust={} cpp={expected_ok})",
                    got.is_some()
                ));
            }
            if expected_ok {
                consume_outputs(&mut c);
            }
            continue;
        }
        // Progress sequence: alias-exact, fractions bitwise (pins the MILS
        // rounding iteration count and proves the f32 FMA mirrors). Asserted
        // in both sections: backend noise never moved it.
        let got_prog = events.lock().unwrap().clone();
        if got_prog.len() != expected_prog.len() {
            mismatches.push(format!(
                "{case}: progress count diverged (rust={} cpp={})",
                got_prog.len(),
                expected_prog.len()
            ));
        } else {
            for (i, ((gf, ga), (ef, ea))) in got_prog.iter().zip(expected_prog.iter()).enumerate() {
                if ga != ea {
                    mismatches.push(format!(
                        "{case}: progress[{i}] alias diverged (rust={ga} cpp={ea})"
                    ));
                    break;
                }
                if gf.to_bits() != ef.to_bits() {
                    mismatches.push(format!(
                        "{case}: progress[{i}] fraction diverged (rust={gf} cpp={ef})"
                    ));
                    break;
                }
            }
        }
        if !expected_ok {
            continue;
        }
        if strict {
            strict_ok += 1;
        } else {
            stats.both_ok += 1;
        }
        let result = got.unwrap();
        let mut case_agrees = true;

        c.expect("UV");
        for f in 0..nt {
            for l in 0..3 {
                for coord in 0..2 {
                    let expect = c.num();
                    let v = if coord == 0 {
                        result.triangle_uvs[f][l].x()
                    } else {
                        result.triangle_uvs[f][l].y()
                    };
                    let d = (v - expect).abs();
                    let tol = TOL * expect.abs().max(1.0);
                    if strict {
                        // Scale-aware max: UVs reach 1e14 on extreme scalings,
                        // so the summary tracks d/max(1,|e|) like the assert.
                        let rel = d / expect.abs().max(1.0);
                        if rel > max_diff {
                            max_diff = rel;
                            max_diff_at =
                                format!("{case} uv[{f}][{l}][{coord}] v={v:.6e} e={expect:.6e}");
                        }
                        if d > tol {
                            mismatches.push(format!(
                                "{case}: uv[{f}][{l}][{coord}] diverged (rust={v} cpp={expect} diff={d:.3e} tol={tol:.3e})"
                            ));
                        }
                    } else {
                        if d > stats.max_diff {
                            stats.max_diff = d;
                            stats.max_diff_at =
                                format!("{case} uv[{f}][{l}][{coord}] v={v:.6e} e={expect:.6e}");
                        }
                        if d > tol {
                            case_agrees = false;
                        }
                    }
                }
            }
        }
        c.expect("FIELD");
        for f in 0..nt {
            let expect = c.v3();
            let got_v = result.field[f];
            for (coord, (g, e)) in [
                (got_v.x(), expect.x()),
                (got_v.y(), expect.y()),
                (got_v.z(), expect.z()),
            ]
            .into_iter()
            .enumerate()
            {
                let d = (g - e).abs();
                let tol = TOL * e.abs().max(1.0);
                if strict {
                    if d > max_field {
                        max_field = d;
                        max_field_at = format!("{case} field[{f}][{coord}]");
                    }
                    if d > tol {
                        mismatches.push(format!(
                            "{case}: field[{f}][{coord}] diverged (rust={g} cpp={e} diff={d:.3e} tol={tol:.3e})"
                        ));
                    }
                } else {
                    if d > stats.max_diff {
                        stats.max_diff = d;
                        stats.max_diff_at =
                            format!("{case} field[{f}][{coord}] g={g:.6e} e={e:.6e}");
                    }
                    if d > tol {
                        case_agrees = false;
                    }
                }
            }
        }
        if !strict && case_agrees {
            stats.value_agree += 1;
        }
        c.expect("ROT");
        let n_rot = c.uint();
        if result.corner_rotations.len() != n_rot {
            mismatches.push(format!(
                "{case}: rotation count diverged (rust={} cpp={n_rot})",
                result.corner_rotations.len()
            ));
            for _ in 0..n_rot {
                c.int();
            }
        } else {
            for (i, r) in result.corner_rotations.iter().enumerate() {
                let expect = c.int() as i32;
                if *r != expect {
                    mismatches.push(format!(
                        "{case}: rotation[{i}] diverged (rust={r} cpp={expect})"
                    ));
                    for _ in i + 1..n_rot {
                        c.int();
                    }
                    break;
                }
            }
        }
        c.expect("SING");
        let n_sing = c.uint();
        let mut expected_sing = Vec::with_capacity(n_sing);
        for _ in 0..n_sing {
            expected_sing.push(c.uint());
        }
        if result.singular_vertices != expected_sing {
            mismatches.push(format!(
                "{case}: singular vertices diverged (rust={:?} cpp={expected_sing:?})",
                result.singular_vertices
            ));
        }
    }
    // Timing lines are informational only; the timing harness regenerates
    // the same mesh and prints its own ms.
    let mut t_lines = 0;
    while c.pos < c.toks.len() {
        c.expect("T");
        let kind = c.word();
        assert_eq!(kind, "qp", "bad T line");
        for _ in 0..4 {
            c.word();
        }
        t_lines += 1;
    }
    eprintln!(
        "differential replay: {strict_cases} strict ({strict_ok} ok), max uv rel-diff = {max_diff:.3e} at {max_diff_at}, max |field diff| = {max_field:.3e} at {max_field_at}"
    );
    eprintln!(
        "QPX (robustness-only): {} cases, {} both-ok, {} value-agree, max |diff| = {:.3e} at {}",
        stats.cases, stats.both_ok, stats.value_agree, stats.max_diff, stats.max_diff_at
    );
    for m in mismatches.iter().take(20) {
        eprintln!("MISMATCH: {m}");
    }
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        max_diff <= TOL,
        "strict max rel-diff {max_diff:.3e} exceeds {TOL}"
    );
    assert!(
        max_field <= TOL,
        "strict max field diff {max_field:.3e} exceeds {TOL}"
    );
    assert!(
        mismatches.is_empty(),
        "{} mismatches (first above)",
        mismatches.len()
    );
}

/// Skip expected outputs after an ok-flag divergence to keep the cursor in
/// sync (scans to the next case tag; all output payloads are numeric).
fn consume_outputs(c: &mut Cur) {
    let from = c.pos;
    while c.pos < c.toks.len()
        && c.toks[c.pos] != "CASE"
        && c.toks[c.pos] != "QPX"
        && c.toks[c.pos] != "CASES"
    {
        c.pos += 1;
    }
    eprintln!(
        "ok diverged, skipping {} tokens to stay in sync",
        c.pos - from
    );
}
