// Differential oracle replay: parses
// tests/fixtures/singularitysimplifier_diff.txt (generated by the C++
// singularitysimplifier_diff_dump tool), rebuilds every mesh + face field
// with the Rust port, and asserts the port matches the C++ implementation:
// exact (E) cases assert counts, per-vertex input/output charges, and the
// full output field bitwise (zero mismatches allowed); structural (S)
// cases assert the order-free prefix (input charges, before-count) exactly
// plus output self-consistency (after == popcount, charges in range, all
// coordinates finite). The E/S split is decided by input/output features
// (before-count, monotonicity), and the replay re-checks the E
// preconditions on the Rust side, so generator drift fails loudly.
use retopo_core::singularity_simplifier::SingularitySimplifier;
use retopo_core::surface_mesh::SurfaceMesh;
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/singularitysimplifier_diff.txt");
const EXACT_CASES: usize = 202;
const STRUCT_CASES: usize = 21;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn int(&mut self) -> i32 {
        self.word().parse().expect("bad i32")
    }
}

fn check_bits(case: usize, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    let same = if got.is_nan() && expect.is_nan() {
        got.is_sign_negative() == expect.is_sign_negative()
    } else {
        got.to_bits() == expect.to_bits()
    };
    assert!(
        same,
        "case {case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("SINGSIMP1");
    let mut exact = 0usize;
    let mut structural = 0usize;
    let mut cancelled_total = 0usize;
    let mut compared = 0usize;
    let mut t_lines = 0usize;
    while c.pos < c.toks.len() {
        let tag = c.word();
        match tag.as_str() {
            "CASE" => {
                let id = c.uint();
                let nv = c.uint();
                let nt = c.uint();
                let max_pair = c.uint();
                let sharp_deg: f64 = c.num();
                let class = c.word();
                assert!(class == "E" || class == "S", "case {id}: bad class {class}");
                let mut positions = Vec::with_capacity(nv);
                for _ in 0..nv {
                    c.expect("v");
                    positions.push(Vector3::new(c.num(), c.num(), c.num()));
                }
                let mut triangles = Vec::with_capacity(nt);
                for _ in 0..nt {
                    c.expect("t");
                    let k = c.uint();
                    let mut face = Vec::with_capacity(k);
                    for _ in 0..k {
                        face.push(c.uint());
                    }
                    triangles.push(face);
                }
                let mesh = SurfaceMesh::new(&positions, &triangles);
                c.expect("F");
                let nf = c.uint();
                assert_eq!(nf, mesh.face_count(), "case {id}: F arity");
                let mut field = Vec::with_capacity(nf);
                for _ in 0..nf {
                    field.push(Vector3::new(c.num(), c.num(), c.num()));
                }
                // Input charges use the uncached quarter-turn path on both
                // sides: order-free, hence exact in both classes.
                let (charges_before, before, after, cancelled, charges_after) = {
                    let mut simp = SingularitySimplifier::new(&mesh, &mut field);
                    simp.set_maximum_pair_distance(max_pair);
                    simp.set_sharp_edge_degrees(sharp_deg);
                    let charges_before = simp.vertex_charges();
                    simp.simplify();
                    (
                        charges_before,
                        simp.singularity_count_before(),
                        simp.singularity_count_after(),
                        simp.cancelled_pair_count(),
                        simp.vertex_charges(),
                    )
                };
                // The simplifier is dropped, so `field` holds the output.
                c.expect("R");
                let (e_before, e_after, e_cancelled) = (c.uint(), c.uint(), c.uint());
                assert_eq!(before, e_before, "case {id}: before");
                c.expect("CHI");
                assert_eq!(c.uint(), nv, "case {id}: CHI arity");
                for (v, &charge) in charges_before.iter().enumerate() {
                    assert_eq!(charge, c.int(), "case {id}: input charge {v}");
                }
                if class == "E" {
                    exact += 1;
                    // Tripwires: the exact section requires the
                    // insertion-sort regime (round-1 candidates < 24,
                    // implied by before <= 7) and sane dynamics.
                    assert!(
                        before <= 7,
                        "case {id}: exact-class tripwire before={before} > 7"
                    );
                    assert!(
                        after <= before,
                        "case {id}: exact-class tripwire after={after} > before={before}"
                    );
                    assert_eq!(after, e_after, "case {id}: after");
                    assert_eq!(cancelled, e_cancelled, "case {id}: cancelled");
                    cancelled_total += cancelled;
                    c.expect("CH");
                    assert_eq!(c.uint(), nv, "case {id}: CH arity");
                    for (v, &charge) in charges_after.iter().enumerate() {
                        assert_eq!(charge, c.int(), "case {id}: output charge {v}");
                    }
                    c.expect("FO");
                    assert_eq!(c.uint(), nf, "case {id}: FO arity");
                    for (f, vec) in field.iter().enumerate() {
                        check_bits(
                            id,
                            &format!("output_field({f}).x"),
                            vec.x(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            id,
                            &format!("output_field({f}).y"),
                            vec.y(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            id,
                            &format!("output_field({f}).z"),
                            vec.z(),
                            &mut c,
                            &mut compared,
                        );
                    }
                } else {
                    structural += 1;
                    // Order-dependent tail: self-consistency only. Skip the
                    // C++ values (still parsed to advance the cursor).
                    let _ = (e_after, e_cancelled);
                    c.expect("CH");
                    let nch = c.uint();
                    assert_eq!(nch, nv, "case {id}: CH arity");
                    for _ in 0..nch {
                        c.int();
                    }
                    c.expect("FO");
                    let nfo = c.uint();
                    assert_eq!(nfo, nf, "case {id}: FO arity");
                    for _ in 0..3 * nfo {
                        c.num();
                    }
                    assert_eq!(
                        after,
                        charges_after.iter().filter(|&&x| x != 0).count(),
                        "case {id}: after == popcount"
                    );
                    for (v, &charge) in charges_after.iter().enumerate() {
                        assert!(
                            (0..4).contains(&charge),
                            "case {id}: output charge {v} = {charge} out of range"
                        );
                    }
                    for (f, vec) in field.iter().enumerate() {
                        assert!(
                            vec.x().is_finite() && vec.y().is_finite() && vec.z().is_finite(),
                            "case {id}: output field {f} non-finite"
                        );
                    }
                }
            }
            "T" => {
                // `T singsimp faces=.. before=.. after=.. cancelled=.. xsum=.. ms=..`:
                // informational only; the Rust timing test rebuilds the
                // same dipole grid and must reproduce xsum/counts bitwise.
                t_lines += 1;
                for _ in 0..7 {
                    c.word();
                }
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(exact, EXACT_CASES, "expected {EXACT_CASES} exact cases");
    assert_eq!(
        structural, STRUCT_CASES,
        "expected {STRUCT_CASES} structural cases"
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    eprintln!(
        "singsimp differential replay: {} exact + {} structural, {} output doubles bitwise, {} cancelled pairs, 0 mismatches",
        exact, structural, compared, cancelled_total
    );
}
