// Differential oracle replay: parses tests/fixtures/surfacemesh_diff.txt
// (generated by the C++ surfacemesh_diff_dump tool), rebuilds every mesh
// with the Rust port, and asserts the port matches the C++ implementation
// exactly: same counts, same opposite/adjacent/boundary tables, same
// corners-around-vertex lists, and — where every kept triangle is
// in-bounds — bitwise-identical average edge length, per-corner normal
// angles and edge vectors, and per-face normals. All float work goes
// through the ported Vector3 methods (FMA-exact) plus acos, so every
// double must be bit-identical; NaNs (not expected from finite inputs)
// compare by sign bit only, like the vector oracle.
use retopo_core::surface_mesh::SurfaceMesh;
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/surfacemesh_diff.txt");
const EDGE_CASES: usize = 27;
const RANDOM_CASES: usize = 220;

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad uint")
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn flag(&mut self) -> bool {
        match self.word().as_str() {
            "1" => true,
            "0" => false,
            other => panic!("bad flag token: {other}"),
        }
    }
    fn maybe_index(&mut self) -> usize {
        let w = self.word();
        if w == "N" {
            SurfaceMesh::NPOS
        } else {
            w.parse().expect("bad index")
        }
    }
}

fn check_bits(case: usize, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    let same = if got.is_nan() && expect.is_nan() {
        got.is_sign_negative() == expect.is_sign_negative()
    } else {
        got.to_bits() == expect.to_bits()
    };
    assert!(
        same,
        "case {case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

#[test]
fn differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("SMESH1");
    let mut cases = 0usize;
    let mut fp_cases = 0usize;
    let mut topo_only = 0usize;
    let mut t_lines = 0usize;
    let mut compared = 0usize;
    while c.pos < c.toks.len() {
        let tag = c.word();
        match tag.as_str() {
            "CASE" => {
                cases += 1;
                let nv = c.uint();
                let nt = c.uint();
                let mut positions = Vec::with_capacity(nv);
                for _ in 0..nv {
                    c.expect("v");
                    positions.push(Vector3::new(c.num(), c.num(), c.num()));
                }
                let mut triangles = Vec::with_capacity(nt);
                for _ in 0..nt {
                    c.expect("t");
                    let k = c.uint();
                    let mut face = Vec::with_capacity(k);
                    for _ in 0..k {
                        face.push(c.uint());
                    }
                    triangles.push(face);
                }
                let mesh = SurfaceMesh::new(&positions, &triangles);
                c.expect("R");
                let (evc, efc, ecc) = (c.uint(), c.uint(), c.uint());
                let fp = c.flag();
                assert_eq!(mesh.vertex_count(), evc, "case {cases}: vertex_count");
                assert_eq!(mesh.face_count(), efc, "case {cases}: face_count");
                assert_eq!(mesh.corner_count(), ecc, "case {cases}: corner_count");
                // Corner-index helpers are pure arithmetic over the counts;
                // spot-check them against the C++ formulas on every corner.
                for corner in 0..mesh.corner_count() {
                    assert_eq!(mesh.corner_face(corner), corner / 3);
                    assert_eq!(mesh.corner_local(corner), corner % 3);
                    assert_eq!(
                        mesh.next_corner(corner),
                        3 * (corner / 3) + (corner + 1) % 3
                    );
                    assert_eq!(
                        mesh.previous_corner(corner),
                        3 * (corner / 3) + (corner + 2) % 3
                    );
                }
                c.expect("OPP");
                assert_eq!(c.uint(), ecc, "case {cases}: OPP arity");
                for corner in 0..ecc {
                    let eo = c.maybe_index();
                    assert_eq!(
                        mesh.opposite_corner(corner),
                        eo,
                        "case {cases}: opposite_corner({corner})"
                    );
                }
                c.expect("ADJ");
                assert_eq!(c.uint(), ecc, "case {cases}: ADJ arity");
                for corner in 0..ecc {
                    let ea = c.maybe_index();
                    assert_eq!(
                        mesh.adjacent_face(corner),
                        ea,
                        "case {cases}: adjacent_face({corner})"
                    );
                }
                c.expect("BND");
                assert_eq!(c.uint(), ecc, "case {cases}: BND arity");
                for corner in 0..ecc {
                    let eb = c.flag();
                    assert_eq!(
                        mesh.is_boundary_corner(corner),
                        eb,
                        "case {cases}: is_boundary_corner({corner})"
                    );
                }
                c.expect("CAV");
                assert_eq!(c.uint(), evc, "case {cases}: CAV arity");
                for v in 0..evc {
                    c.expect("c");
                    let m = c.uint();
                    let mut expected = Vec::with_capacity(m);
                    for _ in 0..m {
                        expected.push(c.uint());
                    }
                    assert_eq!(
                        mesh.corners_around_vertex(v),
                        &expected,
                        "case {cases}: corners_around_vertex({v})"
                    );
                    for &corner in &expected {
                        assert_eq!(
                            mesh.corner_vertex(corner),
                            v,
                            "case {cases}: cav membership"
                        );
                    }
                }
                // Triangle accessor + position accessor round-trip.
                let mut kept = 0usize;
                for t in &triangles {
                    if t.len() == 3 {
                        assert_eq!(
                            mesh.triangle(kept),
                            &[t[0], t[1], t[2]],
                            "case {cases}: triangle({kept})"
                        );
                        kept += 1;
                    }
                }
                for (v, p) in positions.iter().enumerate() {
                    assert_eq!(
                        mesh.position(v).as_array(),
                        p.as_array(),
                        "case {cases}: position({v})"
                    );
                }
                if fp {
                    fp_cases += 1;
                    c.expect("AVG");
                    check_bits(
                        cases,
                        "average_edge_length",
                        mesh.average_edge_length(),
                        &mut c,
                        &mut compared,
                    );
                    c.expect("NANG");
                    assert_eq!(c.uint(), ecc, "case {cases}: NANG arity");
                    for corner in 0..ecc {
                        check_bits(
                            cases,
                            &format!("normal_angle({corner})"),
                            mesh.normal_angle(corner),
                            &mut c,
                            &mut compared,
                        );
                    }
                    c.expect("EDGE");
                    assert_eq!(c.uint(), ecc, "case {cases}: EDGE arity");
                    for corner in 0..ecc {
                        let e = mesh.edge_vector(corner);
                        check_bits(
                            cases,
                            &format!("edge_vector({corner}).x"),
                            e.x(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            cases,
                            &format!("edge_vector({corner}).y"),
                            e.y(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            cases,
                            &format!("edge_vector({corner}).z"),
                            e.z(),
                            &mut c,
                            &mut compared,
                        );
                    }
                    c.expect("FNORM");
                    assert_eq!(c.uint(), efc, "case {cases}: FNORM arity");
                    for f in 0..efc {
                        let n = mesh.face_normal(f);
                        check_bits(
                            cases,
                            &format!("face_normal({f}).x"),
                            n.x(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            cases,
                            &format!("face_normal({f}).y"),
                            n.y(),
                            &mut c,
                            &mut compared,
                        );
                        check_bits(
                            cases,
                            &format!("face_normal({f}).z"),
                            n.z(),
                            &mut c,
                            &mut compared,
                        );
                    }
                } else {
                    topo_only += 1;
                }
            }
            "T" => {
                // `T surfacemesh verts=.. faces=.. anglesum=.. avg=.. ms=..`:
                // informational only; the Rust timing test rebuilds the
                // same grid and must reproduce anglesum/avg bitwise.
                t_lines += 1;
                for _ in 0..6 {
                    c.word();
                }
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(
        cases,
        EDGE_CASES + RANDOM_CASES,
        "expected {} cases",
        EDGE_CASES + RANDOM_CASES
    );
    assert_eq!(t_lines, 3, "expected 3 timing lines");
    assert!(
        fp_cases > 100 && topo_only > 0,
        "unbalanced oracle: {fp_cases} float cases, {topo_only} topology-only"
    );
    eprintln!(
        "surfacemesh differential replay: {cases} cases ({fp_cases} float, {topo_only} topology-only), {compared} doubles bitwise, 0 mismatches"
    );
}
