//! Differential oracle replay for the symmetry port: parses
//! tests/fixtures/symmetry_diff.txt (generated by the Release C++
//! symmetry_diff_dump tool) and replays every case. Doubles compare
//! BITWISE (`%.17g` round-trips exactly; the port transcribes Clang's FMA
//! fusion of `2.0 * offset - x` with explicit `mul_add`, and every other
//! scalar op is a plain IEEE op, so every value must be bit-identical).
//! NaN inputs are excluded by construction (the C++ grid cell cast is UB
//! on out-of-range values); all fixture inputs are finite.
use retopo_core::symmetry::{Symmetry, SymmetryPlane};
use retopo_core::vector3::Vector3;

const FIXTURE: &str = include_str!("../../../tests/fixtures/symmetry_diff.txt");

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn uint(&mut self) -> usize {
        self.word().parse().expect("bad usize")
    }
    fn int(&mut self) -> i32 {
        self.word().parse().expect("bad i32")
    }
    fn v3(&mut self) -> Vector3 {
        Vector3::new(self.num(), self.num(), self.num())
    }
}

fn check_bits(case: &str, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    assert!(
        got.to_bits() == expect.to_bits(),
        "{case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

fn check_v3(case: &str, what: &str, got: &Vector3, c: &mut Cur, compared: &mut usize) {
    check_bits(case, &format!("{what}.x"), got.x(), c, compared);
    check_bits(case, &format!("{what}.y"), got.y(), c, compared);
    check_bits(case, &format!("{what}.z"), got.z(), c, compared);
}

fn check_plane(case: &str, what: &str, got: &SymmetryPlane, c: &mut Cur, compared: &mut usize) {
    let axis = c.int();
    assert_eq!(got.axis, axis, "{case} {what}.axis");
    check_bits(case, &format!("{what}.offset"), got.offset, c, compared);
    check_bits(case, &format!("{what}.score"), got.score, c, compared);
}

#[test]
fn symmetry_differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("SDIFF1");
    let mut compared = 0usize;
    let (mut m, mut d, mut v, mut f) = (0, 0, 0, 0);
    loop {
        if c.pos >= c.toks.len() {
            break;
        }
        let tag = c.word();
        match tag.as_str() {
            "M" => {
                m += 1;
                let case = format!("M case {m}");
                let point = c.v3();
                let axis = c.int();
                let offset = c.num();
                let plane = SymmetryPlane {
                    axis,
                    offset,
                    score: 0.0,
                };
                c.expect("r");
                check_v3(
                    &case,
                    "mirror_point",
                    &Symmetry::mirror_point(&point, &plane),
                    &mut c,
                    &mut compared,
                );
                check_v3(
                    &case,
                    "mirror_direction",
                    &Symmetry::mirror_direction(&point, &plane),
                    &mut c,
                    &mut compared,
                );
            }
            "D" => {
                d += 1;
                let case = format!("D case {d}");
                let n = c.uint();
                let mut verts = Vec::with_capacity(n);
                for _ in 0..n {
                    verts.push(c.v3());
                }
                let (probe_axis, probe_offset, probe_tol) = (c.int(), c.num(), c.num());
                c.expect("r");
                check_plane(
                    &case,
                    "detect",
                    &Symmetry::detect_plane(&verts),
                    &mut c,
                    &mut compared,
                );
                for axis in [-1, 0, 1, 2, 3] {
                    check_plane(
                        &case,
                        &format!("fixed[{axis}]"),
                        &Symmetry::fixed_plane(&verts, axis),
                        &mut c,
                        &mut compared,
                    );
                }
                check_bits(
                    &case,
                    "score",
                    Symmetry::score_plane(&verts, probe_axis, probe_offset, probe_tol),
                    &mut c,
                    &mut compared,
                );
            }
            "V" => {
                v += 1;
                let case = format!("V case {v}");
                let n = c.uint();
                let mut verts = Vec::with_capacity(n);
                for _ in 0..n {
                    verts.push(c.v3());
                }
                let (axis, offset) = (c.int(), c.num());
                let plane = SymmetryPlane {
                    axis,
                    offset,
                    score: 1.0,
                };
                Symmetry::symmetrize_vertices(&mut verts, &plane);
                c.expect("r");
                let out_n = c.uint();
                assert_eq!(verts.len(), out_n, "{case}: output vertex count");
                for (i, vert) in verts.iter().enumerate() {
                    check_v3(&case, &format!("out[{i}]"), vert, &mut c, &mut compared);
                }
            }
            "F" => {
                f += 1;
                let case = format!("F case {f}");
                let nv = c.uint();
                let mut verts = Vec::with_capacity(nv);
                for _ in 0..nv {
                    verts.push(c.v3());
                }
                let nt = c.uint();
                let mut tris = Vec::with_capacity(nt);
                for _ in 0..nt {
                    let k = c.uint();
                    let mut tri = Vec::with_capacity(k);
                    for _ in 0..k {
                        tri.push(c.uint());
                    }
                    tris.push(tri);
                }
                let nf = c.uint();
                let mut field = Vec::with_capacity(nf);
                for _ in 0..nf {
                    field.push(c.v3());
                }
                let (axis, offset) = (c.int(), c.num());
                let plane = SymmetryPlane {
                    axis,
                    offset,
                    score: 1.0,
                };
                Symmetry::symmetrize_frame_field(&verts, &tris, &mut field, &plane);
                c.expect("r");
                let out_n = c.uint();
                assert_eq!(field.len(), out_n, "{case}: output field count");
                for (i, vec) in field.iter().enumerate() {
                    check_v3(&case, &format!("fout[{i}]"), vec, &mut c, &mut compared);
                }
            }
            "T" => {
                // Timing lines are informational; the timing test compares
                // the sink. Format: `T sym ms=%.3f sink=%.17g`.
                assert_eq!(c.word(), "sym");
                c.word();
                c.word();
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(m, 91, "expected 91 M cases");
    assert_eq!(d, 78, "expected 78 D cases");
    assert_eq!(v, 67, "expected 67 V cases");
    assert_eq!(f, 78, "expected 78 F cases");
    eprintln!("symmetry replay: {m} M + {d} D + {v} V + {f} F, {compared} doubles bitwise-equal");
}
