// Differential oracle replay for the vector2/vector3 port: parses
// tests/fixtures/vector_diff.txt (generated by the C++ vector_diff_dump
// tool) and replays every case. Doubles compare BITWISE (%.17g round-trips
// exactly; the port transcribes Clang's FMA fusion with explicit mul_add,
// so every op must be bit-identical). NaNs compare by sign bit only:
// payloads are never consumed, but a dropped/toggled sign is a real bug.
use retopo_core::vector2::{self, Vector2};
use retopo_core::vector3::{self, Vector3};

const FIXTURE: &str = include_str!("../../../tests/fixtures/vector_diff.txt");

struct Cur {
    toks: Vec<String>,
    pos: usize,
}

impl Cur {
    fn new(s: &str) -> Self {
        Self {
            toks: s.split_ascii_whitespace().map(str::to_string).collect(),
            pos: 0,
        }
    }
    fn word(&mut self) -> String {
        let w = self.toks[self.pos].clone();
        self.pos += 1;
        w
    }
    fn expect(&mut self, tag: &str) {
        assert_eq!(
            self.word(),
            tag,
            "fixture parse error at token {}",
            self.pos
        );
    }
    fn flag(&mut self) -> bool {
        match self.word().as_str() {
            "1" => true,
            "0" => false,
            other => panic!("bad flag token: {other}"),
        }
    }
    fn num(&mut self) -> f64 {
        self.word().parse().expect("bad f64")
    }
    fn v2(&mut self) -> Vector2 {
        Vector2::new(self.num(), self.num())
    }
    fn v3(&mut self) -> Vector3 {
        Vector3::new(self.num(), self.num(), self.num())
    }
}

fn check_bits(case: &str, what: &str, got: f64, c: &mut Cur, compared: &mut usize) {
    let expect = c.num();
    *compared += 1;
    let same = if got.is_nan() && expect.is_nan() {
        got.is_sign_negative() == expect.is_sign_negative()
    } else {
        got.to_bits() == expect.to_bits()
    };
    assert!(
        same,
        "{case} {what}: rust={got} ({:#018x}) cpp={expect} ({:#018x})",
        got.to_bits(),
        expect.to_bits()
    );
}

fn check_v2(case: &str, what: &str, got: &Vector2, c: &mut Cur, compared: &mut usize) {
    check_bits(case, &format!("{what}.x"), got.x(), c, compared);
    check_bits(case, &format!("{what}.y"), got.y(), c, compared);
}

fn check_v3(case: &str, what: &str, got: &Vector3, c: &mut Cur, compared: &mut usize) {
    check_bits(case, &format!("{what}.x"), got.x(), c, compared);
    check_bits(case, &format!("{what}.y"), got.y(), c, compared);
    check_bits(case, &format!("{what}.z"), got.z(), c, compared);
}

fn check_flag(case: &str, what: &str, got: bool, c: &mut Cur) {
    let expect = c.flag();
    assert_eq!(got, expect, "{case} {what}: rust={got} cpp={expect}");
}

#[test]
fn vector_differential_replay() {
    let mut c = Cur::new(FIXTURE);
    c.expect("VDIFF1");
    let mut compared = 0usize;
    let (mut v2n, mut v3n, mut adv) = (0, 0, 0);
    loop {
        if c.pos >= c.toks.len() {
            break;
        }
        let tag = c.word();
        match tag.as_str() {
            "V2" => {
                v2n += 1;
                let case = format!("V2 case {v2n}");
                let (a, b, cc, p) = (c.v2(), c.v2(), c.v2(), c.v2());
                let s = c.num();
                c.expect("r");
                check_bits(&case, "len2", a.length_squared(), &mut c, &mut compared);
                check_bits(&case, "len", a.length(), &mut c, &mut compared);
                check_v2(&case, "norm", &a.normalized(), &mut c, &mut compared);
                check_bits(
                    &case,
                    "dot",
                    Vector2::dot_product(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_flag(&case, "left", a.is_on_left(&b, &cc), &mut c);
                check_v2(
                    &case,
                    "bary",
                    &Vector2::barycentric_coordinates(&a, &b, &cc, &p),
                    &mut c,
                    &mut compared,
                );
                check_flag(
                    &case,
                    "tri",
                    Vector2::is_in_triangle(&a, &b, &cc, &p),
                    &mut c,
                );
                check_flag(&case, "circle", p.is_in_circle(&a, &b, &cc), &mut c);
                check_v2(&case, "add", &(a + b), &mut c, &mut compared);
                check_v2(&case, "sub", &(a - b), &mut c, &mut compared);
                check_v2(&case, "mul", &(a * s), &mut c, &mut compared);
                check_v2(&case, "smul", &(s * a), &mut c, &mut compared);
                check_flag(&case, "eq", a == b, &mut c);
                check_flag(&case, "ne", a != b, &mut c);
                c.expect("n");
                let mut m = a;
                m.normalize();
                check_v2(&case, "normalize", &m, &mut c, &mut compared);
            }
            "V3" => {
                v3n += 1;
                let case = format!("V3 case {v3n}");
                let (a, b, cc, p) = (c.v3(), c.v3(), c.v3(), c.v3());
                let s = c.num();
                c.expect("r");
                check_bits(&case, "len2", a.length_squared(), &mut c, &mut compared);
                check_bits(&case, "len", a.length(), &mut c, &mut compared);
                check_v3(&case, "norm", &a.normalized(), &mut c, &mut compared);
                check_bits(
                    &case,
                    "dot",
                    Vector3::dot_product(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_v3(
                    &case,
                    "cross",
                    &Vector3::cross_product(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_v3(
                    &case,
                    "normal",
                    &Vector3::normal(&a, &b, &cc),
                    &mut c,
                    &mut compared,
                );
                check_bits(
                    &case,
                    "angle",
                    Vector3::angle(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_flag(&case, "iszero", a.is_zero(), &mut c);
                check_flag(&case, "lt", a < b, &mut c);
                check_bits(
                    &case,
                    "area",
                    Vector3::area(&a, &b, &cc),
                    &mut c,
                    &mut compared,
                );
                check_v3(
                    &case,
                    "bary",
                    &Vector3::barycentric_coordinates(&a, &b, &cc, &p),
                    &mut c,
                    &mut compared,
                );
                check_v3(&case, "add", &(a + b), &mut c, &mut compared);
                check_v3(&case, "sub", &(a - b), &mut c, &mut compared);
                check_v3(&case, "neg", &-a, &mut c, &mut compared);
                check_v3(&case, "muls", &(a * s), &mut c, &mut compared);
                check_v3(&case, "smul", &(s * a), &mut c, &mut compared);
                check_v3(&case, "mulv", &(a * b), &mut c, &mut compared);
                check_v3(&case, "divv", &(a / b), &mut c, &mut compared);
                check_v3(&case, "divs", &(a / s), &mut c, &mut compared);
                c.expect("n");
                let mut m = a;
                m.normalize();
                check_v3(&case, "normalize", &m, &mut c, &mut compared);
                let mut q = a;
                q += b;
                check_v3(&case, "addass", &q, &mut c, &mut compared);
                let mut t = a;
                t *= s;
                check_v3(&case, "mulass", &t, &mut c, &mut compared);
                let mut u = a;
                u /= s;
                check_v3(&case, "divass", &u, &mut c, &mut compared);
                c.expect("p2");
                let mut out2 = Vec::new();
                Vector3::project_to_2d(&[a, b, cc], &mut out2, &a, &b, &cc);
                assert_eq!(out2.len(), 3);
                for (i, v) in out2.iter().enumerate() {
                    check_v2(&case, &format!("proj2[{i}]"), v, &mut c, &mut compared);
                }
                c.expect("p3");
                let mut out3 = Vec::new();
                Vector3::project_to_3d(&[a, b, cc], &mut out3, &a, &b, &cc);
                assert_eq!(out3.len(), 3);
                for (i, v) in out3.iter().enumerate() {
                    check_v3(&case, &format!("proj3[{i}]"), v, &mut c, &mut compared);
                }
            }
            "Z" => {
                adv += 1;
                let case = format!("adversarial Z#{adv}");
                let t = c.num();
                let v2 = Vector2::new(t, t);
                let v3 = Vector3::new(t, t, t);
                c.expect("r");
                check_v2(&case, "norm2", &v2.normalized(), &mut c, &mut compared);
                check_v3(&case, "norm3", &v3.normalized(), &mut c, &mut compared);
                check_flag(&case, "iszero", v3.is_zero(), &mut c);
            }
            "P" => {
                adv += 1;
                let case = format!("adversarial P#{adv}");
                let (a, b, cc) = (c.v3(), c.v3(), c.v3());
                c.expect("r");
                check_v3(
                    &case,
                    "cross",
                    &Vector3::cross_product(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_v3(
                    &case,
                    "normal",
                    &Vector3::normal(&a, &b, &cc),
                    &mut c,
                    &mut compared,
                );
                check_bits(
                    &case,
                    "angle",
                    Vector3::angle(&a, &b),
                    &mut c,
                    &mut compared,
                );
                check_bits(
                    &case,
                    "area",
                    Vector3::area(&a, &b, &cc),
                    &mut c,
                    &mut compared,
                );
            }
            "C" => {
                adv += 1;
                let case = format!("adversarial C#{adv}");
                let (a, b, cc, p) = (c.v2(), c.v2(), c.v2(), c.v2());
                c.expect("r");
                check_flag(&case, "circle", p.is_in_circle(&a, &b, &cc), &mut c);
                check_flag(
                    &case,
                    "tri",
                    Vector2::is_in_triangle(&a, &b, &cc, &p),
                    &mut c,
                );
                check_flag(&case, "left", p.is_on_left(&a, &b), &mut c);
            }
            "E" => {
                adv += 1;
                let case = format!("adversarial E#{adv}");
                let (x, y) = (c.num(), c.num());
                c.expect("r");
                check_flag(
                    &case,
                    "eq",
                    Vector2::new(x, 0.0) == Vector2::new(y, 0.0),
                    &mut c,
                );
                check_flag(
                    &case,
                    "ne",
                    Vector2::new(x, 0.0) != Vector2::new(y, 0.0),
                    &mut c,
                );
            }
            "S" => {
                adv += 1;
                let case = format!("adversarial S#{adv}");
                let v = Vector2::new(c.num(), c.num());
                c.expect("r");
                check_bits(&case, "len2", v.length_squared(), &mut c, &mut compared);
                check_v2(&case, "norm", &v.normalized(), &mut c, &mut compared);
                check_flag(&case, "selfeq", v == v, &mut c);
            }
            "O" => {
                adv += 1;
                let case = format!("adversarial O#{adv}");
                let x = c.num();
                let (a, b, cc, d) = (
                    Vector3::new(x, 1.0, 2.0),
                    Vector3::new(0.0, 1.0, 2.0),
                    Vector3::new(0.0, x, 2.0),
                    Vector3::new(0.0, 1.0, x),
                );
                c.expect("r");
                check_flag(&case, "a<b", a < b, &mut c);
                check_flag(&case, "b<a", b < a, &mut c);
                check_flag(&case, "c<d", cc < d, &mut c);
                check_flag(&case, "d<c", d < cc, &mut c);
                check_flag(&case, "a<a", a < a, &mut c);
                check_flag(
                    &case,
                    "xxx<000",
                    Vector3::new(x, x, x) < Vector3::new(0.0, 0.0, 0.0),
                    &mut c,
                );
            }
            "T" if c.toks[c.pos] != "vec" => {
                adv += 1;
                let case = format!("adversarial T#{adv}");
                let x = c.num();
                c.expect("r");
                let e2 = c.word();
                let e3 = c.word();
                let got2 = vector2::to_string(&Vector2::new(x, -x));
                let got3 = vector3::to_string(&Vector3::new(x, 0.5, -x));
                assert_eq!(format!("[{got2}]"), e2, "{case} to_string v2");
                assert_eq!(format!("[{got3}]"), e3, "{case} to_string v3");
            }
            "T" => {
                // Timing lines are informational; the timing test compares
                // the sink. Format: `T vec ms=%.3f sink=%.17g`.
                assert_eq!(c.word(), "vec");
                c.word();
                c.word();
            }
            other => panic!("unexpected fixture tag: {other}"),
        }
    }
    assert_eq!(v2n, 150, "expected 150 V2 cases");
    assert_eq!(v3n, 150, "expected 150 V3 cases");
    eprintln!(
        "vector replay: {v2n} V2 + {v3n} V3 + {adv} adversarial, {compared} doubles bitwise-equal"
    );
}
